### PR TITLE
Fix All Loggers!

### LINKED ISSUE #1688: Node logging not working consistently
I'm attempting to connect to a local regtest neutrino node and sync it. It appears that logging is not working consistently. I'm getting to the part of `Main.scala` where we call `Node.sync()`

https://github.com/Christewart/bitcoin-s-core/blob/85cbad34b2d9308c243496bd82e98325b0b7465e/app/server/src/main/scala/org/bitcoins/server/Main.scala#L135-L146

I expect us to go into [`Node.sync()`](https://github.com/Christewart/bitcoin-s-core/blob/85cbad34b2d9308c243496bd82e98325b0b7465e/node/src/main/scala/org/bitcoins/node/Node.scala#L199) and the very first thing I expect to happen is this log statement: 

https://github.com/Christewart/bitcoin-s-core/blob/85cbad34b2d9308c243496bd82e98325b0b7465e/node/src/main/scala/org/bitcoins/node/Node.scala#L202

however this doesn't show up. You can see I added a `println` above as a sanity check, and I get this output: 

>2020-07-20T23:34:27 INFO [HTTP] After startedFP
2020-07-20T23:34:27 INFO [HTTP] node.sync block
**Starting sync**
2020-07-20T23:34:27 DEBUG [chain-verification] Querying for best block hash
2020-07-20T23:34:27 DEBUG [chain-verification] Looking for header by hash=DoubleSha256BDigestBE(2365f2ab4b7d5104510991052522d6e67dd4f979cb52cdbda1c5d7ae0b9169ef)
2020-07-20T23:34:27 DEBUG [chain-verification] getHeader result: height=122, hash=DoubleSha256BDigestBE(2365f2ab4b7d5104510991052522d6e67dd4f979cb52cdbda1c5d7ae0b9169ef), chain work=246

So it appears our logger is broken!

I added some more logs on this commit and you can see that `Node.sync()` does execute successfully, but logging doesn't work (for me!)

>Starting sync
got chainApi
2020-07-20T23:47:43 DEBUG [chain-verification] Querying for best block hash
got best hash=DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)
2020-07-20T23:47:43 DEBUG [chain-verification] Looking for header by hash=DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)
2020-07-20T23:47:43 DEBUG [chain-verification] getHeader result: height=0, hash=DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206), chain work=0
got best header=BlockHeaderDb(0,DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206),Int32Impl(1),DoubleSha256BDigestBE(0000000000000000000000000000000000000000000000000000000000000000),DoubleSha256BDigestBE(4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b),UInt32Impl(1296688602),UInt32Impl(545259519),UInt32Impl(2),0100000000000000000000000000000000000000000000000000000000000000000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4adae5494dffff7f2002000000,0)
Starting sync node, height=0 hash=DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)

The `println`s work, the `logger` does not

### PR DESCRIPTION
**Pull request by nkohen**
Fixes #1688 and more!

Fixed logging so that appenders are always started when a cached logger is retrieved, for some reason logger appenders get detached and I don't know why.

Previously what was happening is that loggers were cached per-object but appenders were stopped/detached the moment another object queried for a cached logger. The resulting behavior was that the first logs from an object/instance were seen and then once any other object did any logging the logs from the previous object would stop being added.

### CODE REVIEW

File: db-commons/src/main/scala/org/bitcoins/db/AppLoggers.scala [hunk 1]
```diff
@@ -112,8 +116,23 @@ private[bitcoins] trait AppLoggers {
     // This also will make any logger using the class name fall under the same logger
     val logger: Logger = context.getLogger(s"org.bitcoins.$name")
     logger.setAdditive(true)
-    logger.addAppender(fileAppender)
-    logger.addAppender(consoleAppender)
+    if (!AppLoggers.fileAppenders.containsKey(logger.hashCode)) {
+      val appender = newFileAppender(logger)
+      AppLoggers.fileAppenders.put(logger.hashCode, appender)
+    }
```
Comment (benthecarman) [inline db-commons/src/main/scala/org/bitcoins/db/AppLoggers.scala:122]: this should probably be a function in `AppLoggers`

File: db-commons/src/main/scala/org/bitcoins/db/AppLoggers.scala [hunk 2]
```diff
@@ -112,8 +116,23 @@ private[bitcoins] trait AppLoggers {
...
+    if (!AppLoggers.consoleAppenders.containsKey(logger.hashCode)) {
+      val appender = newConsoleAppender(logger)
+      AppLoggers.consoleAppenders.put(logger.hashCode, appender)
+    }
```
Comment (benthecarman) [inline db-commons/src/main/scala/org/bitcoins/db/AppLoggers.scala:126]: ditto

**Review by Christewart — APPROVED** [review]
Seems to work for me on #1697

**Review by Christewart — CHANGES_REQUESTED** [review]
Actually I lied, on #1697 it seems that STDOUT is working, but nothing is being written to `$HOME/.bitcoin-s/testnet3/bitcoin-s.log` 

If you look at this image, the upper right pane is my STDOUT, and the bottom right is me ` tail -F ~/.bitcoin-s/testnet3/bitcoin-s.log`. You can see that nothing is going to the log file 
Screenshot from 2020-07-25 16-43-44

**Review by Christewart — APPROVED** [review]

**Comment by Christewart** [comment]
Logging works on #1697 as of e9e3702. Nice job @nkohen !! :tada:
