### PR TITLE
2022 07 07 issue 4455

### LINKED ISSUE #4455: Blockchain parsing failure for taproot txs
I thought this was only on #3769 but seems to be in master as well (2b60bbb1c359737f896b4f3957af476a68dd0685)

```
2022-07-06T23:41:11UTC INFO [ScanBitcoind] Searching block at height=710040 hashBE=0000000000000000000b273de637ae22e33a76c7822c8bb79311ddeab3029f1e
2022-07-06T23:41:11UTC ERROR [ScanBitcoind] Failed to count witness v1 mempool txs
java.lang.IllegalArgumentException: requirement failed: DoubleSha256Digest must always be 32 bytes, got: 0
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.crypto.DoubleSha256Digest.<init>(HashDigest.scala:112)
        at org.bitcoins.crypto.DoubleSha256Digest$.fromBytes(HashDigest.scala:125)
        at org.bitcoins.crypto.DoubleSha256Digest$.fromBytes(HashDigest.scala:121)
        at org.bitcoins.crypto.Factory.apply(Factory.scala:53)
        at org.bitcoins.core.serializers.transaction.RawTransactionOutPointParser.read(RawTransactionOutPointParser.scala:22)
        at org.bitcoins.core.protocol.transaction.TransactionOutPoint$.fromBytes(TransactionOutPoint.scala:53)
        at org.bitcoins.core.protocol.transaction.TransactionOutPoint$.fromBytes(TransactionOutPoint.scala:48)
        at org.bitcoins.crypto.Factory.apply(Factory.scala:53)
        at org.bitcoins.core.serializers.transaction.RawTransactionInputParser.read(RawTransactionInputParser.scala:20)
        at org.bitcoins.core.protocol.transaction.TransactionInput$.fromBytes(TransactionInput.scala:58)
        at org.bitcoins.core.protocol.transaction.TransactionInput$.fromBytes(TransactionInput.scala:34)
        at org.bitcoins.core.util.BytesUtil.loop$1(BytesUtil.scala:33)
        at org.bitcoins.core.util.BytesUtil.parseCmpctSizeUIntSeq(BytesUtil.scala:42)
        at org.bitcoins.core.util.BytesUtil.parseCmpctSizeUIntSeq$(BytesUtil.scala:21)
        at org.bitcoins.core.util.BytesUtil$.parseCmpctSizeUIntSeq(BytesUtil.scala:52)
        at org.bitcoins.core.protocol.transaction.BaseTransaction$.fromBytes(Transaction.scala:163)
        at org.bitcoins.core.protocol.transaction.Transaction$.fromBytes(Transaction.scala:131)
        at org.bitcoins.core.protocol.transaction.Transaction$.fromBytes(Transaction.scala:109)
        at org.bitcoins.crypto.Factory.apply(Factory.scala:53)
        at org.bitcoins.core.serializers.blockchain.RawBlockSerializer.$anonfun$read$1(RawBlockSerializer.scala:19)
        at org.bitcoins.core.serializers.RawSerializerHelper.loop$1(RawBitcoinSerializerHelper.scala:29)
        at org.bitcoins.core.serializers.RawSerializerHelper.parseCmpctSizeUIntSeq(RawBitcoinSerializerHelper.scala:39)
        at org.bitcoins.core.serializers.blockchain.RawBlockSerializer.read(RawBlockSerializer.scala:19)
        at org.bitcoins.core.protocol.blockchain.Block$.fromBytes(Block.scala:73)
        at org.bitcoins.core.protocol.blockchain.Block$.fromBytes(Block.scala:48)
        at org.bitcoins.crypto.Factory.fromHex(Factory.scala:13)
        at org.bitcoins.commons.serializers.JsonReaders$BlockReads$.$anonfun$reads$17(JsonReaders.scala:298)
        at org.bitcoins.commons.serializers.SerializerUtil.processJsString(SerializerUtil.scala:51)
        at org.bitcoins.commons.serializers.JsonReaders$BlockReads$.reads(JsonReaders.scala:298)
        at play.api.libs.json.JsValue.validate(JsValue.scala:17)
        at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
        at play.api.libs.json.JsString.validate(JsValue.scala:89)
        at play.api.libs.json.JsLookupResult.validate(JsLookup.scala:165)
        at play.api.libs.json.JsLookupResult.validate$(JsLookup.scala:164)
        at play.api.libs.json.JsDefined.validate(JsLookup.scala:188)
        at org.bitcoins.rpc.client.common.Client.$anonfun$bitcoindCall$2(Client.scala:358)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### PR DESCRIPTION
**Pull request by Christewart**
fixes #4455

The problem was we weren't checking there is more than one stack element in the witness before determining if there was an annex. This transaction contains a schnorr signature that starts with `0x50` that we were detecting as annex.

https://blockstream.info/tx/a05213473724e2e7f489ae0cbe1d17eef4f6c1b9806e33e5115d85e71d81e994

### CODE REVIEW

File: core/src/main/scala/org/bitcoins/core/protocol/script/ControlBlock.scala [hunk 1]
```diff
@@ -55,12 +55,14 @@ object ControlBlock extends Factory[ControlBlock] {
...
 
+  val leafVersion: Byte = 0xc0.toByte
+
   /** BIP342 specifies validity rules that apply for leaf version 0xc0,
     * but future proposals can introduce rules for other leaf versions.
     *
     * @see https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#rationale
     */
-  val knownLeafVersions: Vector[Byte] = Vector(0xc0.toByte, 0xc1.toByte)
+  val knownLeafVersions: Vector[Byte] = Vector(leafVersion, 0xc1.toByte)
```
Comment (benthecarman) [inline core/src/main/scala/org/bitcoins/core/protocol/script/ControlBlock.scala:65]: this is a bit confusing as what 0xc1 refers to now because it is in `knownLeafVersions` but `leafVersion` is defined as `0xc0`

File: core/src/main/scala/org/bitcoins/core/protocol/script/ScriptWitness.scala [hunk 2]
```diff
@@ -238,6 +238,15 @@ object TaprootWitness {
       TaprootScriptPath(stack)
     }
   }
+
+  override def fromBytes(bytes: ByteVector): TaprootWitness = {
+    RawScriptWitnessParser.read(bytes) match {
+      case k: TaprootKeyPath    => k
+      case s: TaprootScriptPath => s
+      case x                    => sys.error(s"Could not parse taproot witness, got=$x")
```
Comment (benthecarman) [inline core/src/main/scala/org/bitcoins/core/protocol/script/ScriptWitness.scala]: This seems a bit dangerous, should write out all cases

File: core/src/main/scala/org/bitcoins/core/protocol/script/ScriptWitness.scala [hunk 3]
```diff
@@ -248,13 +257,27 @@ case class TaprootKeyPath(
...
   }
 }
 
-object TaprootKeyPath {
+object TaprootKeyPath extends Factory[TaprootKeyPath] {
+
+  override def fromBytes(bytes: ByteVector): TaprootKeyPath = {
+    RawScriptWitnessParser.read(bytes) match {
+      case keypath: TaprootKeyPath => keypath
+      case x                       => sys.error(s"Could not parse taproot keypath, got=$x")
```
Comment (benthecarman) [inline core/src/main/scala/org/bitcoins/core/protocol/script/ScriptWitness.scala]: same here

**Comment by benthecarman** [comment]
looks like there is a formatting error too

File: core/src/main/scala/org/bitcoins/core/protocol/script/ScriptWitness.scala [hunk 4]
```diff
@@ -275,7 +275,9 @@ object TaprootKeyPath extends Factory[TaprootKeyPath] {
   override def fromBytes(bytes: ByteVector): TaprootKeyPath = {
     RawScriptWitnessParser.read(bytes) match {
       case keypath: TaprootKeyPath => keypath
-      case x                       => sys.error(s"Could not parse taproot keypath, got=$x")
+      case x @ (_: TaprootScriptPath | _: TaprootWitness | _: ScriptWitnessV0 |
```
Comment (benthecarman) [inline core/src/main/scala/org/bitcoins/core/protocol/script/ScriptWitness.scala]: I think you can exlcude `TaprootWitness` here

**Review by benthecarman — APPROVED** [review]
