### PR TITLE
Fix ZMQ Config with bitcoind backend

### LINKED ISSUE #2892: Bitcoind backend does not work following the docs
I'm attempting to setup bitcoind backend following the docs here:

https://bitcoin-s.org/docs/next/getting-setup#option-b-bitcoind-backend

```
    bitcoind-rpc {
        # bitcoind rpc username
        rpcuser = my_user_name
        # bitcoind rpc password
        rpcpassword = my_password

        # Binary location of bitcoind
        binary = ${HOME}/.bitcoin-s/binaries/bitcoind/bitcoin-0.21.0/bin/bitcoind
        # bitcoind datadir
        datadir = ${HOME}/.bitcoin
        # bitcoind network binding
        bind = localhost
        # bitcoind p2p port
        port = 8333
        # bitcoind rpc binding
        rpcbind = localhost
        # bitcoind rpc port
        rpcport = 8332
        # bitcoind zmq port for all services
        zmqport = 29000
}
```

my `bitcoin.conf`

```
addresstype=bech32
server=1
txindex=1
daemon=1
dbcache=4096
blockfilterindex=1
peerblockfilters=1

rpcuser=...
rpcpassword=...
zmqpubhashtx=tcp://127.0.0.1:29000
zmqpubashblock=tcp://127.0.0.1:29000
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
```

and the error I get when running

>2021-04-12T12:28:18UTC INFO [BitcoinSServerMain] Starting wallet
2021-04-12T12:28:18UTC INFO [Wallet$WalletImpl] Starting Wallet
2021-04-12T12:28:18UTC INFO [DbValidate] Successfully validated 10 migrations (execution time 00:00.005s)
2021-04-12T12:28:18UTC INFO [DbMigrate] Current version of schema "main": 10
2021-04-12T12:28:18UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-04-12T12:28:44UTC INFO [ZMQSubscriber] starting zmq
2021-04-12T12:28:44UTC INFO [ZMQSubscriber] ZmqSubscriber connecting to uri=tcp://127.0.0.1:29000
Exception in thread "ZMQSubscriber-thread-1618230524433" org.zeromq.ZMQException: tcp://127.0.0.1 : errno 49
        at zmq.io.net.tcp.TcpAddress.resolve(TcpAddress.java:155)
        at zmq.io.net.tcp.TcpAddress.<init>(TcpAddress.java:39)
        at zmq.io.net.Address.resolve(Address.java:93)
        at zmq.SocketBase.connect(SocketBase.java:549)
        at org.zeromq.ZMQ$Socket.connect(ZMQ.java:3082)
        at org.bitcoins.zmq.ZMQSubscriber$SubscriberRunnable$.run(ZMQSubscriber.scala:43)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: tcp://127.0.0.1
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
        at zmq.io.net.tcp.TcpAddress.resolve(TcpAddress.java:132)
        ... 6 more

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #2892

### CODE REVIEW

File: app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala [hunk 1]
```diff
@@ -147,15 +148,14 @@ class BitcoinSServerMain(override val args: Array[String])
 
         blockCount <- bitcoind.getBlockCount
         // Create callbacks for processing new blocks
-        _ = bitcoindRpcConf.zmqPortOpt match {
-          case Some(_) =>
-            val zmq = BitcoindRpcBackendUtil.createZMQWalletCallbacks(wallet)
-            zmq.start()
-          case None =>
+        _ =
+          if (bitcoindRpcConf.zmqConfig == ZmqConfig()) {
```
Comment (Christewart) [inline app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala]: nit: I would make a `ZmqConfig.empty` as that is more clear as to what is going on here IMO

File: docs/config/configuration.md [hunk 2]
```diff
@@ -144,6 +144,10 @@ bitcoin-s {
         rpcport = 8332
         # bitcoind zmq port for all services
         zmqport = 29000
+        # bitcoind zmq raw tx
+        zmqpubrawtx = "tcp://127.0.0.1:28332"
+        # bitcoind zmq raw block
+        zmqpubrawblock = "tcp://127.0.0.1:28333"
```
Comment (Christewart) [inline docs/config/configuration.md:150]: `hashblock` and `hashtx` need to be defined in the config too i think?

**Review by Christewart — APPROVED** [review]
