### PR TITLE
Fix `chmod: jre/bin/java: No such file or directory` errors

### LINKED ISSUE #4492: `bitcoin-s-oracle-server` error: chmod: `jre/bin/java`: No such file or directory
I see this when unpacking `bitcoin-s-{oracle}-server` on mac

Screen Shot 2022-07-11 at 10 33 22 AM

### PR DESCRIPTION
**Pull request by Christewart**
fixes #4492 

Now you should be able to run `{bitcoin-s-cli,bitcoin-s-server,bitcoin-s-oracle-server}` from `./bin/bitcoin-s-server` OR `cd bin && ./bitcoin-s-server` 

You use to get error messages that looked like

```
chmod: jre/bin/java: No such file or directory
```

### CODE REVIEW

File: app/server/src/universal/wallet-server-extra-startup-script.sh [hunk 1]
```diff
@@ -1,10 +1,21 @@
...
 
-chmod +x jre/bin/java #make sure java is executable
+if test -f "jre/bin/java"; then
+  echo "TOPLEVELJAVA";
+  chmod +x jre/bin/java #make sure java is executable
+fi
+
+if test -f "../jre/bin/java" ; then
+  echo "NESTED JAVA";
+  chmod +x ../jre/bin/java #make sure java is executable
```
Comment (benthecarman) [inline app/server/src/universal/wallet-server-extra-startup-script.sh:14]: nit: still debug logs here
