### PR TITLE
Fail broadcasting transaction when disconnected

### LINKED ISSUE #2326: Failing to broadcast transactions
Related to #1358

In general, it seems we have problems broadcasting txs.

With DLCs, when attempting to set one up, I pressing the  `Get Funding Tx` dialog when seems to return a hash. 

I presume behind the scenes this is attempting to broadcast the tx. It doesn't seem to work though for whatever reason. It would be very useful to display the txid along with the full tx hex so i can broadcast manually if it fails. 

Obviously the perfect situation would be having retry logic on the tx broadcast, but that seems like a lot of work so the best we can do in the short term is just to display the raw tx. That way a user can manually broadcast if they need to.

Screenshot from 2020-12-05 19-06-23

### Workaround

The root cause of this problem is my node not being able to connect to neutrino.suredbits.com:8333 forwhatever reason. This means I'm not actually connected to the node. Our wallet is unaware that our node isn't connected so it silently fails broadcasting the tx.

The workaround for this is to stop, and then restart the node with `bundle/run`. I managed to get a successful connection the second time as indicated by these logs

>[info] 2020-12-06T01:09:38UTC INFO [PeerMessageSender] Attempting to connect to peer=neutrino.suredbits.com/35.163.36.246:8333
[info] 2020-12-06T01:09:38UTC INFO [PeerMessageReceiver] Connection established with peer=Peer(neutrino.suredbits.com/35.163.36.246:8333)
[info] 2020-12-06T01:09:38UTC INFO [NeutrinoNode] Our peer=Peer(neutrino.suredbits.com/35.163.36.246:8333) has been initialized
[info] 2020-12-06T01:09:38UTC INFO [NeutrinoNode] Our node has been full started. It took=471ms
[info] 2020-12-06T01:09:38UTC INFO [NeutrinoNode] Started node, best block hash 0000000000000000000e659300a26da280d67372d76d6dd040cb66cafb4a3ff7 at height 660067, with 660066 filter headers and 660066 filters
[info] 2020-12-06T01:09:38UTC INFO [DbValidate] Successfully validated 9 migrations (execution time 00:00.003s)
[info] 2020-12-06T01:09:38UTC INFO [DbMigrate] Current version of schema "main": 9
[info] 2020-12-06T01:09:38UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2020-12-06T01:09:39UTC INFO [BitcoinSServerMain] Starting neutrino node sync
[info] 2020-12-06T01:09:39UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
[info] 2020-12-06T01:09:39UTC INFO [NeutrinoNode] Starting sync node, height=660067 hash=0000000000000000000e659300a26da280d67372d76d6dd040cb66cafb4a3ff7
[info] 2020-12-06T01:09:39UTC INFO [BitcoinSServerMain] Done starting Main!
[info] 2020-12-06T01:09:41UTC INFO [ActorSystemImpl] http-rpc-server: Response for

After the GUI booted up, I attempted rebroadcasting the funding tx by the  `Get Funding Tx` dialog. I pasted the contract id into it and it sucessfully broadcasted.

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #2326

### CODE REVIEW

File: node-test/src/test/scala/org/bitcoins/node/BroadcastTransactionTest.scala [hunk 1]
```diff
@@ -25,7 +26,7 @@ class BroadcastTransactionTest extends NodeUnitTest {
   override type FixtureParam = SpvNodeConnectedWithBitcoind
 
   def withFixture(test: OneArgAsyncTest): FutureOutcome =
-    withSpvNodeConnectedToBitcoind(test)
+    withSpvNodeConnectedToBitcoind(test, Some(BitcoindVersion.V17))
```
Comment (benthecarman) [inline node-test/src/test/scala/org/bitcoins/node/BroadcastTransactionTest.scala]: Needed to do this because of #2337

**Review by Christewart — CHANGES_REQUESTED** [review]
I've restarted CI a couple of times but this seems to fail consistently: 

https://github.com/bitcoin-s/bitcoin-s/runs/1517833592#step:5:630

**Review by Christewart — APPROVED** [review]

**Comment by Christewart** [comment]
More failures on `BroadcastTransactionTest` 

https://github.com/bitcoin-s/bitcoin-s/pull/2336/checks?check_run_id=1537298211#step:5:518

https://github.com/bitcoin-s/bitcoin-s/pull/2336/checks?check_run_id=1537298243#step:5:844

File: node-test/src/test/scala/org/bitcoins/node/DisconnectedPeerTest.scala [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+  override type FixtureParam = SpvNode
+
+  def withFixture(test: OneArgAsyncTest): FutureOutcome =
+    withDisconnectedSpvNode(test)
+
+  it must "fail to broadcast a transaction when disconnected" in { node =>
+    val tx = TransactionGenerators.transaction.sampleSome
+    recoverToSucceededIf[RuntimeException] {
+      node.broadcastTransaction(tx)
```
Comment (Christewart) [inline node-test/src/test/scala/org/bitcoins/node/DisconnectedPeerTest.scala:24]: isn't this always going to trivially fail, since the tx we are referencing isn't valid to the peers utxo set ?

**Review by Christewart — APPROVED** [review]
