### PR TITLE
Fix block fetch issue #4513

### LINKED ISSUE #4513: Unable to fetch blocks when rescanning
I'm attempting to rescan a wallet on master (948d2b424e91427e1ee98b87a7d55cbd22ef6e53 ) and it hangs on this line forever. It seems we never receive a message back from our peer. This is probably related to #4511 

```
[DEBUG] [07/16/2022 14:13:49.414] [main] [EventStream] StandardOutLogger started
[DEBUG] [07/16/2022 14:13:49.865] [main] [EventStream(akka://bitcoin-s-server-1657998828942)] logger log1-Slf4jLogger started
[DEBUG] [07/16/2022 14:13:49.869] [main] [EventStream(akka://bitcoin-s-server-1657998828942)] Default Loggers started
2022-07-16T19:13:50UTC INFO [BitcoinSServerMain] version=1.9.2-77-948d2b42-SNAPSHOT jdkVersion=18
2022-07-16T19:13:50UTC INFO [BitcoinSServerMain] Starting appServer
2022-07-16T19:13:50UTC WARN [TorAppConfig] Tor daemon was requested to start, but it is disabled in the configuration file. Not starting tor
2022-07-16T19:13:51UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-16T19:13:51UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-16T19:13:51UTC INFO [VersionPrinter]
2022-07-16T19:13:51UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/dlcdb.sqlite (SQLite 3.36)
2022-07-16T19:13:51UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-16T19:13:51UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-16T19:13:51UTC INFO [VersionPrinter]
2022-07-16T19:13:51UTC INFO [DbValidate] Successfully validated 8 migrations (execution time 00:00.012s)
2022-07-16T19:13:51UTC INFO [DbMigrate] Current version of schema "main": 8
2022-07-16T19:13:51UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-16T19:13:51UTC INFO [DLCAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@26a07e24 to the dlc project
2022-07-16T19:13:51UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-16T19:13:51UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-16T19:13:51UTC INFO [VersionPrinter]
2022-07-16T19:13:51UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/nodedb.sqlite (SQLite 3.36)
2022-07-16T19:13:51UTC INFO [DbValidate] Successfully validated 5 migrations (execution time 00:00.002s)
2022-07-16T19:13:51UTC INFO [DbMigrate] Current version of schema "main": 5
2022-07-16T19:13:51UTC WARN [DbMigrate] Schema "main" has a version (5) that is newer than the latest available migration (4) !
2022-07-16T19:13:51UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-16T19:13:51UTC INFO [NodeAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@125b251e migrations fro the node project
2022-07-16T19:13:51UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV
2022-07-16T19:13:51UTC INFO [BitcoinSServerMain] Start on network MainNet
2022-07-16T19:13:51UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-16T19:13:51UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-16T19:13:51UTC INFO [VersionPrinter]
2022-07-16T19:13:51UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/chaindb.sqlite (SQLite 3.36)
2022-07-16T19:13:51UTC INFO [DbValidate] Successfully validated 7 migrations (execution time 00:00.006s)
2022-07-16T19:13:51UTC INFO [DbMigrate] Current version of schema "main": 7
2022-07-16T19:13:51UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-16T19:13:51UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV
2022-07-16T19:13:51UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-16T19:13:51UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-16T19:13:51UTC INFO [VersionPrinter]
2022-07-16T19:13:51UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/walletdb.sqlite (SQLite 3.36)
2022-07-16T19:13:51UTC INFO [DbValidate] Successfully validated 15 migrations (execution time 00:00.015s)
2022-07-16T19:13:51UTC INFO [DbMigrate] Current version of schema "main": 15
2022-07-16T19:13:51UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-16T19:13:51UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
2022-07-16T19:13:51UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
2022-07-16T19:13:51UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
2022-07-16T19:13:51UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
2022-07-16T19:13:51UTC INFO [ChainAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@646d2a1f to chain project
2022-07-16T19:13:51UTC INFO [WalletAppConfig] Starting wallet with xpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV walletName=
2022-07-16T19:13:51UTC INFO [WalletAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@72c3c0be to the wallet project
2022-07-16T19:13:51UTC INFO [BitcoinSAppConfig] Done starting BitcoinSAppConfig, it took=1755ms
2022-07-16T19:13:52UTC INFO [BitcoinSServerMain] startBitcoinSBackend()
2022-07-16T19:13:52UTC INFO [FeeProviderFactory$] Using fee provider: MempoolSpaceProvider(HourFeeTarget,MainNet,None)
2022-07-16T19:13:52UTC WARN [Server] RPC password is not set (rpchost=127.0.0.1)
2022-07-16T19:13:52UTC INFO [BitcoinSServerMain] Initialized chain api
2022-07-16T19:13:52UTC INFO [DLCAppConfig$] Using pre-existing wallet
2022-07-16T19:13:52UTC INFO [BitcoinSServerMain] Done configuring wallet, it took=749ms
2022-07-16T19:13:52UTC INFO [BitcoinSServerMain] Done configuring node, it took=750ms
2022-07-16T19:13:52UTC INFO [DLCWallet$DLCWalletImpl] Starting Wallet
2022-07-16T19:13:52UTC INFO [NeutrinoNode] Starting node
2022-07-16T19:13:52UTC INFO [PeerFinder] Peer discovery disabled.
2022-07-16T19:13:52UTC INFO [PeerManager] Done starting PeerManager
2022-07-16T19:13:52UTC INFO [NeutrinoNode] Our node has been full started. It took=119ms
2022-07-16T19:13:53UTC INFO [NeutrinoNode] Started node, best block hash 00000000000000000003053499e0edfec89bbd68d9733db2b0474c1fda32d550 at height 744849, with 744849 filter headers and 744849 filters
2022-07-16T19:13:53UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV
2022-07-16T19:13:53UTC INFO [HikariDataSource] bitcoin-s-node-db - Starting...
2022-07-16T19:13:53UTC INFO [HikariDataSource] bitcoin-s-node-db - Start completed.
2022-07-16T19:13:53UTC INFO [PeerManager] Connected to peer Peer(127.0.0.1:8333) with filters. Connected peer count 1
2022-07-16T19:13:53UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-16T19:13:53UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-16T19:13:53UTC INFO [VersionPrinter]
2022-07-16T19:13:53UTC INFO [DbValidate] Successfully validated 15 migrations (execution time 00:00.010s)
2022-07-16T19:13:53UTC INFO [DbMigrate] Current version of schema "main": 15
2022-07-16T19:13:53UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-16T19:13:53UTC INFO [DLCNode] Binding server to /0.0.0.0:2862, with tor hidden service: false
2022-07-16T19:13:53UTC WARN [DLCServer$] Tor must be enabled to negotiate a dlc, you can set this with bitcoin-s.tor.enabled=true and bitcoin-s.control.enabled=true in your bitcoin-s.conf
2022-07-16T19:13:53UTC INFO [WalletAppConfig] Starting wallet with xpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV walletName=
2022-07-16T19:13:53UTC INFO [WalletAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@71b46d9d to the wallet project
2022-07-16T19:13:53UTC INFO [DLCServer] Bound at /[0:0:0:0:0:0:0:0]:2862
2022-07-16T19:13:53UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
2022-07-16T19:13:53UTC INFO [Server] Started Bitcoin-S websocket at /127.0.0.1:19999
2022-07-16T19:13:53UTC INFO [BitcoinSServerMain] Starting neutrino node sync, it took=1365ms
2022-07-16T19:13:53UTC INFO [WalletAppConfig] Starting wallet rebroadcast task
2022-07-16T19:13:53UTC INFO [DLCWallet$DLCWalletImpl] Starting rescanning the wallet from None to None useCreationTime=true
2022-07-16T19:13:56UTC INFO [DLCWallet$DLCWalletImpl] Beginning to search for matches between 577723:744849 against 4059 spks
2022-07-16T19:13:57UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 577819
2022-07-16T19:13:58UTC INFO [DLCWallet$DLCWalletImpl] Requesting 1 block(s)
//eventually i shut down the node ...
^C2022-07-16T19:34:45UTC INFO [BitcoinSServerMain$] @@@@@@@@@@@@@@@@@@@@@ Shutting down BitcoinSServerMain$ @@@@@@@@@@@@@@@@@@@@@
2022-07-16T19:34:45UTC ERROR [BitcoinSServerMain] Exiting process
```

When i checkout out our latest release, 1.9.2, things work immediately and we can fetch a block. It seems there is some sort of a regression introduced in master since 1.9.2

### PR DESCRIPTION
**Pull request by solo1g**
The logic for fetching blocks that I added was wrong. Closes #4513

### CODE REVIEW

File: node/src/main/scala/org/bitcoins/node/Node.scala [hunk 1]
```diff
@@ -180,10 +180,17 @@ trait Node extends NodeApi with ChainQueryApi with P2PLogger {
...
-        ServiceIdentifier.NODE_NETWORK)
-      peerMsgSenderF.flatMap(
-        _.sendGetDataMessage(TypeIdentifier.MsgWitnessBlock, blockHashes: _*))
+      val syncPeerOpt = getDataMessageHandler.syncPeer
+      syncPeerOpt match {
+        case Some(peer) =>
+          peerManager
+            .peerData(peer)
+            .peerMessageSender
+            .sendGetDataMessage(TypeIdentifier.MsgWitnessBlock, blockHashes: _*)
```
Comment (benthecarman) [inline node/src/main/scala/org/bitcoins/node/Node.scala:189]: I think it still makes sense to call from a random peer here

Comment (solo1g) [reply node/src/main/scala/org/bitcoins/node/Node.scala:189]: At the moment, we simply ignore any messages from a peer that's not `syncPeer`. What you say is the ultimately the goal though.
