### PR TITLE
2020 11 13 issue 2258

### LINKED ISSUE #2258: getbestblockhash returning stale block
**Describe the bug**
`getbestblockhash` is returning a block that is 208 blocks old! It appears that might node has fallen out of sync for some reason (sort of). 

This is occurring on the latest `v0.4.0` official release.

> ./bitcoin-s-cli getbestblockhash
00000000000000000002b1202dd118fd7d720493fba2a34b00bcefd8c790584b

This corresponds to the [block at height 656299](https://blockstream.info/block/00000000000000000002b1202dd118fd7d720493fba2a34b00bcefd8c790584b)

If I query my node for blockcount I get 

>./bitcoin-s-cli getblockcount
656508

Which is accurate as of the time of this writing. 

My database also says that I am receiving headers _even though_ my `getbestblockhash` is returning an incorrect value

Screenshot from 2020-11-11 17-00-26

I'm not sure why these are internally inconsistent.

One notable thing that occurred today was a 2 block reorg on bitcoin mainent where my node was running 

https://twitter.com/BitMEXResearch/status/1326627907805065218

However if my `getbestblockhash` is 208 blocks old (as of this writing) it appears that my issue occurred yesterday before this reorg stuff occurred. 

I've attached a log file for the past two days (11-10-2020 to 11-11-2020)

[bitcoin-s-issue.log](https://github.com/bitcoin-s/bitcoin-s/files/5527212/bitcoin-s-issue.log)

### PR DESCRIPTION
**Pull request by Christewart**
This fixes #2258 

specifically this comment: https://github.com/bitcoin-s/bitcoin-s/issues/2258#issuecomment-726855565

>So now looking at [`ChainHandler.blockchains`](https://github.com/bitcoin-s/bitcoin-s/blob/8a148357d560a40bf21e7c0e3f4074cd276534fe/chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala#L37) it is pretty apparent why this is happening. 

>We cache the current set of blockchains inside of [`ChainRoutes`](https://github.com/bitcoin-s/bitcoin-s/blob/6ce7d3d7019ca11eafe347728a5d0dc83647c692/app/server/src/main/scala/org/bitcoins/server/ChainRoutes.scala#L34-L33) and then call [`ChainHandler.getBestBlockHash()`](https://github.com/bitcoin-s/bitcoin-s/blob/8a148357d560a40bf21e7c0e3f4074cd276534fe/chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala#L54) which just searches the set of `blockchains` passed into the constructor. 

>This has no way to be updated when new block headers come into the chain project. 

>I think the solution to this is to have two implementations of `ChainApi` inside of the `chain` module. 

>1. `ChainHandler` (and re-implement [`getbestblockheader`](https://github.com/bitcoin-s/bitcoin-s/blob/8a148357d560a40bf21e7c0e3f4074cd276534fe/chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala#L54) to read from the database)
>2. `ChainHandlerCached` which implements `getbestblockheader` by reading from `blockchains` stored in memory. This should only be used for things that are performance sensitive like initial block download.

I'll be testing this manually with an IBD this weekend, but I want to get initial code review and clean CI runs.

### CODE REVIEW

File: chain-test/src/test/scala/org/bitcoins/chain/blockchain/MainnetChainHandlerTest.scala [hunk 1]
```diff
@@ -177,44 +178,45 @@ class MainnetChainHandlerTest extends ChainDbUnitTest {
...
+        _ <- chainHandler.blockHeaderDAO.createAll(headersWithNoWork)
+        lowestNoWork <- chainHandler.blockHeaderDAO.getLowestNoWorkHeight
+        _ = assert(lowestNoWork == 0)
+        isMissingWork <- chainHandler.isMissingChainWork
+        _ = assert(isMissingWork)
+        newHandler <- chainHandler.recalculateChainWork
+        headerDb <- newHandler.getBestBlockHeader()
+      } yield {
+        assert(headerDb.height == headersWithNoWork.head.height)
+        /*        assert(
```
Comment (Christewart) [inline chain-test/src/test/scala/org/bitcoins/chain/blockchain/MainnetChainHandlerTest.scala]: come back and look at this

File: chain/src/main/scala/org/bitcoins/chain/blockchain/BaseBlockChain.scala [hunk 2]
```diff
@@ -114,7 +114,7 @@ private[blockchain] trait BaseBlockChainCompObject
       findPrevBlockHeaderIdx(header, blockchain) match {
         case None =>
           logger.warn(
-            s"No common ancestor found in the chain to connect to ${header.hashBE}")
+            s"No common ancestor found in the chain with tip=${blockchain.tip} to connect to ${header.hashBE}")
```
Comment (benthecarman) [inline chain/src/main/scala/org/bitcoins/chain/blockchain/BaseBlockChain.scala]: nit: should do `.tip.hashBE.hex`

File: chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala [hunk 3]
```diff
@@ -51,28 +53,38 @@ case class ChainHandler(
...
-          logger.warn(
-            s"We have multiple competing blockchains: ${(chain +: rest).map(_.tip.hashBE.hex).mkString(", ")}")
-          chain.tip
-      }
-      bestHeader
+    val blockchainsF = blockHeaderDAO.getBlockchains()
+    for {
+      blockchains <- blockchainsF
+    } yield {
+      getBestBlockHeaderHelper(blockchains)
```
Comment (benthecarman) [inline chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala]: Should use `chainTips` that should be more efficient and require less memory

File: node/src/main/scala/org/bitcoins/node/Node.scala [hunk 4]
```diff
@@ -69,19 +69,16 @@ trait Node extends NodeApi with ChainQueryApi with P2PLogger {
...
+    val peerMsgRecv: PeerMessageReceiver =
+      PeerMessageReceiver.newReceiver(chainApi = chainApi,
+                                      peer = peer,
+                                      callbacks = nodeCallbacks,
+                                      initialSyncDone = initialSyncDone)
+    val p2p = P2PClient(context = system,
+                        peer = peer,
+                        peerMessageReceiver = peerMsgRecv)
+    Future.successful(p2p)
   }
```
Comment (benthecarman) [inline node/src/main/scala/org/bitcoins/node/Node.scala]: Should remove the `Future` from this

File: chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala [hunk 5]
```diff
@@ -23,20 +23,22 @@ import scala.concurrent._
...
   * @param chainConfig config file
   */
-case class ChainHandler(
-    blockHeaderDAO: BlockHeaderDAO,
-    filterHeaderDAO: CompactFilterHeaderDAO,
-    filterDAO: CompactFilterDAO,
-    blockchains: Vector[Blockchain],
-    blockFilterCheckpoints: Map[DoubleSha256DigestBE, DoubleSha256DigestBE])(
-    implicit
+class ChainHandler(
```
Comment (benthecarman) [inline chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala:35]: Should add to `ChainHandlerCached` function

File: app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala [hunk 6]
```diff
@@ -246,11 +246,11 @@ class BitcoinSServerMain(override val args: Array[String])
       system: ActorSystem): Future[ChainApi] = {
     val blockEC =
       system.dispatchers.lookup(Dispatchers.DefaultBlockingDispatcherId)
+    val chainApi = ChainHandler.fromDatabase(
```
Comment (benthecarman) [inline app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala:249]: Should be using the cached version for the node

**Review by benthecarman — CHANGES_REQUESTED** [review]

File: node/src/main/scala/org/bitcoins/node/Node.scala (hunk 4 above)
Comment (Christewart) [reply node/src/main/scala/org/bitcoins/node/Node.scala]: This will significantly add to the diff, i'm filing an issue for it

File: chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala [hunk 7]
```diff
@@ -964,4 +969,20 @@ object ChainHandler {
...
                      blockFilterCheckpoints = Map.empty)
   }
+
+  /** Converts a [[ChainHandler]] to [[ChainHandlerCached]] by calling [[BlockHeaderDAO.getBlockchains()]] */
+  def toChainHandlerCached(chainHandler: ChainHandler)(implicit
+      ec: ExecutionContext): Future[ChainHandlerCached] = {
+    val blockchainsF = chainHandler.blockHeaderDAO.getBlockchains()
+    for {
+      blockchains <- blockchainsF
+      cached = ChainHandlerCached.apply(
```
Comment (benthecarman) [inline chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala]: nit: dont't need `.apply`

File: app/server/src/main/resources/logback.xml [hunk 8]
```diff
@@ -27,7 +27,7 @@
         </encoder>
     </appender>
 
-    <root level="INFO">
+    <root level="DEBUG">
```
Comment (benthecarman) [inline app/server/src/main/resources/logback.xml]: should revert this

File: app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala (hunk 6 above)
Comment (benthecarman) [reply app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala:249]: still need to do this

**Comment by benthecarman** [comment]
Looks like a test is failing with postgres

https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/743629025#L591

**Comment by Christewart** [comment]
When running IBD on testnet i'm seeing errors occasionally that look like this. I'm guessing some sort of race condition between callbacks being executed and the database actually containing the block?

>2020-11-15T15:18:29UTC ERROR [Wallet$WalletImpl] Error processing of block=DoubleSha256BDigestBE(0000000000000008d3788a734090d276b75e9d67e7afab2f2aa360c2df2b16f0).
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processBlock$7(TransactionProcessing.scala:62)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2020-11-15T15:18:29UTC DEBUG [Wallet$WalletImpl] Updating wallet signal completion for DoubleSha256Digest(f0162bdfc260a32a2fabafe7679d5eb776d29040738a78d30800000000000000)
2020-11-15T15:18:29UTC ERROR [DataMessageHandler] onBlockReceived Callback failed with error: 
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processBlock$7(TransactionProcessing.scala:62)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2020-11-15T15:18:29UTC INFO [DataMessageHandler] Received headers message with 2000 headers
2020-11-15T15:18:29UTC DEBUG [BlockHeaderDAO] Getting chain tips from database
2020-11-15T15:18:29UTC DEBUG [BlockHeaderDAO] Max block work: 441091991171884283132
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to connect 2000 headers to 1 blockchains
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000055f523239d935743d36e4f79a727b2a986c55afe47f1516e6136fa3 with prevhash=0000000016cf5858b64e3a1d42e6221a938b1e3d04fa99d16846c455fa6780d9 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000055f523239d935743d36e4f79a727b2a986c55afe47f1516e6136fa3 with prevhash=0000000016cf5858b64e3a1d42e6221a938b1e3d04fa99d16846c455fa6780d9 to chain of 2017 headers with tip 0000000016cf5858b64e3a1d42e6221a938b1e3d04fa99d16846c455fa6780d9
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=00000000055f523239d935743d36e4f79a727b2a986c55afe47f1516e6136fa3, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000001e7db625cbfd722176dd95330f51dee9632826081cef5ff8bbb78aee with prevhash=00000000055f523239d935743d36e4f79a727b2a986c55afe47f1516e6136fa3 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000001e7db625cbfd722176dd95330f51dee9632826081cef5ff8bbb78aee with prevhash=00000000055f523239d935743d36e4f79a727b2a986c55afe47f1516e6136fa3 to chain of 2016 headers with tip 00000000055f523239d935743d36e4f79a727b2a986c55afe47f1516e6136fa3
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=000000001e7db625cbfd722176dd95330f51dee9632826081cef5ff8bbb78aee, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000002f52db2b10adb6f470c95a9b349c6b9098b10f9b35f07e31ac74ad0a with prevhash=000000001e7db625cbfd722176dd95330f51dee9632826081cef5ff8bbb78aee to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000002f52db2b10adb6f470c95a9b349c6b9098b10f9b35f07e31ac74ad0a with prevhash=000000001e7db625cbfd722176dd95330f51dee9632826081cef5ff8bbb78aee to chain of 2016 headers with tip 000000001e7db625cbfd722176dd95330f51dee9632826081cef5ff8bbb78aee
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=000000002f52db2b10adb6f470c95a9b349c6b9098b10f9b35f07e31ac74ad0a, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000001048aa68fc410957343e35a516898f69f7a05df0d0300f1fe4bdab7a with prevhash=000000002f52db2b10adb6f470c95a9b349c6b9098b10f9b35f07e31ac74ad0a to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000001048aa68fc410957343e35a516898f69f7a05df0d0300f1fe4bdab7a with prevhash=000000002f52db2b10adb6f470c95a9b349c6b9098b10f9b35f07e31ac74ad0a to chain of 2016 headers with tip 000000002f52db2b10adb6f470c95a9b349c6b9098b10f9b35f07e31ac74ad0a
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=000000001048aa68fc410957343e35a516898f69f7a05df0d0300f1fe4bdab7a, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000112bdd6e10ab5f6d862f7327563656b170268497a28ce11ee22cef2e with prevhash=000000001048aa68fc410957343e35a516898f69f7a05df0d0300f1fe4bdab7a to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000112bdd6e10ab5f6d862f7327563656b170268497a28ce11ee22cef2e with prevhash=000000001048aa68fc410957343e35a516898f69f7a05df0d0300f1fe4bdab7a to chain of 2016 headers with tip 000000001048aa68fc410957343e35a516898f69f7a05df0d0300f1fe4bdab7a
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=00000000112bdd6e10ab5f6d862f7327563656b170268497a28ce11ee22cef2e, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000001c8d0c36febb14298e67c125e04110fe0f5c46050c47cb3b7038ace2 with prevhash=00000000112bdd6e10ab5f6d862f7327563656b170268497a28ce11ee22cef2e to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000001c8d0c36febb14298e67c125e04110fe0f5c46050c47cb3b7038ace2 with prevhash=00000000112bdd6e10ab5f6d862f7327563656b170268497a28ce11ee22cef2e to chain of 2016 headers with tip 00000000112bdd6e10ab5f6d862f7327563656b170268497a28ce11ee22cef2e
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=000000001c8d0c36febb14298e67c125e04110fe0f5c46050c47cb3b7038ace2, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000007006ac26eff1a6b3b424559860ac1d9d7942b617a529d88563bcf3 with prevhash=000000001c8d0c36febb14298e67c125e04110fe0f5c46050c47cb3b7038ace2 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000007006ac26eff1a6b3b424559860ac1d9d7942b617a529d88563bcf3 with prevhash=000000001c8d0c36febb14298e67c125e04110fe0f5c46050c47cb3b7038ace2 to chain of 2016 headers with tip 000000001c8d0c36febb14298e67c125e04110fe0f5c46050c47cb3b7038ace2
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=00000000007006ac26eff1a6b3b424559860ac1d9d7942b617a529d88563bcf3, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000005158f4770a8288366872cdc2351b6b83711fabed2f749b21221b37 with prevhash=00000000007006ac26eff1a6b3b424559860ac1d9d7942b617a529d88563bcf3 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000005158f4770a8288366872cdc2351b6b83711fabed2f749b21221b37 with prevhash=00000000007006ac26eff1a6b3b424559860ac1d9d7942b617a529d88563bcf3 to chain of 2016 headers with tip 00000000007006ac26eff1a6b3b424559860ac1d9d7942b617a529d88563bcf3
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=00000000005158f4770a8288366872cdc2351b6b83711fabed2f749b21221b37, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000003b1dd5dfc20e6d0321cb0d32de11531de41d01f0d4d0307dcf2f84 with prevhash=00000000005158f4770a8288366872cdc2351b6b83711fabed2f749b21221b37 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000003b1dd5dfc20e6d0321cb0d32de11531de41d01f0d4d0307dcf2f84 with prevhash=00000000005158f4770a8288366872cdc2351b6b83711fabed2f749b21221b37 to chain of 2016 headers with tip 00000000005158f4770a8288366872cdc2351b6b83711fabed2f749b21221b37
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=00000000003b1dd5dfc20e6d0321cb0d32de11531de41d01f0d4d0307dcf2f84, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=0000000004a8ad145c725c9e633fcfc013494e2ce8ea8cace800c192144c2955 with prevhash=00000000003b1dd5dfc20e6d0321cb0d32de11531de41d01f0d4d0307dcf2f84 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=0000000004a8ad145c725c9e633fcfc013494e2ce8ea8cace800c192144c2955 with prevhash=00000000003b1dd5dfc20e6d0321cb0d32de11531de41d01f0d4d0307dcf2f84 to chain of 2016 headers with tip 00000000003b1dd5dfc20e6d0321cb0d32de11531de41d01f0d4d0307dcf2f84
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=0000000004a8ad145c725c9e633fcfc013494e2ce8ea8cace800c192144c2955, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000355c0e2b8df3da9609bdc4d68015e1a1a08b2f10e7b75d1e3abea1d1 with prevhash=0000000004a8ad145c725c9e633fcfc013494e2ce8ea8cace800c192144c2955 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000355c0e2b8df3da9609bdc4d68015e1a1a08b2f10e7b75d1e3abea1d1 with prevhash=0000000004a8ad145c725c9e633fcfc013494e2ce8ea8cace800c192144c2955 to chain of 2016 headers with tip 0000000004a8ad145c725c9e633fcfc013494e2ce8ea8cace800c192144c2955
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=00000000355c0e2b8df3da9609bdc4d68015e1a1a08b2f10e7b75d1e3abea1d1, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000004b52c8c46674fce3ec6e354693d61e92e6d428bfa760d4aa99bff241 with prevhash=00000000355c0e2b8df3da9609bdc4d68015e1a1a08b2f10e7b75d1e3abea1d1 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000004b52c8c46674fce3ec6e354693d61e92e6d428bfa760d4aa99bff241 with prevhash=00000000355c0e2b8df3da9609bdc4d68015e1a1a08b2f10e7b75d1e3abea1d1 to chain of 2016 headers with tip 00000000355c0e2b8df3da9609bdc4d68015e1a1a08b2f10e7b75d1e3abea1d1
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=000000004b52c8c46674fce3ec6e354693d61e92e6d428bfa760d4aa99bff241, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000000f54e093df0ffae1045f1123d34590c4d5dfcb043a160ee1110bbab2 with prevhash=000000004b52c8c46674fce3ec6e354693d61e92e6d428bfa760d4aa99bff241 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000000f54e093df0ffae1045f1123d34590c4d5dfcb043a160ee1110bbab2 with prevhash=000000004b52c8c46674fce3ec6e354693d61e92e6d428bfa760d4aa99bff241 to chain of 2016 headers with tip 000000004b52c8c46674fce3ec6e354693d61e92e6d428bfa760d4aa99bff241
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=000000000f54e093df0ffae1045f1123d34590c4d5dfcb043a160ee1110bbab2, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000002eb666ae23ecd19e35bc3465f76d4aef84c87dbc6d21d7e5c22a17ee with prevhash=000000000f54e093df0ffae1045f1123d34590c4d5dfcb043a160ee1110bbab2 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000002eb666ae23ecd19e35bc3465f76d4aef84c87dbc6d21d7e5c22a17ee with prevhash=000000000f54e093df0ffae1045f1123d34590c4d5dfcb043a160ee1110bbab2 to chain of 2016 headers with tip 000000000f54e093df0ffae1045f1123d34590c4d5dfcb043a160ee1110bbab2
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=000000002eb666ae23ecd19e35bc3465f76d4aef84c87dbc6d21d7e5c22a17ee, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=0000000038b902018ebe1ce8587d8e8f4222ae5ffb2515458fc34ee24f815ed0 with prevhash=000000002eb666ae23ecd19e35bc3465f76d4aef84c87dbc6d21d7e5c22a17ee to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=0000000038b902018ebe1ce8587d8e8f4222ae5ffb2515458fc34ee24f815ed0 with prevhash=000000002eb666ae23ecd19e35bc3465f76d4aef84c87dbc6d21d7e5c22a17ee to chain of 2016 headers with tip 000000002eb666ae23ecd19e35bc3465f76d4aef84c87dbc6d21d7e5c22a17ee
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=0000000038b902018ebe1ce8587d8e8f4222ae5ffb2515458fc34ee24f815ed0, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000001ecd50ae16622b75204278735c80a95745e13741e3ebb0e4ce0d4891 with prevhash=0000000038b902018ebe1ce8587d8e8f4222ae5ffb2515458fc34ee24f815ed0 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000001ecd50ae16622b75204278735c80a95745e13741e3ebb0e4ce0d4891 with prevhash=0000000038b902018ebe1ce8587d8e8f4222ae5ffb2515458fc34ee24f815ed0 to chain of 2016 headers with tip 0000000038b902018ebe1ce8587d8e8f4222ae5ffb2515458fc34ee24f815ed0
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=000000001ecd50ae16622b75204278735c80a95745e13741e3ebb0e4ce0d4891, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000247150439149f30cf5cc3770da60ece8c2ede0ee810a15a0cb6b6b9c with prevhash=000000001ecd50ae16622b75204278735c80a95745e13741e3ebb0e4ce0d4891 to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000247150439149f30cf5cc3770da60ece8c2ede0ee810a15a0cb6b6b9c with prevhash=000000001ecd50ae16622b75204278735c80a95745e13741e3ebb0e4ce0d4891 to chain of 2016 headers with tip 000000001ecd50ae16622b75204278735c80a95745e13741e3ebb0e4ce0d4891
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=00000000247150439149f30cf5cc3770da60ece8c2ede0ee810a15a0cb6b6b9c, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000000049d12e951642a4958492fd70ee663156f027ceba623c31d239e42f with prevhash=00000000247150439149f30cf5cc3770da60ece8c2ede0ee810a15a0cb6b6b9c to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=000000000049d12e951642a4958492fd70ee663156f027ceba623c31d239e42f with prevhash=00000000247150439149f30cf5cc3770da60ece8c2ede0ee810a15a0cb6b6b9c to chain of 2016 headers with tip 00000000247150439149f30cf5cc3770da60ece8c2ede0ee810a15a0cb6b6b9c
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=000000000049d12e951642a4958492fd70ee663156f027ceba623c31d239e42f, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000007f0b65d65877821ee04076d0a132b5b4f7c97d53d3218664d3638e with prevhash=000000000049d12e951642a4958492fd70ee663156f027ceba623c31d239e42f to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=00000000007f0b65d65877821ee04076d0a132b5b4f7c97d53d3218664d3638e with prevhash=000000000049d12e951642a4958492fd70ee663156f027ceba623c31d239e42f to chain of 2016 headers with tip 000000000049d12e951642a4958492fd70ee663156f027ceba623c31d239e42f
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Successfully verified=00000000007f0b65d65877821ee04076d0a132b5b4f7c97d53d3218664d3638e, connecting to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=0000000011014763beb1fd2d78cc3b749250aa6d12d8c76aad6000fbbb7935b1 with prevhash=00000000007f0b65d65877821ee04076d0a132b5b4f7c97d53d3218664d3638e to chain
2020-11-15T15:18:29UTC DEBUG [Blockchain$] Attempting to add new tip=0000000011014763beb1fd2d78cc3b749250aa6d12d8c76aad6000fbbb7935b1 with prevhash=00000000007f0b65d65877821ee04076d0a132b5b4f7c97d53d3218664d3638e to chain of 2016 headers with tip 00000000007f0b65d65877821ee04076d0a132b5b4f7c97d53d3218664d3638e

**Comment by Christewart** [comment]
So looking at the error message above, it appears that [`0000000000000008d3788a734090d276b75e9d67e7afab2f2aa360c2df2b16f0`](https://blockstream.info/testnet/block/0000000000000008d3788a734090d276b75e9d67e7afab2f2aa360c2df2b16f0) was a block that was mined while IBD was going on. 

We don't really handle this currently AFAICT and we need to file an issue to address it.

**Comment by Christewart** [comment]
#2263 is filed for the comment above ^

File: node/src/main/scala/org/bitcoins/node/Node.scala (hunk 4 above)
Comment (Christewart) [reply node/src/main/scala/org/bitcoins/node/Node.scala]: #2262

File: app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala [hunk 9]
```diff
@@ -246,11 +246,12 @@ class BitcoinSServerMain(override val args: Array[String])
       system: ActorSystem): Future[ChainApi] = {
     val blockEC =
       system.dispatchers.lookup(Dispatchers.DefaultBlockingDispatcherId)
-    val chainApi = ChainHandler.fromDatabase(
-      blockHeaderDAO = BlockHeaderDAO()(blockEC, chainAppConfig),
-      CompactFilterHeaderDAO()(blockEC, chainAppConfig),
-      CompactFilterDAO()(blockEC, chainAppConfig))
+
     for {
+      chainApi <- ChainHandlerCached.fromDatabase(
```
Comment (benthecarman) [inline app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala]: Sorry, looks like I was wrong. This was supposed to be a regular `ChainHandler` so the wallet and chain routes use the db and it needs to be changed on Node.scala line 72 to be the cached version so we get the optimizations

File: app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala [hunk 10]
```diff
@@ -93,7 +93,7 @@ class BitcoinSServerMain(override val args: Array[String])
         wallet <- configuredWalletF
         _ <- node.start()
         _ <- wallet.start()
-        chainApi = node.chainApiFromDb()
+        chainApi <- node.chainApiFromDb()
```
Comment (benthecarman) [inline app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala]: This returns the cached version now, should use `chainApiF`

**Review by benthecarman — APPROVED** [review]
