### PR TITLE
Fix rescans that are larger than the batch size

### LINKED ISSUE #1911: Log progress during rescans
We don't have any logs indicating we are making progress during a rescan

### LINKED ISSUE #1912: Rescan broken does not update balance
It appears that rescaning is broken, I am running on 1c84dc330f1674fbf9beff3d4b5202b30992a83c

> ./bitcoin-s-cli rescan --force

and i saw this in my logs

>2020-08-26T20:43:23 INFO [WALLET] Beginning to search for matches between 1449936:1824886 against 200 spks

However because of #1911 i can't tell if things are continuing. I don't think they are as my visualvm instance looks like there is nothing happening

Screenshot from 2020-08-26 15-50-34

My balance before rescanning was 1.6 tBTC 

and now 

> ./bitcoin-s-cli getbalance
0E-8 BTC

It does appear I get stuff happenign in my logs, due to a period of high activity on testnet i'm receiving blocks 

>2020-08-26T20:52:00 DEBUG [P2P] Processing 1 filters
2020-08-26T20:52:00 DEBUG [chain-verification] processFilters: messages=Vector(CompactFilterMessage(Basic,DoubleSha256Digest(2ad1b7e623ca50497fdd460d3cc4ca6eb174c1c23aa665ebfda6000000000000),ByteVector(4 bytes, 0x014242f0)))
2020-08-26T20:52:00 DEBUG [chain-verification] processFilters: filterHeaders=Vector(CompactFilterDb(hashBE=DoubleSha256BDigestBE(1ea18da6c333b248ce0459f5a55f2eaeed36a504cc00d4c34bba93c9b53ea724),filterHashBE=DoubleSha256BDigestBE(8eb739c738eee8ad8e3e0860a1ce9533b32c6aa96dd32a6ac2eb9042616f0280),previousFilterHeaderBE=DoubleSha256BDigestBE(59a6b91bb886b297f59f150163dfe39257c015054fa15c79ac5fee30d649997f),blockHashBE=DoubleSha256BDigestBE(000000000000a6fdeb65a63ac2c174b16ecac43c0d46dd7f4950ca23e6b7d12a),height=1824919))
2020-08-26T20:52:00 INFO [chain-verification] Processed filters from height=1824919 to 1824919

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #1911
Fixes #1912 
Closes #1914 

We were using `batchExecute` instead of `batchAndSyncExecute` which would cause us only to receive the last batch of blocks we needed, instead of all of the blocks we needed. Also, `findMatches` needed to be changed to return a `Vector` instead of an `Iterator`, I'm not entirely sure why but doing `Iterator.toVector` would always return `Vector.empty`, maybe because we already iterated through it?

### CODE REVIEW

**Comment by Christewart** [comment]
Good news 

>2020-08-27T11:43:26 INFO [WALLET] Matched 111 blocks on rescan
2020-08-27T11:43:26 INFO [WALLET] Requesting 111 block(s)
2020-08-27T11:43:26 INFO [P2P] Sending getdata=GetDataMessage(inventoryCount=1, inventories=Vector(Inventory(MsgBlock,DoubleSha256Digest(62d34461f297083732f227909776cb4858d3c54e2c481019ec00000...) to peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333)

Bad news, when i go to request the full blocks:

>2020-08-27T11:43:26 DEBUG [P2P] Sending msg=getdata to peer=neutrino.testnet3.suredbits.com/34.210.154.40:18333
2020-08-27T11:43:26 ERROR [P2P] Cannot send a message to our peer when we are not connected! payload=GetDataMessage(inventoryCount=1, inventories=Vector(Inventory(MsgBlock,DoubleSha256Digest(62d34461f297083732f227909776cb4858d3c54e2c481019ec00000...) peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333)

File: wallet/src/main/scala/org/bitcoins/wallet/internal/RescanHandling.scala [hunk 1]
```diff
@@ -107,10 +107,9 @@ private[wallet] trait RescanHandling extends WalletLogger {
         _ = logger.info(
           s"Beginning to search for matches between ${startHeight}:${endHeight} against ${scripts.length} spks")
         range = startHeight.to(endHeight)
-        matched <- FutureUtil.batchExecute(
+        matched <- FutureUtil.batchAndSyncExecute(
```
Comment (Christewart) [inline wallet/src/main/scala/org/bitcoins/wallet/internal/RescanHandling.scala:110]: We should really add a unit test for this, it should be trivial no? Basically make the rescan bigger then `batchSize`?

**Review by Christewart — CHANGES_REQUESTED** [review]

File: wallet/src/main/scala/org/bitcoins/wallet/internal/RescanHandling.scala (hunk 1 above)
Comment (benthecarman) [reply wallet/src/main/scala/org/bitcoins/wallet/internal/RescanHandling.scala:110]: Added

**Review by Christewart — APPROVED** [review]
