### PR TITLE
2021 11 23 crud action

### LINKED ISSUE #3844: dlcdb funding_inputs.out_point unique constraint failed multiple outputs same tx
My wallet selected two utxos from the same funding transaction [8c137c7f5000e5ce0035f9fb868acf7cc5706891a9da17d0e44e3033dd15c0aa](https://blockstream.info/tx/8c137c7f5000e5ce0035f9fb868acf7cc5706891a9da17d0e44e3033dd15c0aa)

>8c137c7f5000e5ce0035f9fb868acf7cc5706891a9da17d0e44e3033dd15c0aa:91

>8c137c7f5000e5ce0035f9fb868acf7cc5706891a9da17d0e44e3033dd15c0aa:105

The offer has 10 funding outputs total, and two of them happen to be from the same tx. I believe this is some service that has been posting dust outputs to addresses to try and surveil them long term

Here is the full offer

>a71a006fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000fdd82efd033400000000000186a0fda720480012fda7263c000401000000000000000000000001fdea60000000000000c350000001fe0001d4c000000000000186a0000001fe0003ffff00000000000186a00000fda724020000fda712fd02dafdd824fd02d4e4940b5c507fa0ad208f90182034d0b8318b1a682e29aaddcd2ba3f365c383fcc3992ff57c9cee8724170798abb03efca738dcda7f1e5fbe1842c41b1d603f7904ba9838623f02c940d20d7b185d410178cff7990c7fcf19186c7f58c7c4b8defdd822fd026e0012a83876a19b89b28555e9a76adb6336ff3144c983e65af63281a878dc519d889535ea0d03d3ba09e0cb0225691395ceee6c92df4cee1a5e90d4dd499d3598de0770945a614653cceca4e8cc4a31947eeeaba7a54042412d707a9e35350fab8906bc408e8096f7542d4577f8cebf751bf05bcbeddf33a57fddea50923bb7abc66a0f2bdf85f7ed09deaf49ce2619c1acdc2a854bc2eb7004c2d7c1c2c3ff94d5896ffeb3ec7f7b65521ab71aab516dca2a79156f2e84c9997a1802fbe49c348fb80ac4078ce464f2745d10de73844b791a42ee0abcb34ec5eb23ea2e7a361e0ba257acd4b5f2344fec63c94ed373050df11a016f76ac3af8e903b5fc6d9f860f344d817d273b13617cd5a47f32277dd95323e019d8b92ccf140d7697a8357079f788c426aeccac83f2658c3f4a5d50ed6d396ef9761236d10a08ac3376aded93cdaa8cb8c3c6bceb2c0590d8e58e52b7ec0b584f2d51d1f8d0b0478970500d92a938c3e748ad669a351976595308e050fa521f259dab6ab97338e307135af007a1f3f0c4326c3d14736a7aa359f2e8650605013d4b8de11df3c2ae1d2057f9aad042d8f91577f2c95b120a1ab6625d0c1f04bb2e566f2f81284429815f50a4f1a41140b133f7ec982dabec0d4ae927ec2fb8414ede94b6ba1b7ab7a1f032f64324fa9e7b5b3174afe16a044d71b8340ed7f006b752090233e4f7d78810fbf1bbe0776ef5ea31db31b2618f5ad442b717ea8b98b3f765bed501909ff2d6e1d359ff3482b6f19fb11ccaa21af195e453dd6f6c95e239d2801c9fc5caf8cb7be1bb1d619c9f80fdd80a100002000642544355534400000000001213446572696269742d4254432d32334e4f563231029a0d3a261804afb0e7ed265e8b6cbc05fc2b7d1a51fe806f9a840e5496e7bfb8001600142a936ba471a4e3ef46fb40383ad999550fbd4ace29457e7349588048000000000000c350000afda714fd024725a99524ff29e23d023102000000000103154c7717fcc4d1768be6a743bbcda746003c7d072026507d0027a8b6e0a507aa0100000000ffffffff28ba7257a794050d485dc0bb18e7593f89d06f02736feb8cd4493851fa8787e10100000000ffffffff7c6f25066930cc04634a843769395ba9ae0d14e5acffd812aa8886de523b37290100000000ffffffff0323ad0100000000002200205cf4bb9ced93fc5e6945e66dab2a69626507ea98aa5ab256bf7207881b96da6d9b0400000000000016001452584eb56f12d421e5efc49ecddc5eb873958cc054bb1a000000000016001448560654ca7b9e9f2d1c5aa1753b86ede0d8f0cf0247304402201c6e837e66d50593b2b2870171b07e3ebea10254e0c8f96c84d0a6858d555941022025c510efaad7498eb256f9d3f4b2400dff8ad745ceb36ab2539847c5a0a38e8901210349ba5cb6c8789ebe90efdf9823ea955581f7a334274ac8adbb9e62cba846c946024730440220139a519f463e5785bb4f92d128f408a3ba2d3e98ab545f451c26ba6bef332f4402200c34dd76965aa9eeebedc8c247d589a96d4fed210a9205d35c7aa3a2005a21a8012103befb8fdbe90fc1599843efa07ea7fc55092d801e0e3a98c698f9db5cb68a159b0247304402207e674707f31ff1ab4c5a68483a07186899b08eac63e2a653e60029571e80171002207806ac1c73c108ae214357be17035450545f894c783713e7b23cfb1d7b633598012103ec3ececed56128fdd6696e2b53b68895c5f3e8b6a57d107fb0b28d724843a01c0000000000000001fffffffd006b0000fda714fd2f728da4821a7a1bb8c22f5c0200000000010139b972a98c6e5a707b4eb93bf7987c2ea92fc507be28093115e31eb9b15169d15f02000000fdfffffffd6e0123020000000000001976a91403b7892656a4c3df81b2f3e974f8e5ed2dc78dee88ac23020000000000001976a914075b7dfca1465daa6f51b8497af83c10042ef39988ac23020000000000001976a91408d2de7257e4f777653b939c6bcb7401aeabf1ff88ac23020000000000001976a91404d9d15e67e6f20551992e03039711e59281f72888ac23020000000000001976a91406f61b94f0e562e41e7137a8b0aa78db6102925788ac23020000000000001976a91409cc4cb806f792fe235c1b8149c0267b12067c9788ac23020000000000001976a9140a9598557e4075d6543a51a33a6a84d6945b6a8e88ac23020000000000001600149fb2f9537a8fd38df559346405be2baa3c72c90d230200000000000017a914083dc9041c5af68d3a84b5649f38300ba8ce2bf987230200000000000017a914166278d881b3fe8d1fe8fcc71a94b1381f65c6e387230200000000000017a9144947e8225918b63e0a1146715c1d31a9db29d2658723020000000000001976a91438c04525a19adcbe2ee618c371b819a1842aec6788ac23020000000000001976a9146261111744bcb237fc16475b58966e05e49ee91488ac2302000000000000160014f8f416e8650cf65853d9b2ccb68f291736ce9f16230200000000000017a914cafecd5bd4e863243325220c2ae77acd4e6a483a87230200000000000016001415bda5f82091653d281bed4baf448c3e836894fa230200000000000017a914d798abd4c7b615cbbda823bc1ac90aa95a6c5d2087230200000000000017a914a61ad56f619d34cb27e8e6084e61d0c781b57043872302000000000000160014c390a98f9bd670f7fffd05ad0c49030ea3558e0d230200000000000017a914ab7cd63a2467544015f1b836bc7ee825014ed1f68723020000000000001600140e28c69bda7fc84d7596ac5ab984108eec189039230200000000000017a914d686e9e2933770f2f0505940bd1b71961278436e87230200000000000017a914d11e7c96aa252713b3e952f0aa6cb5dab58454888723020000000000001976a914ab8df34991a3904bfc7af8695d25e878272a80da88ac230200000000000017a914f90558a334d9e94ed55f2758d45d77aa2a12a4b387230200000000000017a914c576afd0b25b74b0536ad748d5c0caf4dc02aa728723020000000000001976a9147f162d1676d136c43103eb829ea4fc0144356ebf88ac230200000000000017a914af9769bb90961b4cceb63b6aa658c6b08b6c72368723020000000000001976a914a2d2ff77f0532b78cde36b3342cf8d39ed25310b88ac23020000000000001976a9147b00ba7bb0706d0d3513c25f0e176ec10aa8357a88ac23020000000000001600148e5d7d761aa81e21d44794ac18f327043bb51c29230200000000000017a914dd3d5c36925f9da35a1e41cc767662225907d35687230200000000000017a91492948622bd64e5ab5cc3131f46fd6e020ec9cd778723020000000000001976a91404bc122a97b3d767c74d9903ca0fa9ae759a4f7788ac2302000000000000160014800a2fa1c5ce8f76066337945a30bf20676d3e74230200000000000017a91495422ffb24b0b15582c0d6dd85ddd512ae932a1e87230200000000000017a9149e9fac02c01735cde61fa38599f6277c0a9d50e38723020000000000001976a91478729f374b26f142b9fd0aa95c18ec177aa5718a88ac23020000000000001976a914117abda60c33332922cbc775ba1736c3962e8fc788ac23020000000000001976a91486ee82444dbef6b1a1b1a80178aec6e50a02666188ac230200000000000017a9144c28496aa3e360638395ae867c52a376d9b676028723020000000000001976a91452791bea99155d14fc7aa2be33432e8d5a6e7acc88ac230200000000000017a914a038e6d23699603fa481830d233aadc9ba1a50a587230200000000000017a914999e70797506b99f9fe7425f4b04223968ff54518723020000000000001976a91452b0bf8ad6ec03bfa28f946025a9ec118c9438d688ac230200000000000017a914ceb97a9a76bddc2e3c291bb57ccf08bd6ef26b3387230200000000000017a914059e93240e9ad13a0cefef0bd0da7af09c63efa787230200000000000017a914c5b4340a8d91046723b926fd070eddd0e3aea8798723020000000000001976a914d9081422d11330156348eed7188296d7f86a1ba188ac230200000000000017a914c4de313f3a10e3cd00e63a6192ec77d97b393f648723020000000000001976a914152924f27f61c0e2d74b6789eba026320e5157c588ac230200000000000017a91467835200a0c01b1c7b6985daa6d6e20bc42a83d187230200000000000017a9148ad3fad7a520fd92150e2cd71e5fc94cfc58e4448723020000000000001976a91402826240dc63aaa77ab740b589b71dccd328e81c88ac23020000000000001976a9145fd10d16dee6404b86867ba316d9fc4bf120f36388ac23020000000000001976a914a068282adf132d1f09394d1bc9ce6fb6d0a9fcec88ac23020000000000001976a914fd5801e308fad7a10f8aa35c3631bd9f1a29ca2a88ac23020000000000001976a91441d2321f1f48475795bb63e9ba92253558eafd3488ac230200000000000016001440d085fc97c7f10d8e8941df91cfdb14c8f31773230200000000000017a914f3b478c591c1998e204c4139cf7acaf2775f257787230200000000000017a914a42aebef7e9394c534ad3921017236fd831b375287230200000000000017a91405ebff2bb06018f1dcbabdbdab3ffd13f70a0a218723020000000000001976a9147426386edb015d6ab9f7a03ea9d9fec2f88087f988ac230200000000000017a914ffcdc453f7c2233cddc6f1a3c5dc9f1dd457c66b8723020000000000001976a91437656021883983ddf2a2947b923671b4f407cbcf88ac2302000000000000160014b6f82d7f07c3f5be91fed19f76062581612e9c72230200000000000016001407494f429133c6d580ed901ca22b793a4b6f031a230200000000000017a914503e431c5cddfcbcba6b6b7a58b8c0eb4bb9372e8723020000000000001976a914ee30800a1ae846689dcb62d10d73bdd53b12263088ac23020000000000001976a9146065c5d7d9b0f8dcdad5da95ff8b2d70be7cf40088ac2302000000000000160014f402151c8388fa91172f1d0c85b25b0e680692e823020000000000001976a914c6a0c630aff95f37c99681a8caa9ce414baf3b2488ac230200000000000017a914703e36245b8e117b6126624bdc06fc8af0786ced87230200000000000017a9142e84d2d9ff58e5158da8c4b73e607e458e5bcee68723020000000000001976a91439b03548d49ea1fffd7491be87c25534d92b65d688ac23020000000000001976a914da7780d7ec425b2164f4c7851c1947f799a317c888ac230200000000000017a914627a2a7a29265badc12e612622957ec7a60465c38723020000000000001600148ca512ac6642963d71b3e17af949092bc3295417230200000000000017a9149721b126f0432a31d3ef318cd8f2c7f375ab18a5872302000000000000160014d0929a49be169a16aa8333a20028f7bf0239df7623020000000000001976a914e564ae45b875b8f5ee95ceda7f5d008bbf76bb5588ac230200000000000017a91496799d921a74f417ad40e9ac0dfee6ce21b1000987230200000000000017a914779179aee640e5f01e9d21efad0a736d0123bdb88723020000000000001600146e4416646092d87274c35d3e6a8968ff14f4bf2d230200000000000017a914e287d41cfefdab09c04b321880f55ac215fd013487230200000000000017a914cab63089beca3e07ba56e5c82a258aa9bd3fcd8987230200000000000016001484b67c1d8c134890c681fdec8437f3d665f7ce8023020000000000001976a914cf3bef4339b7a6237ab427892e37d694ec4667cd88ac23020000000000001976a914450c0db3f4bf429d44d3f2d422a99cf1e69b918088ac23020000000000001976a9145dfff4b853a555665445ea19ff728dfd904ac49488ac230200000000000017a914ae527f54830f76309221c88fee50dfe4d24fa7fb87230200000000000016001441aef0c553260b7316412f74086eba43ac7a4caa230200000000000017a9147a854c40d41fa587772f9defa4ecf19a9e3367748723020000000000001976a91435cc46e14dc5f3211460bb789bb2ac41eeea324688ac230200000000000017a9142e9589fa3c9c5907842760a901a57e7809dd4a2b872302000000000000160014ef888f9ce63fe380601e757932a83718ab85c1d423020000000000001976a9143df4ed34906abdf143b07dd335ffd5ead8d7c5bd88ac230200000000000017a91401e760704153a07ef9872a58383cc4867f3aca648723020000000000001976a914d9bb3376e68d7a71ba16d5819937fcae887f022e88ac2302000000000000160014ede4c4c877dfaf0900e3f39d9d0818b67b7009be23020000000000001976a914a0f7653fc0a919026785b608092ef4885882787f88ac23020000000000001600149f767cf30454b93504c46507d760cfc1a61a97c123020000000000001976a91482fc44c2f09b998c7e1a024e3a8cc1c51fd0897988ac23020000000000001976a914158dc6f9a9c49d3d860d71446222ae3b96f6503d88ac230200000000000017a914849e066c2bef8ad4acc4c4ad442d8bae600c973a872302000000000000160014b209ba581834315d281109b546b6778b26cbd76523020000000000001976a91446d2a34026977167351b7b2506c15096bfb3f04788ac230200000000000017a91478ebb53671dd46fe65d328e96aa9d8563bd33a6f87230200000000000017a9146b4e664383556aaa23a78db6b4e48e7285bdc5dd87230200000000000017a914c19177ff03819605f23abaddb2a3c2e682478aad8723020000000000001600146c7345202b63d30342ce3d68b67e7fdf10b9cb462302000000000000160014d3f7c12706a78d7fda7d82e3b2afe1b51862ea76230200000000000017a9144ab5aff881ea295db96820eed7f596dc226f23b38723020000000000001976a914ffbfa1ceef46f7c69902a791b7ac5d2230759a4e88ac23020000000000001976a9144fddf6c4fb8f68d1ebc70f9bd2e64e13a395831788ac23020000000000001976a914494b0a4c166296d72668b12e7108713cf0e95e2088ac230200000000000017a91426bafc3e0e4fc749aa1a892df65792c99c39e8d787230200000000000017a914d3c7799869a7fffa6d05e00dae030b03ab33dafe8723020000000000001600148dd1d6f47cc6952bae3fa51ecf8a0e94173f84e423020000000000001600148dc498e2f169e60a7ca69dd9cdf76e31cb049ada23020000000000001976a91462d7a334399aec9a82703e96fc7416649ce1706b88ac2302000000000000160014a28c96aba55d1ebe17ab0f486f5765edd78e28ff23020000000000001976a91491db8f43e3cdb5dc7ac7d02949a4e5112ed9140888ac2302000000000000160014f25bbdda4adb4885b913a4f2e0057de99928b50a23020000000000001600143a05998c72db81740732489344baa79d7b00e0e823020000000000001976a91432f5d2ea71c526bd089cb2826985c9af4cf56b3488ac230200000000000017a914d85866646ebda63ae457ee2ea2a09f347d7e304487230200000000000017a91444442f51643a9d2f2bb12003ce7d5aee98cd13c88723020000000000001976a91419db3b54f38eb29127d87efcb0685e3137d7e00688ac23020000000000001976a9143c2d736da47a667d70b9ff4ddb6574baadbcb5e088ac23020000000000001976a9145859c43e087ff91905591e89496af9a17ddf6afa88ac230200000000000017a9141d7f80c7fb024b41fe6762d012033b35b1aba47687230200000000000017a91493ce5567957c3491235061374ef1ac67bafdb2db8723020000000000001976a914e3faed63a523db39c57ca6b6ad96f9e9e66558c788ac230200000000000017a914863c07e88df3039ca8e41f6e57a9988254f0419c8723020000000000001976a914f9376c267a4cba1b41423b5580bfe30e5cc48f9288ac230200000000000017a914f2f4ed419833d5169820b18bf7a4f944717ff47c8723020000000000001976a914fd530daf0fb34bdd0219ff6f713d56d7609be0e088ac230200000000000017a914d45fb0c36dcdce07afd8cf73be4a223b4b81a87c872302000000000000160014a2e03cec45dbdc93aac2a944dd8eb3251e24a832230200000000000017a914a36f746b5216df34e3d6c001b15bb23572403b87872302000000000000160014ae7ea0a8d256b54a6d68fe5cbd314434cf41543b23020000000000001976a9149d5a3a9d7fe224a40340a80d6cc26dd84b9e49f088ac23020000000000001976a914d8f3375e5f6c66890cad7d63ce037da843d2415188ac23020000000000001976a91457fca43fd4d3dbaa6d9e74c4f0ed68b8d306afe888ac23020000000000001976a914458ce5baf10d3005bbc9da92c27be37366b2bf5d88ac23020000000000001976a914e1b7b0fa25d5b38696fa8289127eeeaefadc8f8988ac230200000000000017a914b8a5913d1aeecc70eab3441fc831eea92f8b1f2187230200000000000017a914e062539a8343778cefe65870e0c758b8b6a1cd848723020000000000001976a914d7bdd4a7531e5e1b7e59b5150bb881b477b035d388ac230200000000000017a914b0788464f21866825c503fe191b99c6d4c347a628723020000000000001976a9140aa6da0abe353a65c153d017e864b1c5097fb92588ac23020000000000001976a914ddd1b12ade1bb18c0122719ac89752b254a06a1d88ac23020000000000001976a914fbcb96a8d1d70d3063c1b37027dd1370ec310be688ac23020000000000001976a91455350e526a1184630396ca927975bb998b7e04ba88ac230200000000000017a914af13bb785200c1872eb5546c56a6e3c74dc5b21f872302000000000000160014a9f9268f516a910c5a32fbfa754bd675f9fe7ed523020000000000001600141c6cf7c45c0919b8d08790a5e6f2a760a999a4cc230200000000000017a914f25b9ea827187ba264c0a179be76a6943824149a8723020000000000001976a914e98af4e43fa9e1b0e36ca8041278079a3a0883f588ac23020000000000001976a914ff2a0aa1de5bf4ecf19491245291cfd89a35df8488ac230200000000000017a914e26e760fc8496ce6fa0eb2a32760b450ca3fd92e872302000000000000160014f0879cbec5fdf033d1a3206ef3f1097454973d54230200000000000017a914c963915bbf458eb4a6d61e22dcf26e9779e433d187230200000000000017a9143d02f490fd0d3c8614dbeaffad154a07d70afc988723020000000000001976a9148c99cbba72a0b3f5d8b14da031033fa18ade94be88ac23020000000000001976a9149b6d5e7d4423ef5882bc614338f2c608c4555c6588ac23020000000000001976a914e4af7042584f30414ca51e5a4ccbba31bd2cc9bc88ac23020000000000001976a9144411e2f964ab916e4eefd3d53c81f11ca4f77eb788ac230200000000000017a914377aaaa31831b5c80a01d9c0672bd24f2476513e8723020000000000001976a914319023079e460558db34ebf69035dd25d2e71a5e88ac23020000000000001976a9142d2765b593545ae839692fb067646ec13fbc50b588ac23020000000000001976a914bcd5a5874d0752e27da88aad12b78f981cbfb7a488ac230200000000000017a91423fb6e4e86e99d26468514d5566b92a7f35ba07587230200000000000017a914eeac3a34cdcd9ff4c309dd3cb8631d0f23784ba48723020000000000001976a914dc20668b4ec3fce5c7c644edfb86b8f1b681980f88ac230200000000000017a91402f8b23b04094b81e637b9df3509d64fb6cc30f787230200000000000017a91400b20f68f708c81ee570020b906d0696f12c19c787230200000000000017a91422d35961b3e01872b02101ddbdc3a6aadfd9d5228723020000000000001976a914d93fe9eb224bc3e67e121a07c82978984ee73c2c88ac23020000000000001976a914fb8443f3be9b71b766646bde191f0fd031f7dc2788ac23020000000000001976a914114b1d9c0a6ae2f678949e3d3cb0c9bc75e8accc88ac230200000000000017a914224edcef45695f06688d414a2a0c86f41b53826e87230200000000000017a914ba85d6e1bc9ccfe144ce3a46c9c43baf905cdaa487230200000000000017a914a4239a672eec4674ebae84caaf16429eaf9c53008723020000000000001976a9143a3d5a2ef1c103dfc93664f3fba456b5c9b107e188ac23020000000000001976a914e68d4821ded42d6b71878d6ddd654faf8cf214e288ac23020000000000001976a914b99abf2b0d5cc653a40cce55af88318bf0e6071988ac23020000000000001976a914b4c2eacc2ddfd2c89ea5aa5fd4749b5e74b3b7dc88ac23020000000000001976a914454ca2a1e0fcfd75f50ad44b6f40c3250e59976e88ac23020000000000001976a91444a9d6273a8fb42966e19a708ab3c60946068b9d88ac23020000000000001600148a85563bd05cbc11dff50bd15195047be6ebe81c230200000000000016001410d6a10f70cae84349607017a2672df471a3bd4023020000000000001600143bb333182bcc902e2ef13681091f1cebf86e851c23020000000000001976a914b57013aebc7dde1cd4049d6c68a0cde27984a8c088ac230200000000000017a9143e257da258c88ca015e00e93a4d279ed8662136f872302000000000000160014f05e6a00a088dbbf80605943127dc3d74c719cab230200000000000017a9141e1513ccafe9c48a2d336066996cd03fb9bafa1087230200000000000017a914132bd5760b9c030ad9f0865c55336a6ea9d9631b8723020000000000001976a914d7eda7fa5262f2a620ee6a68353a40759025e85c88ac2302000000000000160014c85ab3e3feb9a17c9d754647744a00a5ca44bb5b23020000000000001976a9145ee7d8d516267c0a9d7bf9c0d3b065bceb48f8e988ac230200000000000017a914bdabc85c063b9505639944d5abec7a4051801b1e8723020000000000001976a914848c0fb744c34c294bb872c039f7b808b8b47d0b88ac230200000000000016001499b754524469d6ad0d02b6db53d197d866b4dfa623020000000000001976a9142f27df9390470738329eb9e65a2a1dfcde42ca9488ac23020000000000001976a914cf21f69d7e312aea192bd9e57721daf3d0a366cd88ac230200000000000017a91448e9f35671e79ecce10259f6e5839d800957ab6887230200000000000017a914f6c94bc3dd972025d1f3683b7cb52820c95bc9768723020000000000001976a914a42ba2bc745b7e4e0e72302019806e6831f0b2f588ac230200000000000017a914e6707453710971cef8be91e32e841bec294c028e87230200000000000017a9147d2522b44c72cda6b343d7d27666c9c9ec7ee0718723020000000000001976a914437612ebe04191ec2f1e38fca51875ba8cca5cb788ac23020000000000001976a914efd994588c4209e98cc272b82f925b0403b952ae88ac23020000000000001976a9147f026f6360e869d23a055ef59412f3fa706e061d88ac23020000000000001976a914669a807ff902b80c1447816a1cdea9d7198b747388ac230200000000000017a914e1d300eb2c9b18e74995f69a8b9e5d906eb2dab987230200000000000017a9144a9bb4d751a68ff69e386eaf846b2988a3d57a9e8723020000000000001600141bafbbfc72d46f958a7f29ead2890cbd01551e4a23020000000000001976a914a15b019177e57a7e30f778b7e1f60b166415db8188ac2302000000000000160014d159cfceab0450919e4a7d424dd322fdd136b486230200000000000017a914e5793fc0434b18b0487d95ddc5d5c524520b597d8723020000000000001976a91440780fba501b7bdfa5d0b2a9799ce52399993ed288ac23020000000000001976a914782686d03338f1c5e1694046636176d81f3e9e1888ac230200000000000017a9143415462039fa2b69f56d9a1672c3d075db6e6f248723020000000000001600147838b97c5a48b0de99e6305d32de4aad42a8ce80230200000000000017a9146986783e33115c90b60e8cb02a02ce54bc11e3478723020000000000001976a9149a9e35d3c0c9ea32830cd82a3acc72fedc3400b088ac230200000000000017a914725946687317874e800cae544e1d9f97a2f6682387230200000000000017a9148f11f28dc7e7b0b644a26574b83ed45881f6960987230200000000000017a914407efa1735aa1294aa4e75e4f0bd1aa3d135d81287230200000000000017a914f3370dc8873bd4c7a32d786318b5d5519944c1b587230200000000000017a914e3879d24370b39597fafc0ac342bf180328463c58723020000000000001600147c4f33b7702363c2ce15909b3858fec06ddde67a23020000000000001976a914a5a072c325e77f222e24c9251b1e14bcaed137d188ac23020000000000001976a9142da18b9be3f1604823d7db4a5dfaa5efbf7ff58388ac230200000000000017a914777f803f72c392a2c6a9eef4d40a170205be9fe287230200000000000017a9146918f281da7e641d0b90f511f35a9128ffc37e168723020000000000001976a91468f02d4626b8524923875ebaf3bcf4d6f68aab4a88ac23020000000000001976a9145e4db041915c4daba068c49c51ceae09c84f1cdb88ac23020000000000001976a914cf556ac3c916551048deeaa527989e1088608f5d88ac2302000000000000160014fe5f7fb2e28ba25b1c6df1469981682b9a320cff2302000000000000160014cbb3925133efb7b7ce69c864e785f237d75ec56f23020000000000001600143b6e0e2bcd9a18cfa060e80179ca7a4971e5fb0623020000000000001976a9142d9c0d48ba1d4a8928898189e308ae1f77d6ad7988ac23020000000000001600148a8c087ecb8df522af4839083be98220ce337a37230200000000000017a91479e7ebc22b278f2f0a5ca19b6442319c70ebda368723020000000000001976a9143e5c1134a31449b766f54c140bc7043595f6c92688ac23020000000000001976a914782dad903264b30baa201926d21abb43d2078a0288ac23020000000000001976a914b7bef448bb7b72400a8f63efee062f42ad82107688ac230200000000000017a91425a1163e59591345aa693f4721e9c9dd5440e6358723020000000000001976a91468b155bdb5d89fd28bb06b3489c2787bf887671c88ac23020000000000001976a9149030478aae3edac9b71306d26398d5fbdb04021f88ac230200000000000017a914482a6e63ee8700be61f93267b7440d30b341fa9d8723020000000000001976a914a8567c92f57ad92e2ec7d10238cbb77536fd415388ac23020000000000001976a9143101581e1ce201b5dda8d10ce565067706e4290e88ac23020000000000001976a9148757fa39b205dc19aee1431e4926a024cd29e79d88ac23020000000000001976a914233951587260464ec1c08eedd3f90f18b56f37e888ac230200000000000017a914bdf3e9d6e4993d2d1683d3b5c24cc265859c872e8723020000000000001976a91402dd9d2e86952bdc4999c7c34400407fda9b6e7488ac230200000000000017a91453250ade815844653339f8120af51fa1fab8a5708723020000000000001976a9144986b21668eec5e7892c75a75dbf1d740fe61bb188ac230200000000000017a91429ea8b11b1ed498474a01a306bf411a38657a53587230200000000000017a91492715a9a554c984c0f6b30660145912a2c7e7c708723020000000000001976a914bf527572bb5862c7e84ceea6bec5a4fafe46251c88ac23020000000000001600145bdd6829dc171596cebdcbf66023e900183c1c69230200000000000017a91487abf5151ae4270b7d71012712b162756bc38d888723020000000000001976a9140b822e0bef510fe018c4793aa1a61d2fd14933fa88ac23020000000000001976a914b3ba8762ff5a03945d0e591866aa80cab238875b88ac23020000000000001976a914bcda05a85decca0fbfc105f34dcc9d1ff6ce4c6f88ac23020000000000001976a914a26e333aaf75821ee99ffd135fb7d4cff33ba0fb88ac23020000000000001976a9143441292259c79eb9665e7bd9db25bfccc6190eb788ac2302000000000000160014a0d2c014796aec0497e4cffc2e34c7fcd86a7af523020000000000001976a914b5a55bc4872539ea89aa7e7118f1ea065a11945f88ac230200000000000016001464c7e81fd7bf1dff3089e25122f82eacf3232d1b230200000000000017a9149c4974bdcda2e3c5cf259585cd15a36b250b58d18723020000000000001976a9142bda83492a48e41018b42b20b9385f695991b7d788ac23020000000000001976a9147001b5d4c5fed4b4f5fd7572e53597798150a1a188ac230200000000000017a914297ecaa88e0356bf479d37b3c99e26904ee8a8b687230200000000000017a914eb631675bd26081e32d23d53c507b5cf1f1f111187230200000000000017a91403d30a45d7831d367e1832df55dd6035d6ebac7887230200000000000017a914d3117b38fe904fd46bdf27571c4df8b1827aa69c8723020000000000001976a914db2acd0a4bfb14c151b24b6a1f840fd3e48aae4188ac23020000000000001976a9141a97f348b05c18cdbb1e224d695b03841dc37a8788ac23020000000000001976a9141066f94732935460f13496a3a3d4e18c16a896f988ac23020000000000001976a91415d9c7272ef24727d60d560506d6cadafe4f3e1a88ac230200000000000017a91490f0e5c26aa667b451a5d0c909391b354d6d090687230200000000000017a9149640d5b97acece03ec72b76f8b8a9892f20f4bbc872302000000000000160014acc299c860fd9bb7134a8fee46a2b499f84c47c523020000000000001976a914f175ab5ec14999c33857eb4d88953802de009a2f88ac23020000000000001976a9144f9682eaa9b671bc2a6736583be9e2e6ad7d96f288ac2302000000000000160014639c6ea53206fdcda5af57ce6922867add84e20f230200000000000017a914c15f6a343310cb953df9f14e3dd441b8fec5723587230200000000000017a9140843a49814635ea03f6ed3eb7b394ed1f9e3997a8723020000000000001600144bbeddb7d8761bf6b9f2e4c00ecbbb9033b76a8b23020000000000001976a91459fb930127c59313401725bedf159e8001b2d0ab88ac23020000000000001976a9142b08b8c36d1d0ca1fe951676d2e8deecc10cd67288ac23020000000000001976a9141cceaf463bb18ed44a5788fff0351ca7a105eccc88ac230200000000000016001492ce08bf9f8b4f65dfe10040b04599d7af999f69230200000000000016001445d6979c266f53ea9bdd60335f43cdf8ec3d46f223020000000000001976a9145e66657c77ec79fb9ba2a4b6662e81ada08470d188ac23020000000000001976a914edb3e35c36330b40517badf19b8667d8d8a91fcf88ac2302000000000000160014a0d0285c9bf5c614e2eb8694459e734c405f61ad2302000000000000160014eb6796013e3f322b4409c83a5ce6933b3bed2a6623020000000000001976a914a37da29fb9cc3032213440dfeef4dbfd5127d8c588ac23020000000000001976a914bea7d433934b2234d5e02ab12e2609b5f1547f3888ac23020000000000001976a914bc34b4978ce51bcab9e2bea4b4b2d3e7aaeffc4788ac230200000000000016001474287528d9d261390b2e4612cdc27f82b1daf9282302000000000000160014e68846d818f5f2367dcbbdeed01ae7e62ed881dd230200000000000017a9143aa4e97541e63d6fb615230db3b9790467d9404e8723020000000000001976a914d161fd65bc8950ae8e758d7caf4bb01f7589ed7a88ac230200000000000017a914865411c372bd22308ae7e49ac9a73ddf4524ac088723020000000000001976a914733eb148bef61d63d544f9e1f134bc28c713622388ac230200000000000017a914aae06c64efa23a13dfeb1ecaed7c5442304e59f78723020000000000001976a914c4b39d67f1063f2b40d93ac7a3c32aeff0d0673988ac230200000000000017a914b4aacc86b0d171d0daeed1e973bfd84efffbd94787230200000000000017a914bca4fca5751781fe4b217b495369494b0970532987230200000000000017a9147c31eb5516ca6be732d4d665993234453e555b908723020000000000001976a91423a5f2901e4291616689c645b86c3f2834b035de88ac23020000000000001976a9144cdf897e8471c4b26128a7586dd1712f5858363288ac23020000000000001976a9148b9f659dc9063387dea0b4b2125caffcb19f52c988ac230200000000000017a914de64339689cffd9954e82650bdc7489899c1c77c8723020000000000001976a9142c3034477226c953c7bfdf37a57b5ef72d84577388ac23020000000000001976a9141b980ccb350e958513cac7031c2f8d037bd3d33d88ac23020000000000001976a914ca470e9456e7fcfd3282b8e5547db71067584c2388ac230200000000000017a9147493cecc87c3e1512aa502791cadc858527cfd608723020000000000001976a9148b9d038965ef40cdf6b2179d24a737f8f0fc64d488ac230200000000000017a9140904f1a65a1671e9718224c90bcdd4d981ed13e687230200000000000017a914a0d0cb1362e3367331f413d4e95dda33bf59ffe287230200000000000017a914b541f609756fb144f5d87b87a515563c5185ed4c87230200000000000016001476de53781da21c28b854714030f60655c01936da23020000000000001976a914553360efb4f1337a304d833c006f65625580e9d688ac230200000000000016001424eb2b58976164272055c5d8e33e134b63ff3af423020000000000001976a9147796681441c9f2eb826398a10afce0240a499cdd88ac230200000000000017a914ed1a54faf310f0fa3fe041219006ededc3e2b090872302000000000000160014c4976d206da3995694b1743d621db3aff3a3f491230200000000000017a9143da99fcef5e7da440530ee7bc0a29428d60d08dd87230200000000000017a9146b2b5a9544bbc70f5255653167c83d589dd6983b87230200000000000017a914b57dad25d82428ddf3d702f8866fa268955a508a8723020000000000001976a914bba81549f149741e79ef1719150b0d52a033538388ac230200000000000017a914b7e6eeddb7a17c62137f758859854124eccb2d2e87230200000000000017a914d4913822e89c430ce31449c024bddb5b6ba721068723020000000000001976a914d26bb7c6fd5d39ab76c32abb956f65333659662a88ac23020000000000001976a914033ebd5d7114934ec871224ee4a9f3c03405772188ac230200000000000017a91474c7b5d931b78c817d32e63f4f660f455a186c528723020000000000001600141ccbee5d78e1ceadd1747fa1f9e2076af14cf3e723020000000000001976a91479cdb818be5c72840a57c43db7a68f897ed2d5ec88ac23020000000000001600149807d8d45c60fd36c5a5f89da84be86061fd8037230200000000000017a9148d4e2d8bb92aaff70aa6755163515e5ccc6882b987230200000000000017a914dda395967c5998540994f26536caf5ff778924f48723020000000000001976a9148fc1ff6e256e7560e3a8f59f92b90d8cbb33031f88ac230200000000000017a914b9b8a32c2d9a660efec10adee18a447422a93f788723020000000000001976a91490f7fec9b9d1f8e00a03536a9efe8e7327cf48e288ac230200000000000017a9141cab5f8200e1a801a70121fc4bec08a7faaed2b987230200000000000017a914198d0d8e324460dbde2eee90279708ddee1871f5872302000000000000160014a98c87a6a076b86a289e504873d6edb005e73163230200000000000017a9143ab083e70d63ab931417b7257995c336847a5ef787230200000000000016001428a5f68c4e39b007619fd0b7b45fff5608c3f13623020000000000001976a914e4200fab7e35453f5d98fb65467e9121fb1490d888ac230200000000000017a91484ed2020d76a13e7a030073060ae412f9807a93287230200000000000016001402cd78d3ec050ed4f06e73aa392ae5cf38f26b95230200000000000017a914eabfcd9efe02602e151bc2b991b9eaf8f859008887230200000000000017a9148b6065dab8302532a12aafa0b830ab2bdb42a71487230200000000000017a91432b7183734429b0aa45ab965d96959d128d8f59e872302000000000000160014a0e9c227e3ca350209011eb658196a678cfdbab1115b7e0600000000160014718eb14c8b2a915f38eb48827d36dc19efd68c650247304402204a0633b56f90119ed2b3bc3284eb5ea45ae018659fc8e8b0ea3e2a369692575c02204b48d99955ecc928823c0c4f32ad3ab8b5a90b07e4bc7a9a2efef99e593a46b20121022ee8e970385fc312ae22d41e89a34e567cfffd3c5ff072853616cea7b122712a72760a000000005bfffffffd006b0000fda714fd2f72dba7006dd57264342f5c0200000000010139b972a98c6e5a707b4eb93bf7987c2ea92fc507be28093115e31eb9b15169d15f02000000fdfffffffd6e0123020000000000001976a91403b7892656a4c3df81b2f3e974f8e5ed2dc78dee88ac23020000000000001976a914075b7dfca1465daa6f51b8497af83c10042ef39988ac23020000000000001976a91408d2de7257e4f777653b939c6bcb7401aeabf1ff88ac23020000000000001976a91404d9d15e67e6f20551992e03039711e59281f72888ac23020000000000001976a91406f61b94f0e562e41e7137a8b0aa78db6102925788ac23020000000000001976a91409cc4cb806f792fe235c1b8149c0267b12067c9788ac23020000000000001976a9140a9598557e4075d6543a51a33a6a84d6945b6a8e88ac23020000000000001600149fb2f9537a8fd38df559346405be2baa3c72c90d230200000000000017a914083dc9041c5af68d3a84b5649f38300ba8ce2bf987230200000000000017a914166278d881b3fe8d1fe8fcc71a94b1381f65c6e387230200000000000017a9144947e8225918b63e0a1146715c1d31a9db29d2658723020000000000001976a91438c04525a19adcbe2ee618c371b819a1842aec6788ac23020000000000001976a9146261111744bcb237fc16475b58966e05e49ee91488ac2302000000000000160014f8f416e8650cf65853d9b2ccb68f291736ce9f16230200000000000017a914cafecd5bd4e863243325220c2ae77acd4e6a483a87230200000000000016001415bda5f82091653d281bed4baf448c3e836894fa230200000000000017a914d798abd4c7b615cbbda823bc1ac90aa95a6c5d2087230200000000000017a914a61ad56f619d34cb27e8e6084e61d0c781b57043872302000000000000160014c390a98f9bd670f7fffd05ad0c49030ea3558e0d230200000000000017a914ab7cd63a2467544015f1b836bc7ee825014ed1f68723020000000000001600140e28c69bda7fc84d7596ac5ab984108eec189039230200000000000017a914d686e9e2933770f2f0505940bd1b71961278436e87230200000000000017a914d11e7c96aa252713b3e952f0aa6cb5dab58454888723020000000000001976a914ab8df34991a3904bfc7af8695d25e878272a80da88ac230200000000000017a914f90558a334d9e94ed55f2758d45d77aa2a12a4b387230200000000000017a914c576afd0b25b74b0536ad748d5c0caf4dc02aa728723020000000000001976a9147f162d1676d136c43103eb829ea4fc0144356ebf88ac230200000000000017a914af9769bb90961b4cceb63b6aa658c6b08b6c72368723020000000000001976a914a2d2ff77f0532b78cde36b3342cf8d39ed25310b88ac23020000000000001976a9147b00ba7bb0706d0d3513c25f0e176ec10aa8357a88ac23020000000000001600148e5d7d761aa81e21d44794ac18f327043bb51c29230200000000000017a914dd3d5c36925f9da35a1e41cc767662225907d35687230200000000000017a91492948622bd64e5ab5cc3131f46fd6e020ec9cd778723020000000000001976a91404bc122a97b3d767c74d9903ca0fa9ae759a4f7788ac2302000000000000160014800a2fa1c5ce8f76066337945a30bf20676d3e74230200000000000017a91495422ffb24b0b15582c0d6dd85ddd512ae932a1e87230200000000000017a9149e9fac02c01735cde61fa38599f6277c0a9d50e38723020000000000001976a91478729f374b26f142b9fd0aa95c18ec177aa5718a88ac23020000000000001976a914117abda60c33332922cbc775ba1736c3962e8fc788ac23020000000000001976a91486ee82444dbef6b1a1b1a80178aec6e50a02666188ac230200000000000017a9144c28496aa3e360638395ae867c52a376d9b676028723020000000000001976a91452791bea99155d14fc7aa2be33432e8d5a6e7acc88ac230200000000000017a914a038e6d23699603fa481830d233aadc9ba1a50a587230200000000000017a914999e70797506b99f9fe7425f4b04223968ff54518723020000000000001976a91452b0bf8ad6ec03bfa28f946025a9ec118c9438d688ac230200000000000017a914ceb97a9a76bddc2e3c291bb57ccf08bd6ef26b3387230200000000000017a914059e93240e9ad13a0cefef0bd0da7af09c63efa787230200000000000017a914c5b4340a8d91046723b926fd070eddd0e3aea8798723020000000000001976a914d9081422d11330156348eed7188296d7f86a1ba188ac230200000000000017a914c4de313f3a10e3cd00e63a6192ec77d97b393f648723020000000000001976a914152924f27f61c0e2d74b6789eba026320e5157c588ac230200000000000017a91467835200a0c01b1c7b6985daa6d6e20bc42a83d187230200000000000017a9148ad3fad7a520fd92150e2cd71e5fc94cfc58e4448723020000000000001976a91402826240dc63aaa77ab740b589b71dccd328e81c88ac23020000000000001976a9145fd10d16dee6404b86867ba316d9fc4bf120f36388ac23020000000000001976a914a068282adf132d1f09394d1bc9ce6fb6d0a9fcec88ac23020000000000001976a914fd5801e308fad7a10f8aa35c3631bd9f1a29ca2a88ac23020000000000001976a91441d2321f1f48475795bb63e9ba92253558eafd3488ac230200000000000016001440d085fc97c7f10d8e8941df91cfdb14c8f31773230200000000000017a914f3b478c591c1998e204c4139cf7acaf2775f257787230200000000000017a914a42aebef7e9394c534ad3921017236fd831b375287230200000000000017a91405ebff2bb06018f1dcbabdbdab3ffd13f70a0a218723020000000000001976a9147426386edb015d6ab9f7a03ea9d9fec2f88087f988ac230200000000000017a914ffcdc453f7c2233cddc6f1a3c5dc9f1dd457c66b8723020000000000001976a91437656021883983ddf2a2947b923671b4f407cbcf88ac2302000000000000160014b6f82d7f07c3f5be91fed19f76062581612e9c72230200000000000016001407494f429133c6d580ed901ca22b793a4b6f031a230200000000000017a914503e431c5cddfcbcba6b6b7a58b8c0eb4bb9372e8723020000000000001976a914ee30800a1ae846689dcb62d10d73bdd53b12263088ac23020000000000001976a9146065c5d7d9b0f8dcdad5da95ff8b2d70be7cf40088ac2302000000000000160014f402151c8388fa91172f1d0c85b25b0e680692e823020000000000001976a914c6a0c630aff95f37c99681a8caa9ce414baf3b2488ac230200000000000017a914703e36245b8e117b6126624bdc06fc8af0786ced87230200000000000017a9142e84d2d9ff58e5158da8c4b73e607e458e5bcee68723020000000000001976a91439b03548d49ea1fffd7491be87c25534d92b65d688ac23020000000000001976a914da7780d7ec425b2164f4c7851c1947f799a317c888ac230200000000000017a914627a2a7a29265badc12e612622957ec7a60465c38723020000000000001600148ca512ac6642963d71b3e17af949092bc3295417230200000000000017a9149721b126f0432a31d3ef318cd8f2c7f375ab18a5872302000000000000160014d0929a49be169a16aa8333a20028f7bf0239df7623020000000000001976a914e564ae45b875b8f5ee95ceda7f5d008bbf76bb5588ac230200000000000017a91496799d921a74f417ad40e9ac0dfee6ce21b1000987230200000000000017a914779179aee640e5f01e9d21efad0a736d0123bdb88723020000000000001600146e4416646092d87274c35d3e6a8968ff14f4bf2d230200000000000017a914e287d41cfefdab09c04b321880f55ac215fd013487230200000000000017a914cab63089beca3e07ba56e5c82a258aa9bd3fcd8987230200000000000016001484b67c1d8c134890c681fdec8437f3d665f7ce8023020000000000001976a914cf3bef4339b7a6237ab427892e37d694ec4667cd88ac23020000000000001976a914450c0db3f4bf429d44d3f2d422a99cf1e69b918088ac23020000000000001976a9145dfff4b853a555665445ea19ff728dfd904ac49488ac230200000000000017a914ae527f54830f76309221c88fee50dfe4d24fa7fb87230200000000000016001441aef0c553260b7316412f74086eba43ac7a4caa230200000000000017a9147a854c40d41fa587772f9defa4ecf19a9e3367748723020000000000001976a91435cc46e14dc5f3211460bb789bb2ac41eeea324688ac230200000000000017a9142e9589fa3c9c5907842760a901a57e7809dd4a2b872302000000000000160014ef888f9ce63fe380601e757932a83718ab85c1d423020000000000001976a9143df4ed34906abdf143b07dd335ffd5ead8d7c5bd88ac230200000000000017a91401e760704153a07ef9872a58383cc4867f3aca648723020000000000001976a914d9bb3376e68d7a71ba16d5819937fcae887f022e88ac2302000000000000160014ede4c4c877dfaf0900e3f39d9d0818b67b7009be23020000000000001976a914a0f7653fc0a919026785b608092ef4885882787f88ac23020000000000001600149f767cf30454b93504c46507d760cfc1a61a97c123020000000000001976a91482fc44c2f09b998c7e1a024e3a8cc1c51fd0897988ac23020000000000001976a914158dc6f9a9c49d3d860d71446222ae3b96f6503d88ac230200000000000017a914849e066c2bef8ad4acc4c4ad442d8bae600c973a872302000000000000160014b209ba581834315d281109b546b6778b26cbd76523020000000000001976a91446d2a34026977167351b7b2506c15096bfb3f04788ac230200000000000017a91478ebb53671dd46fe65d328e96aa9d8563bd33a6f87230200000000000017a9146b4e664383556aaa23a78db6b4e48e7285bdc5dd87230200000000000017a914c19177ff03819605f23abaddb2a3c2e682478aad8723020000000000001600146c7345202b63d30342ce3d68b67e7fdf10b9cb462302000000000000160014d3f7c12706a78d7fda7d82e3b2afe1b51862ea76230200000000000017a9144ab5aff881ea295db96820eed7f596dc226f23b38723020000000000001976a914ffbfa1ceef46f7c69902a791b7ac5d2230759a4e88ac23020000000000001976a9144fddf6c4fb8f68d1ebc70f9bd2e64e13a395831788ac23020000000000001976a914494b0a4c166296d72668b12e7108713cf0e95e2088ac230200000000000017a91426bafc3e0e4fc749aa1a892df65792c99c39e8d787230200000000000017a914d3c7799869a7fffa6d05e00dae030b03ab33dafe8723020000000000001600148dd1d6f47cc6952bae3fa51ecf8a0e94173f84e423020000000000001600148dc498e2f169e60a7ca69dd9cdf76e31cb049ada23020000000000001976a91462d7a334399aec9a82703e96fc7416649ce1706b88ac2302000000000000160014a28c96aba55d1ebe17ab0f486f5765edd78e28ff23020000000000001976a91491db8f43e3cdb5dc7ac7d02949a4e5112ed9140888ac2302000000000000160014f25bbdda4adb4885b913a4f2e0057de99928b50a23020000000000001600143a05998c72db81740732489344baa79d7b00e0e823020000000000001976a91432f5d2ea71c526bd089cb2826985c9af4cf56b3488ac230200000000000017a914d85866646ebda63ae457ee2ea2a09f347d7e304487230200000000000017a91444442f51643a9d2f2bb12003ce7d5aee98cd13c88723020000000000001976a91419db3b54f38eb29127d87efcb0685e3137d7e00688ac23020000000000001976a9143c2d736da47a667d70b9ff4ddb6574baadbcb5e088ac23020000000000001976a9145859c43e087ff91905591e89496af9a17ddf6afa88ac230200000000000017a9141d7f80c7fb024b41fe6762d012033b35b1aba47687230200000000000017a91493ce5567957c3491235061374ef1ac67bafdb2db8723020000000000001976a914e3faed63a523db39c57ca6b6ad96f9e9e66558c788ac230200000000000017a914863c07e88df3039ca8e41f6e57a9988254f0419c8723020000000000001976a914f9376c267a4cba1b41423b5580bfe30e5cc48f9288ac230200000000000017a914f2f4ed419833d5169820b18bf7a4f944717ff47c8723020000000000001976a914fd530daf0fb34bdd0219ff6f713d56d7609be0e088ac230200000000000017a914d45fb0c36dcdce07afd8cf73be4a223b4b81a87c872302000000000000160014a2e03cec45dbdc93aac2a944dd8eb3251e24a832230200000000000017a914a36f746b5216df34e3d6c001b15bb23572403b87872302000000000000160014ae7ea0a8d256b54a6d68fe5cbd314434cf41543b23020000000000001976a9149d5a3a9d7fe224a40340a80d6cc26dd84b9e49f088ac23020000000000001976a914d8f3375e5f6c66890cad7d63ce037da843d2415188ac23020000000000001976a91457fca43fd4d3dbaa6d9e74c4f0ed68b8d306afe888ac23020000000000001976a914458ce5baf10d3005bbc9da92c27be37366b2bf5d88ac23020000000000001976a914e1b7b0fa25d5b38696fa8289127eeeaefadc8f8988ac230200000000000017a914b8a5913d1aeecc70eab3441fc831eea92f8b1f2187230200000000000017a914e062539a8343778cefe65870e0c758b8b6a1cd848723020000000000001976a914d7bdd4a7531e5e1b7e59b5150bb881b477b035d388ac230200000000000017a914b0788464f21866825c503fe191b99c6d4c347a628723020000000000001976a9140aa6da0abe353a65c153d017e864b1c5097fb92588ac23020000000000001976a914ddd1b12ade1bb18c0122719ac89752b254a06a1d88ac23020000000000001976a914fbcb96a8d1d70d3063c1b37027dd1370ec310be688ac23020000000000001976a91455350e526a1184630396ca927975bb998b7e04ba88ac230200000000000017a914af13bb785200c1872eb5546c56a6e3c74dc5b21f872302000000000000160014a9f9268f516a910c5a32fbfa754bd675f9fe7ed523020000000000001600141c6cf7c45c0919b8d08790a5e6f2a760a999a4cc230200000000000017a914f25b9ea827187ba264c0a179be76a6943824149a8723020000000000001976a914e98af4e43fa9e1b0e36ca8041278079a3a0883f588ac23020000000000001976a914ff2a0aa1de5bf4ecf19491245291cfd89a35df8488ac230200000000000017a914e26e760fc8496ce6fa0eb2a32760b450ca3fd92e872302000000000000160014f0879cbec5fdf033d1a3206ef3f1097454973d54230200000000000017a914c963915bbf458eb4a6d61e22dcf26e9779e433d187230200000000000017a9143d02f490fd0d3c8614dbeaffad154a07d70afc988723020000000000001976a9148c99cbba72a0b3f5d8b14da031033fa18ade94be88ac23020000000000001976a9149b6d5e7d4423ef5882bc614338f2c608c4555c6588ac23020000000000001976a914e4af7042584f30414ca51e5a4ccbba31bd2cc9bc88ac23020000000000001976a9144411e2f964ab916e4eefd3d53c81f11ca4f77eb788ac230200000000000017a914377aaaa31831b5c80a01d9c0672bd24f2476513e8723020000000000001976a914319023079e460558db34ebf69035dd25d2e71a5e88ac23020000000000001976a9142d2765b593545ae839692fb067646ec13fbc50b588ac23020000000000001976a914bcd5a5874d0752e27da88aad12b78f981cbfb7a488ac230200000000000017a91423fb6e4e86e99d26468514d5566b92a7f35ba07587230200000000000017a914eeac3a34cdcd9ff4c309dd3cb8631d0f23784ba48723020000000000001976a914dc20668b4ec3fce5c7c644edfb86b8f1b681980f88ac230200000000000017a91402f8b23b04094b81e637b9df3509d64fb6cc30f787230200000000000017a91400b20f68f708c81ee570020b906d0696f12c19c787230200000000000017a91422d35961b3e01872b02101ddbdc3a6aadfd9d5228723020000000000001976a914d93fe9eb224bc3e67e121a07c82978984ee73c2c88ac23020000000000001976a914fb8443f3be9b71b766646bde191f0fd031f7dc2788ac23020000000000001976a914114b1d9c0a6ae2f678949e3d3cb0c9bc75e8accc88ac230200000000000017a914224edcef45695f06688d414a2a0c86f41b53826e87230200000000000017a914ba85d6e1bc9ccfe144ce3a46c9c43baf905cdaa487230200000000000017a914a4239a672eec4674ebae84caaf16429eaf9c53008723020000000000001976a9143a3d5a2ef1c103dfc93664f3fba456b5c9b107e188ac23020000000000001976a914e68d4821ded42d6b71878d6ddd654faf8cf214e288ac23020000000000001976a914b99abf2b0d5cc653a40cce55af88318bf0e6071988ac23020000000000001976a914b4c2eacc2ddfd2c89ea5aa5fd4749b5e74b3b7dc88ac23020000000000001976a914454ca2a1e0fcfd75f50ad44b6f40c3250e59976e88ac23020000000000001976a91444a9d6273a8fb42966e19a708ab3c60946068b9d88ac23020000000000001600148a85563bd05cbc11dff50bd15195047be6ebe81c230200000000000016001410d6a10f70cae84349607017a2672df471a3bd4023020000000000001600143bb333182bcc902e2ef13681091f1cebf86e851c23020000000000001976a914b57013aebc7dde1cd4049d6c68a0cde27984a8c088ac230200000000000017a9143e257da258c88ca015e00e93a4d279ed8662136f872302000000000000160014f05e6a00a088dbbf80605943127dc3d74c719cab230200000000000017a9141e1513ccafe9c48a2d336066996cd03fb9bafa1087230200000000000017a914132bd5760b9c030ad9f0865c55336a6ea9d9631b8723020000000000001976a914d7eda7fa5262f2a620ee6a68353a40759025e85c88ac2302000000000000160014c85ab3e3feb9a17c9d754647744a00a5ca44bb5b23020000000000001976a9145ee7d8d516267c0a9d7bf9c0d3b065bceb48f8e988ac230200000000000017a914bdabc85c063b9505639944d5abec7a4051801b1e8723020000000000001976a914848c0fb744c34c294bb872c039f7b808b8b47d0b88ac230200000000000016001499b754524469d6ad0d02b6db53d197d866b4dfa623020000000000001976a9142f27df9390470738329eb9e65a2a1dfcde42ca9488ac23020000000000001976a914cf21f69d7e312aea192bd9e57721daf3d0a366cd88ac230200000000000017a91448e9f35671e79ecce10259f6e5839d800957ab6887230200000000000017a914f6c94bc3dd972025d1f3683b7cb52820c95bc9768723020000000000001976a914a42ba2bc745b7e4e0e72302019806e6831f0b2f588ac230200000000000017a914e6707453710971cef8be91e32e841bec294c028e87230200000000000017a9147d2522b44c72cda6b343d7d27666c9c9ec7ee0718723020000000000001976a914437612ebe04191ec2f1e38fca51875ba8cca5cb788ac23020000000000001976a914efd994588c4209e98cc272b82f925b0403b952ae88ac23020000000000001976a9147f026f6360e869d23a055ef59412f3fa706e061d88ac23020000000000001976a914669a807ff902b80c1447816a1cdea9d7198b747388ac230200000000000017a914e1d300eb2c9b18e74995f69a8b9e5d906eb2dab987230200000000000017a9144a9bb4d751a68ff69e386eaf846b2988a3d57a9e8723020000000000001600141bafbbfc72d46f958a7f29ead2890cbd01551e4a23020000000000001976a914a15b019177e57a7e30f778b7e1f60b166415db8188ac2302000000000000160014d159cfceab0450919e4a7d424dd322fdd136b486230200000000000017a914e5793fc0434b18b0487d95ddc5d5c524520b597d8723020000000000001976a91440780fba501b7bdfa5d0b2a9799ce52399993ed288ac23020000000000001976a914782686d03338f1c5e1694046636176d81f3e9e1888ac230200000000000017a9143415462039fa2b69f56d9a1672c3d075db6e6f248723020000000000001600147838b97c5a48b0de99e6305d32de4aad42a8ce80230200000000000017a9146986783e33115c90b60e8cb02a02ce54bc11e3478723020000000000001976a9149a9e35d3c0c9ea32830cd82a3acc72fedc3400b088ac230200000000000017a914725946687317874e800cae544e1d9f97a2f6682387230200000000000017a9148f11f28dc7e7b0b644a26574b83ed45881f6960987230200000000000017a914407efa1735aa1294aa4e75e4f0bd1aa3d135d81287230200000000000017a914f3370dc8873bd4c7a32d786318b5d5519944c1b587230200000000000017a914e3879d24370b39597fafc0ac342bf180328463c58723020000000000001600147c4f33b7702363c2ce15909b3858fec06ddde67a23020000000000001976a914a5a072c325e77f222e24c9251b1e14bcaed137d188ac23020000000000001976a9142da18b9be3f1604823d7db4a5dfaa5efbf7ff58388ac230200000000000017a914777f803f72c392a2c6a9eef4d40a170205be9fe287230200000000000017a9146918f281da7e641d0b90f511f35a9128ffc37e168723020000000000001976a91468f02d4626b8524923875ebaf3bcf4d6f68aab4a88ac23020000000000001976a9145e4db041915c4daba068c49c51ceae09c84f1cdb88ac23020000000000001976a914cf556ac3c916551048deeaa527989e1088608f5d88ac2302000000000000160014fe5f7fb2e28ba25b1c6df1469981682b9a320cff2302000000000000160014cbb3925133efb7b7ce69c864e785f237d75ec56f23020000000000001600143b6e0e2bcd9a18cfa060e80179ca7a4971e5fb0623020000000000001976a9142d9c0d48ba1d4a8928898189e308ae1f77d6ad7988ac23020000000000001600148a8c087ecb8df522af4839083be98220ce337a37230200000000000017a91479e7ebc22b278f2f0a5ca19b6442319c70ebda368723020000000000001976a9143e5c1134a31449b766f54c140bc7043595f6c92688ac23020000000000001976a914782dad903264b30baa201926d21abb43d2078a0288ac23020000000000001976a914b7bef448bb7b72400a8f63efee062f42ad82107688ac230200000000000017a91425a1163e59591345aa693f4721e9c9dd5440e6358723020000000000001976a91468b155bdb5d89fd28bb06b3489c2787bf887671c88ac23020000000000001976a9149030478aae3edac9b71306d26398d5fbdb04021f88ac230200000000000017a914482a6e63ee8700be61f93267b7440d30b341fa9d8723020000000000001976a914a8567c92f57ad92e2ec7d10238cbb77536fd415388ac23020000000000001976a9143101581e1ce201b5dda8d10ce565067706e4290e88ac23020000000000001976a9148757fa39b205dc19aee1431e4926a024cd29e79d88ac23020000000000001976a914233951587260464ec1c08eedd3f90f18b56f37e888ac230200000000000017a914bdf3e9d6e4993d2d1683d3b5c24cc265859c872e8723020000000000001976a91402dd9d2e86952bdc4999c7c34400407fda9b6e7488ac230200000000000017a91453250ade815844653339f8120af51fa1fab8a5708723020000000000001976a9144986b21668eec5e7892c75a75dbf1d740fe61bb188ac230200000000000017a91429ea8b11b1ed498474a01a306bf411a38657a53587230200000000000017a91492715a9a554c984c0f6b30660145912a2c7e7c708723020000000000001976a914bf527572bb5862c7e84ceea6bec5a4fafe46251c88ac23020000000000001600145bdd6829dc171596cebdcbf66023e900183c1c69230200000000000017a91487abf5151ae4270b7d71012712b162756bc38d888723020000000000001976a9140b822e0bef510fe018c4793aa1a61d2fd14933fa88ac23020000000000001976a914b3ba8762ff5a03945d0e591866aa80cab238875b88ac23020000000000001976a914bcda05a85decca0fbfc105f34dcc9d1ff6ce4c6f88ac23020000000000001976a914a26e333aaf75821ee99ffd135fb7d4cff33ba0fb88ac23020000000000001976a9143441292259c79eb9665e7bd9db25bfccc6190eb788ac2302000000000000160014a0d2c014796aec0497e4cffc2e34c7fcd86a7af523020000000000001976a914b5a55bc4872539ea89aa7e7118f1ea065a11945f88ac230200000000000016001464c7e81fd7bf1dff3089e25122f82eacf3232d1b230200000000000017a9149c4974bdcda2e3c5cf259585cd15a36b250b58d18723020000000000001976a9142bda83492a48e41018b42b20b9385f695991b7d788ac23020000000000001976a9147001b5d4c5fed4b4f5fd7572e53597798150a1a188ac230200000000000017a914297ecaa88e0356bf479d37b3c99e26904ee8a8b687230200000000000017a914eb631675bd26081e32d23d53c507b5cf1f1f111187230200000000000017a91403d30a45d7831d367e1832df55dd6035d6ebac7887230200000000000017a914d3117b38fe904fd46bdf27571c4df8b1827aa69c8723020000000000001976a914db2acd0a4bfb14c151b24b6a1f840fd3e48aae4188ac23020000000000001976a9141a97f348b05c18cdbb1e224d695b03841dc37a8788ac23020000000000001976a9141066f94732935460f13496a3a3d4e18c16a896f988ac23020000000000001976a91415d9c7272ef24727d60d560506d6cadafe4f3e1a88ac230200000000000017a91490f0e5c26aa667b451a5d0c909391b354d6d090687230200000000000017a9149640d5b97acece03ec72b76f8b8a9892f20f4bbc872302000000000000160014acc299c860fd9bb7134a8fee46a2b499f84c47c523020000000000001976a914f175ab5ec14999c33857eb4d88953802de009a2f88ac23020000000000001976a9144f9682eaa9b671bc2a6736583be9e2e6ad7d96f288ac2302000000000000160014639c6ea53206fdcda5af57ce6922867add84e20f230200000000000017a914c15f6a343310cb953df9f14e3dd441b8fec5723587230200000000000017a9140843a49814635ea03f6ed3eb7b394ed1f9e3997a8723020000000000001600144bbeddb7d8761bf6b9f2e4c00ecbbb9033b76a8b23020000000000001976a91459fb930127c59313401725bedf159e8001b2d0ab88ac23020000000000001976a9142b08b8c36d1d0ca1fe951676d2e8deecc10cd67288ac23020000000000001976a9141cceaf463bb18ed44a5788fff0351ca7a105eccc88ac230200000000000016001492ce08bf9f8b4f65dfe10040b04599d7af999f69230200000000000016001445d6979c266f53ea9bdd60335f43cdf8ec3d46f223020000000000001976a9145e66657c77ec79fb9ba2a4b6662e81ada08470d188ac23020000000000001976a914edb3e35c36330b40517badf19b8667d8d8a91fcf88ac2302000000000000160014a0d0285c9bf5c614e2eb8694459e734c405f61ad2302000000000000160014eb6796013e3f322b4409c83a5ce6933b3bed2a6623020000000000001976a914a37da29fb9cc3032213440dfeef4dbfd5127d8c588ac23020000000000001976a914bea7d433934b2234d5e02ab12e2609b5f1547f3888ac23020000000000001976a914bc34b4978ce51bcab9e2bea4b4b2d3e7aaeffc4788ac230200000000000016001474287528d9d261390b2e4612cdc27f82b1daf9282302000000000000160014e68846d818f5f2367dcbbdeed01ae7e62ed881dd230200000000000017a9143aa4e97541e63d6fb615230db3b9790467d9404e8723020000000000001976a914d161fd65bc8950ae8e758d7caf4bb01f7589ed7a88ac230200000000000017a914865411c372bd22308ae7e49ac9a73ddf4524ac088723020000000000001976a914733eb148bef61d63d544f9e1f134bc28c713622388ac230200000000000017a914aae06c64efa23a13dfeb1ecaed7c5442304e59f78723020000000000001976a914c4b39d67f1063f2b40d93ac7a3c32aeff0d0673988ac230200000000000017a914b4aacc86b0d171d0daeed1e973bfd84efffbd94787230200000000000017a914bca4fca5751781fe4b217b495369494b0970532987230200000000000017a9147c31eb5516ca6be732d4d665993234453e555b908723020000000000001976a91423a5f2901e4291616689c645b86c3f2834b035de88ac23020000000000001976a9144cdf897e8471c4b26128a7586dd1712f5858363288ac23020000000000001976a9148b9f659dc9063387dea0b4b2125caffcb19f52c988ac230200000000000017a914de64339689cffd9954e82650bdc7489899c1c77c8723020000000000001976a9142c3034477226c953c7bfdf37a57b5ef72d84577388ac23020000000000001976a9141b980ccb350e958513cac7031c2f8d037bd3d33d88ac23020000000000001976a914ca470e9456e7fcfd3282b8e5547db71067584c2388ac230200000000000017a9147493cecc87c3e1512aa502791cadc858527cfd608723020000000000001976a9148b9d038965ef40cdf6b2179d24a737f8f0fc64d488ac230200000000000017a9140904f1a65a1671e9718224c90bcdd4d981ed13e687230200000000000017a914a0d0cb1362e3367331f413d4e95dda33bf59ffe287230200000000000017a914b541f609756fb144f5d87b87a515563c5185ed4c87230200000000000016001476de53781da21c28b854714030f60655c01936da23020000000000001976a914553360efb4f1337a304d833c006f65625580e9d688ac230200000000000016001424eb2b58976164272055c5d8e33e134b63ff3af423020000000000001976a9147796681441c9f2eb826398a10afce0240a499cdd88ac230200000000000017a914ed1a54faf310f0fa3fe041219006ededc3e2b090872302000000000000160014c4976d206da3995694b1743d621db3aff3a3f491230200000000000017a9143da99fcef5e7da440530ee7bc0a29428d60d08dd87230200000000000017a9146b2b5a9544bbc70f5255653167c83d589dd6983b87230200000000000017a914b57dad25d82428ddf3d702f8866fa268955a508a8723020000000000001976a914bba81549f149741e79ef1719150b0d52a033538388ac230200000000000017a914b7e6eeddb7a17c62137f758859854124eccb2d2e87230200000000000017a914d4913822e89c430ce31449c024bddb5b6ba721068723020000000000001976a914d26bb7c6fd5d39ab76c32abb956f65333659662a88ac23020000000000001976a914033ebd5d7114934ec871224ee4a9f3c03405772188ac230200000000000017a91474c7b5d931b78c817d32e63f4f660f455a186c528723020000000000001600141ccbee5d78e1ceadd1747fa1f9e2076af14cf3e723020000000000001976a91479cdb818be5c72840a57c43db7a68f897ed2d5ec88ac23020000000000001600149807d8d45c60fd36c5a5f89da84be86061fd8037230200000000000017a9148d4e2d8bb92aaff70aa6755163515e5ccc6882b987230200000000000017a914dda395967c5998540994f26536caf5ff778924f48723020000000000001976a9148fc1ff6e256e7560e3a8f59f92b90d8cbb33031f88ac230200000000000017a914b9b8a32c2d9a660efec10adee18a447422a93f788723020000000000001976a91490f7fec9b9d1f8e00a03536a9efe8e7327cf48e288ac230200000000000017a9141cab5f8200e1a801a70121fc4bec08a7faaed2b987230200000000000017a914198d0d8e324460dbde2eee90279708ddee1871f5872302000000000000160014a98c87a6a076b86a289e504873d6edb005e73163230200000000000017a9143ab083e70d63ab931417b7257995c336847a5ef787230200000000000016001428a5f68c4e39b007619fd0b7b45fff5608c3f13623020000000000001976a914e4200fab7e35453f5d98fb65467e9121fb1490d888ac230200000000000017a91484ed2020d76a13e7a030073060ae412f9807a93287230200000000000016001402cd78d3ec050ed4f06e73aa392ae5cf38f26b95230200000000000017a914eabfcd9efe02602e151bc2b991b9eaf8f859008887230200000000000017a9148b6065dab8302532a12aafa0b830ab2bdb42a71487230200000000000017a91432b7183734429b0aa45ab965d96959d128d8f59e872302000000000000160014a0e9c227e3ca350209011eb658196a678cfdbab1115b7e0600000000160014718eb14c8b2a915f38eb48827d36dc19efd68c650247304402204a0633b56f90119ed2b3bc3284eb5ea45ae018659fc8e8b0ea3e2a369692575c02204b48d99955ecc928823c0c4f32ad3ab8b5a90b07e4bc7a9a2efef99e593a46b20121022ee8e970385fc312ae22d41e89a34e567cfffd3c5ff072853616cea7b122712a72760a0000000069fffffffd006b0000fda714fd0164cb37bac262fc13dc014e0200000000010108d851297f55e24a8f91751d4c316702425e60ce5cb4360cf847d738dd54050e0200000000feffffff02538e000000000000160014b70b54c77a527367690435f0539728b06b548e0a4df8000000000000160014f0c60aa568b9891c1e35b6c4f0a93467ee6879d10400483045022100b2246d051596c73d1fbb17c8388e56cddcdf77debcc83b2b0bcf358ee5533d550220305a7e6163bc15ecbc1058000d2a38d2d872c94702338646cf97f8394bd0ae090147304402205d9351c8e980081e9b330a082d73106edc63b7661c8d09a55010eeb4cdd760b50220045b95ee2a3e380dc07b8bf2c2fc57c77328346617ea781eff80d13b81aab38701475221027dd53ed71a0b2aaab63b43ab431518612ee78759863c8c497ce892aad2c519c72102988c5671f42149973f3cfde0dfd4693123d9daa7dc187acc07669a72c7fddfdf52ae0000000000000000fffffffd006b0000fda714fd01b31514ce59e9d64d0d019d02000000000102be9b153ecf2411f27b824efef1d02c361a408d96fc35b7916c3c363d70a537480100000000fdffffff08d851297f55e24a8f91751d4c316702425e60ce5cb4360cf847d738dd54050e0000000000fdffffff03db0b000000000000160014032f4c093ad59c5a2ebb7ce447835205f5ecb5b5dda901000000000016001484d781502709f5cd296f05f961970a75d5cc033f4a870100000000002200207b6a4bc0229307b69bc980c3759087b45e87f8a23b376a4bc3358376d66d42330247304402201602fe767e6ff0ad2e08287f6bb5455d1d4423863b09a3b9a24bed05370a2d3c022008a09c9bd71e0a64813229c0f048e39f6b2eb6d4677fe102574a6e64998c1f420121024e32511e6deb8b3c1d603fd32657a18a5432e320ca460ca6510a2f15f891f5040247304402201703d4ae617170e9cc5edb57a071b664ab8c174d1b222ad584276fe7bb1f86c802200d72db38ae4bf277e321287dfbd3db58d8c8cbd40d4b7cb22f05c980f31e4689012103bb58041bc35c823ca2bb95f39191c1238a2d766a44187e5bcbfb1d2b2de8110f0000000000000000fffffffd006b0000fda714fd02db8e7b4636bd2bb12d02c502000000000104c02ea210272d2b7f271d28898a79b6ddfc9f8adcac7423f2005633206ffc1da30000000000fdffffff7ff2c0d606d1d845765e5d5467a3b9987600b226ba3c6ec30a8ecd0b698df8be0100000000fdffffffdaaf4278e884588f55e79eb56fb1f6928efb1936457b973e5b3cf992200e16bc0200000000fdffffff0277335952c9dde15fab20dd86b194e100c222590714988f467f6b3fc19a11450200000000fdffffff0363a807000000000016001479a73b0cc447fb8871234f2dcea4a0d5e14cb24f4a87010000000000220020ebe2327de660ea626643166b7115b46fd4837abd29aa35f26ccad978a21c5a83ab29000000000000160014e7e2dab5dbc6fa35e60881802ef5e23fc4a92f510247304402203187cad08f8e82d1c79fb6f377133955d4ee8034f4ef34e96f1a70ce90854b4702200ad2d209d4ba48fe2574e1b475d6414a3419cad8c3d2a119f9afa7936962a18a01210318d993063b1e3ff2f6b1383ee84cefb9f3b2200bc7e1b21dfd347397e5ba81de024730440220052c2a7720f9012b2442ee4a24f70bd285909563d7aed64a89725b4d221c4bbe02207cc4bf4d61b99b79aeabc759f7cff9da5d1b9b69c2ac65e9806f4a18a9cc8cae012103c6b078bcae1001267c41fb90d63b276f81b8383b6fad453de595807219c557bb02473044022035fc2f9905e265f42e5758596c474478be4931cbb719eed517160ca3fef1e5bb0220388a10045e0648d17c45e35784c3a7e7d642b29e45a63e01c60c8ff6dc63e2b7012103c77e544b1a37b1bc1ff32718af6ab51d77b5fe84f208726497c7cb7bbe1542f80247304402206a1494acd00d88524428e7cfbee088b1af1f173e50504b08eb0a200ab83abdf8022064bd678d8b5b4b038f697d31428154dd9261949d7df46ef4b0a0900c2cf25689012103948ee3a77567e69315406972df6772de23951f9c36842dad063de2b03fa110830000000000000002fffffffd006b0000fda714fd01b3306ec90a0159e25b019d02000000000102337679b2b4e0d09e1dc9273a1150ef7fe974aea74534127ff3e2f3afbfc00f180000000000fdfffffff21796c6bed35ddc633cdcec336d9b40ac27098ced9426ffc29b4e2f6bed6e7b0000000000fdffffff034117000000000000160014f86785b71f4f44530c009a2f14e81099277338908bbd000000000000160014c184e92bb428b8d4bbf4f68c82658af2ffe4c2e7468b0100000000002200205264e3d65636e96af8278bbc3e964df04537174dfa47ddef15181e4f1ede435d024730440220212adcbc93e17dbd89be31a6bb8b7a079cbee3dee2d231eb3705f6ded5c2f27e0220070cd559e65af8c398058b91054c434d0ddb51db95b0cef35398dc4f582f0eb3012103d2db9a7d22de629c9ef42a4462beba442498ad12055e04cda81b95e85bc0c81e0247304402204c3b6fe56eb1de8d8ea51fc174910fdeb499fe103a07df333972aa4fe54c5f7f022068fa57e54ec8eec939f7f0544a047a3d2e1d3d73de573a238c29cf2001470da40121024d3e8c14423c04ef79c0be7ca8f1ad0088aec25c41a82c116189081e54c992a20000000000000000fffffffd006b0000fda714fd01b3bb2df4c7aa054453019d02000000000102368af13baeef5a313d3ef12e895b232f1e76212cb76957d7e4b8a664915d15960100000000fdfffffffaec4ef43ae2365d0abc53336188053da4078a5b7489928602bcc8c9a4b75f0d0000000000fdffffff030f0b000000000000160014107eb2463ad25843ed01fd33656c83bdd11db3554a8701000000000022002002265c41f299b3c7f0dda5b9d7bc4135d25c2d8aed286837aa9e0954d70894d606961c000000000016001482a7ecd4624e6856d1b09c27e9f3a82323f49c2d0247304402200911162e99e23e4a26e0219a4bdaaf7a5f790be63a8376516640dcc0860ca4d602203a078371904842e2e6adfbebebcac138db23514b3396851569f5f2bf82c3197a012103cd2d0a4eace5993ebb0a75da85d9070627e64f1a5783cf5217e9bd82d20d1c470247304402200fa8515323410ca2b14b08bf22c618b6ced77b9289cb1dfa7ac10548e2e1b2e002206a407bcafdfb64009182fb5838db9671968abdd902e1194f6883cd0e5413ad36012103d3864eb755690e2b4ff139047419373e36a05630429da76fef5de25eeffb4ffc0000000000000000fffffffd006b0000fda714fd02dbc411c5a2097654c102c502000000000104982f4956c2ac5f0c48942d96695ae60ef800d9aa165fe3c867b824053da9a1470100000000fdffffffb38cd38eef22780475497e7837839c9b311da9418ce65191bd85a7b232547f640000000000fdffffff6866efde4cf495533d1f5ed9d7f3052d58e26d34ad9fd75a5f065282227eb1e20000000000fdffffff0214a90643ac6f3495aa9ed8916af2ec15e96c46af10682169195d8c8d0dc2cc0000000000fdffffff03463000000000000016001448ba92affa20e46dc7c2fcec746080889ac78492f289010000000000220020d40ec2fa1e8c00f97d4d96bc5a60a6d397f62fd23eb326fd2461f3d5848865cd92d50600000000001600142a464d0d10fca3e53b49bcaf307eaefdfd59d7160247304402206e83824012ce95e09469173de716dc3881fcae5fb9711aa05c5df7fdb5054f60022072c4a46ad50b5ebd611778805577419601cbcf90cf42a65a6f36e51d2a937771012102dad6c5f135b9a9a5ee9f0d5a828760373696c686ce3d6047ed37e2bd6c7c60200247304402206dc3a95bf2ebf3051e177bd37fa30df8293ad4e3d74d1b9c0c864c58adeb422c02200f60a8bd667f34f4467b0532361816ae398cc4f48d5bebe76cc8df00cc9eb9fa012103911309104575a84aad2a36d35033e172c6bfd3a195649074c96ff24864377dcd0247304402205b0119225eaf2b127203bb6fc2072695a6f19bcefb91172c4e486320c72c590c02202af0b2d8b1b82f5241cd906fcf9f7575eb2f9a3d13368d38540b1974e5d5de3b01210348d08290108093b047047a6f18f1562fe6bfa3b2104f4a77a0dee27b22dbf450024730440220783688959deb6aac94ebe639b294237955742cc6c4c95fa4b65a441851c32b890220672c0819b35101c0e331b6770468f38f85d4620befb869bacbaf12fb909018b9012102946459bf02d94a6014499a9c357fe2bcb1e02367b3b323f1207315dd9b3e956c0000000000000000fffffffd006b0000fda714fd01886e5288e0df88ce5701720200000000010286cccb3f53bf52291f58bef99e46d81bc21ba752391043b3ea94656cf7f62ed7000000000000000000bd481ff19b3861215be6c9898ca0e6d1a86bd03970494c1e10d857655576e033000000000000000000027337000000000000160014e60ce491b7f7a548ed6d6b8ca88d47ad398bdfedf8240100000000001600145ee7fa05b91109e8098906ee34ecfebd2dfb24b502473044022067095f1e06b2d860d34cccfdcb7dde62d963f2c3ad004785e329b66ee782cc3102202c1b4a9705ed043ded2f413407d1000eefd8cd6222a43d59387bda8c1ca0450801210304e5ecdd25c310458d4b8f313b37593f6a6524dd26ae571a13c6ba3f2939c6ee0247304402207bc0328ac59719ac05b8a170eda77746dadf55af84302b03073c608af42f40ee0220212f9e71fe42eb364aa21d2c86a0e87235f3d40d505dae7d2b3f819ea8688df4012102856d51b4715d6e271a0099b16e7db0f8fec3229c00633564a0cdc5569fd708b80000000000000000fffffffd006b0000001600141e9b40ba13d526b9a194d9a72092e2b31dfff4391eb96589045fe8683c3d3490da894aee00000000000000050000000061a56980

Error message i received on the accept side of a DLC (my macbook) running c419932 . It seems to be related to utxo selection? 

Here is the stack trace from the acceptor's view: 

>2021-11-22T17:16:10UTC INFO [DLCWallet$DLCWalletImpl] Initializing DLC from received offer with tempContractId 0a1671d9a8f56fea7024883ec580b42202eb70ef28a651c5401a31976f6cc8ee
2021-11-22T17:16:10UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Accept for tempContractId 0a1671d9a8f56fea7024883ec580b42202eb70ef28a651c5401a31976f6cc8ee
2021-11-22T17:16:10UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: d971ffafdb251f0281e8061c2900022c5fca9858cf2099462d53151a7c61d9c4:17, d971ffafdb251f0281e8061c2900022c5fca9858cf2099462d53151a7c61d9c4:381, 9d229e371afc4fec6aa20a5dd1912827ae8969774ea5621e7843e9b3c32b496e:0, 21f591323613075416f62034c7153b41806b34155f755c6ea290a8c749deb23f:0, e28d374101afd85a93fa50588ef75b4107706182b33710edbae72b38912acb85:0
2021-11-22T17:16:10UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(547 sats,wpkh(a9beb0dcf0f7e83b5e7cf22c43a55443bcf7220e))
2021-11-22T17:16:10UTC INFO [DLCWallet$DLCWalletImpl] UTXO 1 details: TransactionOutput(547 sats,wpkh(d431e458cc852e7f2f21a6055751b5d2f30b7bca))
2021-11-22T17:16:10UTC INFO [DLCWallet$DLCWalletImpl] UTXO 2 details: TransactionOutput(15996 sats,wpkh(b5597452a0b3cbb3438e40e27f57aaf23a37989f))
2021-11-22T17:16:10UTC INFO [DLCWallet$DLCWalletImpl] UTXO 3 details: TransactionOutput(27190 sats,wpkh(6715b30cd2860d46dde13785e6895c447ba956c8))
2021-11-22T17:16:10UTC INFO [DLCWallet$DLCWalletImpl] UTXO 4 details: TransactionOutput(46160 sats,wpkh(0f118099a2794f8d382345a70935859e15e6cd93))
2021-11-22T17:16:10UTC INFO [DLCWallet$DLCWalletImpl] Creating CET Sigs for 6a9ecdeb5f3d0e056d33b7c87df7c3b8e95008912a2c5aadc17db2090033673c
2021-11-22T17:16:16UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
2021-11-22T17:16:16UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
2021-11-22T17:16:16UTC ERROR [DLCDataHandler] Failed to process lnMessage=LnMessage(DLCOfferTLV(None,0,DoubleSha256Digest(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000),ContractInfoV0TLV(100000 sats,ContractDescriptorV1TLV(18,PayoutFunctionV0TLV(Vector(TLVPoint(0,0 sats,0,true), TLVPoint(60000,50000 sats,0,true), TLVPoint(120000,100000 sats,0,true), TLVPoint(262143,100000 sats,0,true))),RoundingIntervalsV0TLV(Vector())),OracleInfoV0TLV(OracleAnnouncementV0TLV(SchnorrDigitalSignature(SchnorrNonce(ByteVector(32 bytes, 0xe4940b5c507fa0ad208f90182034d0b8318b1a682e29aaddcd2ba3f365c383fc)),FieldElement(ByteVector(32 bytes, 0xc3992ff57c9cee8724170798abb03efca738dcda7f1e5fbe1842c41b1d603f79))),SchnorrPublicKey(ByteVector(32 bytes, 0x04ba9838623f02c940d20d7b185d410178cff7990c7fcf19186c7f58c7c4b8de)),OracleEventV0TLV(IndexedSeq(SchnorrNonce(ByteVector(32 bytes, 0xa83876a19b89b28555e9a76adb6336ff3144c983e65af63281a878dc519d8895)), SchnorrNonce(ByteVector(32 bytes, 0x35ea0d03d3ba09e0cb0225691395ceee6c92df4cee1a5e90d4dd499d3598de07)), SchnorrNonce(ByteVector(32 bytes, 0x70945a614653cceca4e8cc4a31947eeeaba7a54042412d707a9e35350fab8906)), SchnorrNonce(ByteVector(32 bytes, 0xbc408e8096f7542d4577f8cebf751bf05bcbeddf33a57fddea50923bb7abc66a)), SchnorrNonce(ByteVector(32 bytes, 0x0f2bdf85f7ed09deaf49ce2619c1acdc2a854bc2eb7004c2d7c1c2c3ff94d589)), SchnorrNonce(ByteVector(32 bytes, 0x6ffeb3ec7f7b65521ab71aab516dca2a79156f2e84c9997a1802fbe49c348fb8)), SchnorrNonce(ByteVector(32 bytes, 0x0ac4078ce464f2745d10de73844b791a42ee0abcb34ec5eb23ea2e7a361e0ba2)), SchnorrNonce(ByteVector(32 bytes, 0x57acd4b5f2344fec63c94ed373050df11a016f76ac3af8e903b5fc6d9f860f34)), SchnorrNonce(ByteVector(32 bytes, 0x4d817d273b13617cd5a47f32277dd95323e019d8b92ccf140d7697a8357079f7)), SchnorrNonce(ByteVector(32 bytes, 0x88c426aeccac83f2658c3f4a5d50ed6d396ef9761236d10a08ac3376aded93cd)), SchnorrNonce(ByteVector(32 bytes, 0xaa8cb8c3c6bceb2c0590d8e58e52b7ec0b584f2d51d1f8d0b0478970500d92a9)), SchnorrNonce(ByteVector(32 bytes, 0x38c3e748ad669a351976595308e050fa521f259dab6ab97338e307135af007a1)), SchnorrNonce(ByteVector(32 bytes, 0xf3f0c4326c3d14736a7aa359f2e8650605013d4b8de11df3c2ae1d2057f9aad0)), SchnorrNonce(ByteVector(32 bytes, 0x42d8f91577f2c95b120a1ab6625d0c1f04bb2e566f2f81284429815f50a4f1a4)), SchnorrNonce(ByteVector(32 bytes, 0x1140b133f7ec982dabec0d4ae927ec2fb8414ede94b6ba1b7ab7a1f032f64324)), SchnorrNonce(ByteVector(32 bytes, 0xfa9e7b5b3174afe16a044d71b8340ed7f006b752090233e4f7d78810fbf1bbe0)), SchnorrNonce(ByteVector(32 bytes, 0x776ef5ea31db31b2618f5ad442b717ea8b98b3f765bed501909ff2d6e1d359ff)), SchnorrNonce(ByteVector(32 bytes, 0x3482b6f19fb11ccaa21af195e453dd6f6c95e239d2801c9fc5caf8cb7be1bb1d))),UInt32Impl(1637654400),UnsignedDigitDecompositionEventDescriptor(UInt16Impl(2),UInt16Impl(18),BTCUSD,Int32Impl(0)),Deribit-BTC-23NOV21)))),ECPublicKey(029a0d3a261804afb0e7ed265e8b6cbc05fc2b7d1a51fe806f9a840e5496e7bfb8),wpkh(2a936ba471a4e3ef46fb40383ad999550fbd4ace),UInt64Impl(2973922162564956232),50000 sats,Vector(FundingInputV0TLV(UInt64Impl(2713864236599730749),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(aa07a5e0b6a827007d502620077d3c0046a7cdbb43a7e68b76d1c4fc17774c15:1),EmptyScriptSignature,UInt32Impl(4294967295)), TransactionInputImpl(TransactionOutPoint(e18787fa513849d48ceb6f73026fd0893f59e718bbc05d480d0594a75772ba28:1),EmptyScriptSignature,UInt32Impl(4294967295)), TransactionInputImpl(TransactionOutPoint(29373b52de8688aa12d8fface5140daea95b396937844a6304cc306906256f7c:1),EmptyScriptSignature,UInt32Impl(4294967295))),Vector(TransactionOutput(109859 sats,wsh(5cf4bb9ced93fc5e6945e66dab2a69626507ea98aa5ab256bf7207881b96da6d)), TransactionOutput(1179 sats,wpkh(52584eb56f12d421e5efc49ecddc5eb873958cc0)), TransactionOutput(1751892 sats,wpkh(48560654ca7b9e9f2d1c5aa1753b86ede0d8f0cf))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(0349ba5cb6c8789ebe90efdf9823ea955581f7a334274ac8adbb9e62cba846c946, 304402201c6e837e66d50593b2b2870171b07e3ebea10254e0c8f96c84d0a6858d555941022025c510efaad7498eb256f9d3f4b2400dff8ad745ceb36ab2539847c5a0a38e8901)), P2WPKHWitnessV0(List(03befb8fdbe90fc1599843efa07ea7fc55092d801e0e3a98c698f9db5cb68a159b, 30440220139a519f463e5785bb4f92d128f408a3ba2d3e98ab545f451c26ba6bef332f4402200c34dd76965aa9eeebedc8c247d589a96d4fed210a9205d35c7aa3a2005a21a801)), P2WPKHWitnessV0(List(03ec3ececed56128fdd6696e2b53b68895c5f3e8b6a57d107fb0b28d724843a01c, 304402207e674707f31ff1ab4c5a68483a07186899b08eac63e2a653e60029571e80171002207806ac1c73c108ae214357be17035450545f894c783713e7b23cfb1d7b63359801)))),UInt32Impl(1),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(10206425705757784258),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(d16951b1b91ee315310928be07c52fa92e7c98f73bb94e7b705a6e8ca972b939:607),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(547 sats,pkh(03b7892656a4c3df81b2f3e974f8e5ed2dc78dee)), TransactionOutput(547 sats,pkh(075b7dfca1465daa6f51b8497af83c10042ef399)), TransactionOutput(547 sats,pkh(08d2de7257e4f777653b939c6bcb7401aeabf1ff)), TransactionOutput(547 sats,pkh(04d9d15e67e6f20551992e03039711e59281f728)), TransactionOutput(547 sats,pkh(06f61b94f0e562e41e7137a8b0aa78db61029257)), TransactionOutput(547 sats,pkh(09cc4cb806f792fe235c1b8149c0267b12067c97)), TransactionOutput(547 sats,pkh(0a9598557e4075d6543a51a33a6a84d6945b6a8e)), TransactionOutput(547 sats,wpkh(9fb2f9537a8fd38df559346405be2baa3c72c90d)), TransactionOutput(547 sats,sh(083dc9041c5af68d3a84b5649f38300ba8ce2bf9)), TransactionOutput(547 sats,sh(166278d881b3fe8d1fe8fcc71a94b1381f65c6e3)), TransactionOutput(547 sats,sh(4947e8225918b63e0a1146715c1d31a9db29d265)), TransactionOutput(547 sats,pkh(38c04525a19adcbe2ee618c371b819a1842aec67)), TransactionOutput(547 sats,pkh(6261111744bcb237fc16475b58966e05e49ee914)), TransactionOutput(547 sats,wpkh(f8f416e8650cf65853d9b2ccb68f291736ce9f16)), TransactionOutput(547 sats,sh(cafecd5bd4e863243325220c2ae77acd4e6a483a)), TransactionOutput(547 sats,wpkh(15bda5f82091653d281bed4baf448c3e836894fa)), TransactionOutput(547 sats,sh(d798abd4c7b615cbbda823bc1ac90aa95a6c5d20)), TransactionOutput(547 sats,sh(a61ad56f619d34cb27e8e6084e61d0c781b57043)), TransactionOutput(547 sats,wpkh(c390a98f9bd670f7fffd05ad0c49030ea3558e0d)), TransactionOutput(547 sats,sh(ab7cd63a2467544015f1b836bc7ee825014ed1f6)), TransactionOutput(547 sats,wpkh(0e28c69bda7fc84d7596ac5ab984108eec189039)), TransactionOutput(547 sats,sh(d686e9e2933770f2f0505940bd1b71961278436e)), TransactionOutput(547 sats,sh(d11e7c96aa252713b3e952f0aa6cb5dab5845488)), TransactionOutput(547 sats,pkh(ab8df34991a3904bfc7af8695d25e878272a80da)), TransactionOutput(547 sats,sh(f90558a334d9e94ed55f2758d45d77aa2a12a4b3)), TransactionOutput(547 sats,sh(c576afd0b25b74b0536ad748d5c0caf4dc02aa72)), TransactionOutput(547 sats,pkh(7f162d1676d136c43103eb829ea4fc0144356ebf)), TransactionOutput(547 sats,sh(af9769bb90961b4cceb63b6aa658c6b08b6c7236)), TransactionOutput(547 sats,pkh(a2d2ff77f0532b78cde36b3342cf8d39ed25310b)), TransactionOutput(547 sats,pkh(7b00ba7bb0706d0d3513c25f0e176ec10aa8357a)), TransactionOutput(547 sats,wpkh(8e5d7d761aa81e21d44794ac18f327043bb51c29)), TransactionOutput(547 sats,sh(dd3d5c36925f9da35a1e41cc767662225907d356)), TransactionOutput(547 sats,sh(92948622bd64e5ab5cc3131f46fd6e020ec9cd77)), TransactionOutput(547 sats,pkh(04bc122a97b3d767c74d9903ca0fa9ae759a4f77)), TransactionOutput(547 sats,wpkh(800a2fa1c5ce8f76066337945a30bf20676d3e74)), TransactionOutput(547 sats,sh(95422ffb24b0b15582c0d6dd85ddd512ae932a1e)), TransactionOutput(547 sats,sh(9e9fac02c01735cde61fa38599f6277c0a9d50e3)), TransactionOutput(547 sats,pkh(78729f374b26f142b9fd0aa95c18ec177aa5718a)), TransactionOutput(547 sats,pkh(117abda60c33332922cbc775ba1736c3962e8fc7)), TransactionOutput(547 sats,pkh(86ee82444dbef6b1a1b1a80178aec6e50a026661)), TransactionOutput(547 sats,sh(4c28496aa3e360638395ae867c52a376d9b67602)), TransactionOutput(547 sats,pkh(52791bea99155d14fc7aa2be33432e8d5a6e7acc)), TransactionOutput(547 sats,sh(a038e6d23699603fa481830d233aadc9ba1a50a5)), TransactionOutput(547 sats,sh(999e70797506b99f9fe7425f4b04223968ff5451)), TransactionOutput(547 sats,pkh(52b0bf8ad6ec03bfa28f946025a9ec118c9438d6)), TransactionOutput(547 sats,sh(ceb97a9a76bddc2e3c291bb57ccf08bd6ef26b33)), TransactionOutput(547 sats,sh(059e93240e9ad13a0cefef0bd0da7af09c63efa7)), TransactionOutput(547 sats,sh(c5b4340a8d91046723b926fd070eddd0e3aea879)), TransactionOutput(547 sats,pkh(d9081422d11330156348eed7188296d7f86a1ba1)), TransactionOutput(547 sats,sh(c4de313f3a10e3cd00e63a6192ec77d97b393f64)), TransactionOutput(547 sats,pkh(152924f27f61c0e2d74b6789eba026320e5157c5)), TransactionOutput(547 sats,sh(67835200a0c01b1c7b6985daa6d6e20bc42a83d1)), TransactionOutput(547 sats,sh(8ad3fad7a520fd92150e2cd71e5fc94cfc58e444)), TransactionOutput(547 sats,pkh(02826240dc63aaa77ab740b589b71dccd328e81c)), TransactionOutput(547 sats,pkh(5fd10d16dee6404b86867ba316d9fc4bf120f363)), TransactionOutput(547 sats,pkh(a068282adf132d1f09394d1bc9ce6fb6d0a9fcec)), TransactionOutput(547 sats,pkh(fd5801e308fad7a10f8aa35c3631bd9f1a29ca2a)), TransactionOutput(547 sats,pkh(41d2321f1f48475795bb63e9ba92253558eafd34)), TransactionOutput(547 sats,wpkh(40d085fc97c7f10d8e8941df91cfdb14c8f31773)), TransactionOutput(547 sats,sh(f3b478c591c1998e204c4139cf7acaf2775f2577)), TransactionOutput(547 sats,sh(a42aebef7e9394c534ad3921017236fd831b3752)), TransactionOutput(547 sats,sh(05ebff2bb06018f1dcbabdbdab3ffd13f70a0a21)), TransactionOutput(547 sats,pkh(7426386edb015d6ab9f7a03ea9d9fec2f88087f9)), TransactionOutput(547 sats,sh(ffcdc453f7c2233cddc6f1a3c5dc9f1dd457c66b)), TransactionOutput(547 sats,pkh(37656021883983ddf2a2947b923671b4f407cbcf)), TransactionOutput(547 sats,wpkh(b6f82d7f07c3f5be91fed19f76062581612e9c72)), TransactionOutput(547 sats,wpkh(07494f429133c6d580ed901ca22b793a4b6f031a)), TransactionOutput(547 sats,sh(503e431c5cddfcbcba6b6b7a58b8c0eb4bb9372e)), TransactionOutput(547 sats,pkh(ee30800a1ae846689dcb62d10d73bdd53b122630)), TransactionOutput(547 sats,pkh(6065c5d7d9b0f8dcdad5da95ff8b2d70be7cf400)), TransactionOutput(547 sats,wpkh(f402151c8388fa91172f1d0c85b25b0e680692e8)), TransactionOutput(547 sats,pkh(c6a0c630aff95f37c99681a8caa9ce414baf3b24)), TransactionOutput(547 sats,sh(703e36245b8e117b6126624bdc06fc8af0786ced)), TransactionOutput(547 sats,sh(2e84d2d9ff58e5158da8c4b73e607e458e5bcee6)), TransactionOutput(547 sats,pkh(39b03548d49ea1fffd7491be87c25534d92b65d6)), TransactionOutput(547 sats,pkh(da7780d7ec425b2164f4c7851c1947f799a317c8)), TransactionOutput(547 sats,sh(627a2a7a29265badc12e612622957ec7a60465c3)), TransactionOutput(547 sats,wpkh(8ca512ac6642963d71b3e17af949092bc3295417)), TransactionOutput(547 sats,sh(9721b126f0432a31d3ef318cd8f2c7f375ab18a5)), TransactionOutput(547 sats,wpkh(d0929a49be169a16aa8333a20028f7bf0239df76)), TransactionOutput(547 sats,pkh(e564ae45b875b8f5ee95ceda7f5d008bbf76bb55)), TransactionOutput(547 sats,sh(96799d921a74f417ad40e9ac0dfee6ce21b10009)), TransactionOutput(547 sats,sh(779179aee640e5f01e9d21efad0a736d0123bdb8)), TransactionOutput(547 sats,wpkh(6e4416646092d87274c35d3e6a8968ff14f4bf2d)), TransactionOutput(547 sats,sh(e287d41cfefdab09c04b321880f55ac215fd0134)), TransactionOutput(547sats,sh(f25b9ea827187ba264c0a179be76a6943824149a)), TransactionOutput(547 sats,pkh(e98af4e43fa9e1b0e36ca8041278079a3a0883f5)), TransactionOutput(547 sats,sh(32b7183734429b0aa45ab965d96959d128d8f59e)), TransactionOutput(547 sats,wpkh(a0e9c227e3ca350209011eb658196a678cfdbab1)), TransactionOutput(108944145 sats,wpkh(718eb14c8b2a915f38eb48827d36dc19efd68c65))),UInt32Impl(685682),IndexedSeq(P2WPKHWitnessV0(List(022ee8e970385fc312ae22d41e89a34e567cfffd3c5ff072853616cea7b122712a, 304402204a0633b56f90119ed2b3bc3284eb5ea45ae018659fc8e8b0ea3e2a369692575c02204b48d99955ecc928823c0c4f32ad3ab8b5a90b07e4bc7a9a2efef99e593a46b201)))),UInt32Impl(91),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(15827619887149376564),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(d16951b1b91ee315310928be07c52fa92e7c98f73bb94e7b705a6e8ca972b939:607),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(547 sats,pkh(03b7892656a4c3df81b2f3e974f8e5ed2dc78dee)), TransactionOutput(547 sats,pkh(075b7dfca1465daa6f51b8497af83c10042ef399)), TransactionOutput(547 sats,pkh(08d2de7257e4f777653b939c6bcb7401aeabf1ff)), TransactionOutput(547 sats,pkh(04d9d15e67e6f20551992e03039711e59281f728)), TransactionOutput(547 sats,pkh(06f61b94f0e562e41e7137a8b0aa78db61029257)), TransactionOutput(547 sats,pkh(09cc4cb806f792fe235c1b8149c0267b12067c97)), TransactionOutput(547 sats,pkh(0a9598557e4075d6543a51a33a6a84d6945b6a8e)), TransactionOutput(547 sats,wpkh(9fb2f9537a8fd38df559346405be2baa3c72c90d)), TransactionOutput(547 sats,sh(083dc9041c5af68d3a84b5649f38300ba8ce2bf9)), TransactionOutput(547 sats,sh(166278d881b3fe8d1fe8fcc71a94b1381f65c6e3)), TransactionOutput(547 sats,sh(4947e8225918b63e0a1146715c1d31a9db29d265)), TransactionOutput(547 sats,pkh(38c04525a19adcbe2ee618c371b819a1842aec67)), TransactionOutput(547 sats,pkh(6261111744bcb237fc16475b58966e05e49ee914)), TransactionOutput(547 sats,wpkh(f8f416e8650cf65853d9b2ccb68f291736ce9f16)), TransactionOutput(547 sats,sh(cafecd5bd4e863243325220c2ae77acd4e6a483a)), TransactionOutput(547 sats,wpkh(15bda5f82091653d281bed4baf448c3e836894fa)), TransactionOutput(547 sats,sh(d798abd4c7b615cbbda823bc1ac90aa95a6c5d20)), TransactionOutput(547 sats,sh(a61ad56f619d34cb27e8e6084e61d0c781b57043)), TransactionOutput(547 sats,wpkh(c390a98f9bd670f7fffd05ad0c49030ea3558e0d)), TransactionOutput(547 sats,sh(ab7cd63a2467544015f1b836bc7ee825014ed1f6)), TransactionOutput(547 sats,wpkh(0e28c69bda7fc84d7596ac5ab984108eec189039)), TransactionOutput(547 sats,sh(d686e9e2933770f2f0505940bd1b71961278436e)), TransactionOutput(547 sats,sh(d11e7c96aa252713b3e952f0aa6cb5dab5845488)), TransactionOutput(547 sats,pkh(ab8df34991a3904bfc7af8695d25e878272a80da)), TransactionOutput(547 sats,sh(f90558a334d9e94ed55f2758d45d77aa2a12a4b3)), TransactionOutput(547 sats,sh(c576afd0b25b74b0536ad748d5c0caf4dc02aa72)), TransactionOutput(547 sats,pkh(7f162d1676d136c43103eb829ea4fc0144356ebf)), TransactionOutput(547 sats,sh(af9769bb90961b4cceb63b6aa658c6b08b6c7236)), TransactionOutput(547 sats,pkh(a2d2ff77f0532b78cde36b3342cf8d39ed25310b)), TransactionOutput(547 sats,pkh(7b00ba7bb0706d0d3513c25f0e176ec10aa8357a)), TransactionOutput(547 sats,wpkh(8e5d7d761aa81e21d44794ac18f327043bb51c29)), TransactionOutput(547 sats,sh(dd3d5c36925f9da35a1e41cc767662225907d356)), TransactionOutput(547 sats,sh(92948622bd64e5ab5cc3131f46fd6e020ec9cd77)), TransactionOutput(547 sats,pkh(04bc122a97b3d767c74d9903ca0fa9ae759a4f77)), TransactionOutput(547 sats,wpkh(800a2fa1c5ce8f76066337945a30bf20676d3e74)), TransactionOutput(547 sats,sh(95422ffb24b0b15582c0d6dd85ddd512ae932a1e)), TransactionOutput(547 sats,sh(9e9fac02c01735cde61fa38599f6277c0a9d50e3)), TransactionOutput(547 sats,pkh(78729f374b26f142b9fd0aa95c18ec177aa5718a)), TransactionOutput(547 sats,pkh(117abda60c33332922cbc775ba1736c3962e8fc7)), TransactionOutput(547 sats,wpkh(10d6a10f70cae84349607017a2672df471a3bd40)), TransactionOutput(547 sats,wpkh(3bb333182bcc902e2ef13681091f1cebf86e851c)), TransactionOutput(547 sats,pkh(b57013aebc7dde1cd4049d6c68a0cde27984a8c0)), TransactionOutput(547 sats,sh(3e257da258c88ca015e00e93a4d279ed8662136f)), TransactionOutput(547 sats,wpkh(f05e6a00a088dbbf80605943127dc3d74c719cab)), TransactionOutput(547 sats,sh(1e1513ccafe9c48a2d336066996cd03fb9bafa10)), TransactionOutput(547 sats,sh(132bd5760b9c030ad9f0865c55336a6ea9d9631b)), TransactionOutput(547 sats,pkh(d7eda7fa5262f2a620ee6a68353a40759025e85c)), TransactionOutput(547 sats,wpkh(c85ab3e3feb9a17c9d754647744a00a5ca44bb5b)), TransactionOutput(547 sats,pkh(5ee7d8d516267c0a9d7bf9c0d3b065bceb48f8e9)), TransactionOutput(547 sats,sh(bdabc85c063b9505639944d5abec7a4051801b1e)), TransactionOutput(547 sats,pkh(848c0fb744c34c294bb872c039f7b808b8b47d0b)), TransactionOutput(547 sats,wpkh(99b754524469d6ad0d02b6db53d197d866b4dfa6)), TransactionOutput(547 sats,pkh(2f27df9390470738329eb9e65a2a1dfcde42ca94)), TransactionOutput(547 sats,pkh(cf21f69d7e312aea192bd9e57721daf3d0a366cd)), TransactionOutput(547 sats,sh(48e9f35671e79ecce10259f6e5839d800957ab68)), TransactionOutput(547 sats,sh(f6c94bc3dd972025d1f3683b7cb52820c95bc976)), TransactionOutput(547 sats,pkh(a42ba2bc745b7e4e0e72302019806e6831f0b2f5)), TransactionOutput(547 sats,sh(e6707453710971cef8be91e32e841bec294c028e)), TransactionOutput(547 sats,sh(7d2522b44c72cda6b343d7d27666c9c9ec7ee071)), TransactionOutput(547 sats,pkh(437612ebe04191ec2f1e38fca51875ba8cca5cb7)), TransactionOutput(547 sats,pkh(efd994588c4209e98cc272b82f925b0403b952ae)), TransactionOutput(547 sats,pkh(7f026f6360e869d23a055ef59412f3fa706e061d)), TransactionOutput(547 sats,pkh(669a807ff902b80c1447816a1cdea9d7198b7473)), TransactionOutput(547 sats,sh(e1d300eb2c9b18e74995f69a8b9e5d906eb2dab9)), TransactionOutput(547 sats,sh(4a9bb4d751a68ff69e386eaf846b2988a3d57a9e)), TransactionOutput(547 sats,wpkh(1bafbbfc72d46f958a7f29ead2890cbd01551e4a)), TransactionOutput(547 sats,pkh(a15b019177e57a7e30f778b7e1f60b166415db81)), TransactionOutput(547 sats,wpkh(d159cfceab0450919e4a7d424dd322fdd136b486)), TransactionOutput(547 sats,sh(e5793fc0434b18b0487d95ddc5d5c524520b597d)), TransactionOutput(547 sats,pkh(40780fba501b7bdfa5d0b2a9799ce52399993ed2)), TransactionOutput(547 sats,pkh(782686d03338f1c5e1694046636176d81f3e9e18)), TransactionOutput(547 sats,sh(3415462039fa2b69f56d9a1672c3d075db6e6f24)), TransactionOutput(547 sats,wpkh(7838b97c5a48b0de99e6305d32de4aad42a8ce80)), TransactionOutput(547 sats,sh(6986783e33115c90b60e8cb02a02ce54bc11e347)), TransactionOutput(547 sats,pkh(9a9e35d3c0c9ea32830cd82a3acc72fedc3400b0)), TransactionOutput(547 sats,sh(725946687317874e800cae544e1d9f97a2f66823)), TransactionOutput(547 sats,sh(8f11f28dc7e7b0b644a26574b83ed45881f69609)), TransactionOutput(547 sats,sh(407efa1735aa1294aa4e75e4f0bd1aa3d135d812)), TransactionOutput(547 sats,sh(f3370dc8873bd4c7a32d786318b5d5519944c1b5)), TransactionOutput(547 sats,sh(e3879d24370b39597fafc0ac342bf180328463c5)), TransactionOutput(547 sats,wpkh(7c4f33b7702363c2ce15909b3858fec06ddde67a)), TransactionOutput(547 sats,pkh(a5a072c325e77f222e24c9251b1e14bcaed137d1)), TransactionOutput(547 sats,pkh(2da18b9be3f1604823d7db4a5dfaa5efbf7ff583)), TransactionOutput(547 sats,sh(777f803f72c392a2c6a9eef4d40a170205be9fe2)), TransactionOutput(547 sats,sh(6918f281da7e641d0b90f511f35a9128ffc37e16)), TransactionOutput(547 sats,pkh(68f02d4626b8524923875ebaf3bcf4d6f68aab4a)), TransactionOutput(547 sats,pkh(5e4db041915c4daba068c49c51ceae09c84f1cdb)), TransactionOutput(547 sats,pkh(cf556ac3c916551048deeaa527989e1088608f5d)), TransactionOutput(547 sats,wpkh(fe5f7fb2e28ba25b1c6df1469981682b9a320cff)), TransactionOutput(547 sats,pkh(9030478aae3edac9b71306d26398d5fbdb04021f)), TransactionOutput(547 sats,sh(482a6e63ee8700be61f93267b7440d30b341fa9d)), TransactionOutput(547 sats,pkh(a8567c92f57ad92e2ec7d10238cbb77536fd4153)), TransactionOutput(547 sats,pkh(3101581e1ce201b5dda8d10ce565067706e4290e)), TransactionOutput(547 sats,pkh(8757fa39b205dc19aee1431e4926a024cd29e79d)), TransactionOutput(547 sats,pkh(233951587260464ec1c08eedd3f90f18b56f37e8)), TransactionOutput(547 sats,sh(bdf3e9d6e4993d2d1683d3b5c24cc265859c872e)), TransactionOutput(547 sats,pkh(02dd9d2e86952bdc4999c7c34400407fda9b6e74)), TransactionOutput(547 sats,sh(53250ade815844653339f8120af51fa1fab8a570)), TransactionOutput(547 sats,pkh(4986b21668eec5e7892c75a75dbf1d740fe61bb1)), TransactionOutput(547 sats,sh(29ea8b11b1ed498474a01a306bf411a38657a535)), TransactionOutput(547 sats,sh(92715a9a554c984c0f6b30660145912a2c7e7c70)), TransactionOutput(547 sats,pkh(bf527572bb5862c7e84ceea6bec5a4fafe46251c)), TransactionOutput(547 sats,wpkh(5bdd6829dc171596cebdcbf66023e900183c1c69)), TransactionOutput(547 sats,sh(87abf5151ae4270b7d71012712b162756bc38d88)), TransactionOutput(547 sats,pkh(0b822e0bef510fe018c4793aa1a61d2fd14933fa)), TransactionOutput(547 sats,pkh(b3ba8762ff5a03945d0e591866aa80cab238875b)), TransactionOutput(547 sats,pkh(bcda05a85decca0fbfc105f34dcc9d1ff6ce4c6f)), TransactionOutput(547 sats,pkh(a26e333aaf75821ee99ffd135fb7d4cff33ba0fb)), TransactionOutput(547 sats,pkh(3441292259c79eb9665e7bd9db25bfccc6190eb7)), TransactionOutput(547 sats,wpkh(a0d2c014796aec0497e4cffc2e34c7fcd86a7af5)), TransactionOutput(547 sats,pkh(b5a55bc4872539ea89aa7e7118f1ea065a11945f)), TransactionOutput(547 sats,wpkh(64c7e81fd7bf1dff3089e25122f82eacf3232d1b)), TransactionOutput(547 sats,sh(9c4974bdcda2e3c5cf259585cd15a36b250b58d1)), TransactionOutput(547 sats,pkh(2bda83492a48e41018b42b20b9385f695991b7d7)), TransactionOutput(547 sats,pkh(7001b5d4c5fed4b4f5fd7572e53597798150a1a1)), TransactionOutput(547 sats,sh(297ecaa88e0356bf479d37b3c99e26904ee8a8b6)), TransactionOutput(547 sats,sh(eb631675bd26081e32d23d53c507b5cf1f1f1111)), TransactionOutput(547 sats,sh(03d30a45d7831d367e1832df55dd6035d6ebac78)), TransactionOutput(547 sats,sh(d3117b38fe904fd46bdf27571c4df8b1827aa69c)), TransactionOutput(547 sats,pkh(db2acd0a4bfb14c151b24b6a1f840fd3e48aae41)), TransactionOutput(547 sats,pkh(1a97f348b05c18cdbb1e224d695b03841dc37a87)), TransactionOutput(547 sats,pkh(1066f94732935460f13496a3a3d4e18c16a896f9)), TransactionOutput(547 sats,pkh(15d9c7272ef24727d60d560506d6cadafe4f3e1a)), TransactionOutput(547 sats,sh(90f0e5c26aa667b451a5d0c909391b354d6d0906)), TransactionOutput(547 sats,sh(9640d5b97acece03ec72b76f8b8a9892f20f4bbc)), TransactionOutput(547 sats,wpkh(acc299c860fd9bb7134a8fee46a2b499f84c47c5)), TransactionOutput(547 sats,pkh(f175ab5ec14999c33857eb4d88953802de009a2f)), TransactionOutput(547 sats,pkh(4f9682eaa9b671bc2a6736583be9e2e6ad7d96f2)), TransactionOutput(547 sats,wpkh(639c6ea53206fdcda5af57ce6922867add84e20f)), TransactionOutput(547 sats,sh(c15f6a343310cb953df9f14e3dd441b8fec57235)), TransactionOutput(547 sats,sh(0843a49814635ea03f6ed3eb7b394ed1f9e3997a)), TransactionOutput(547 sats,wpkh(4bbeddb7d8761bf6b9f2e4c00ecbbb9033b76a8b)), TransactionOutput(547 sats,pkh(59fb930127c59313401725bedf159e8001b2d0ab)), TransactionOutput(547 sats,pkh(2b08b8c36d1d0ca1fe951676d2e8deecc10cd672)), TransactionOutput(547 sats,pkh(1cceaf463bb18ed44a5788fff0351ca7a105eccc)), TransactionOutput(547 sats,wpkh(92ce08bf9f8b4f65dfe10040b04599d7af999f69)), TransactionOutput(547 sats,wpkh(45d6979c266f53ea9bdd60335f43cdf8ec3d46f2)), TransactionOutput(547 sats,pkh(5e66657c77ec79fb9ba2a4b6662e81ada08470d1)), TransactionOutput(547 sats,pkh(edb3e35c36330b40517badf19b8667d8d8a91fcf)), TransactionOutput(547 sats,wpkh(a0d0285c9bf5c614e2eb8694459e734c405f61ad)), TransactionOutput(547 sats,wpkh(eb6796013e3f322b4409c83a5ce6933b3bed2a66)), TransactionOutput(547 sats,pkh(a37da29fb9cc3032213440dfeef4dbfd5127d8c5)), TransactionOutput(547 sats,pkh(bea7d433934b2234d5e02ab12e2609b5f1547f38)), TransactionOutput(547 sats,pkh(bc34b4978ce51bcab9e2bea4b4b2d3e7aaeffc47)), TransactionOutput(547 sats,wpkh(74287528d9d261390b2e4612cdc27f82b1daf928)), TransactionOutput(547 sats,wpkh(e68846d818f5f2367dcbbdeed01ae7e62ed881dd)), TransactionOutput(547 sats,sh(3aa4e97541e63d6fb615230db3b9790467d9404e)), TransactionOutput(547 sats,pkh(d161fd65bc8950ae8e758d7caf4bb01f7589ed7a)), TransactionOutput(547 sats,sh(865411c372bd22308ae7e49ac9a73ddf4524ac08)), TransactionOutput(547 sats,pkh(733eb148bef61d63d544f9e1f134bc28c7136223)), TransactionOutput(547 sats,sh(aae06c64efa23a13dfeb1ecaed7c5442304e59f7)), TransactionOutput(547 sats,pkh(c4b39d67f1063f2b40d93ac7a3c32aeff0d06739)), TransactionOutput(547 sats,sh(b4aacc86b0d171d0daeed1e973bfd84efffbd947)), TransactionOutput(547 sats,sh(bca4fca5751781fe4b217b495369494b09705329)), TransactionOutput(547 sats,sh(7c31eb5516ca6be732d4d665993234453e555b90)), TransactionOutput(547 sats,pkh(23a5f2901e4291616689c645b86c3f2834b035de)), TransactionOutput(547 sats,pkh(4cdf897e8471c4b26128a7586dd1712f58583632)), TransactionOutput(547 sats,pkh(8b9f659dc9063387dea0b4b2125caffcb19f52c9)), TransactionOutput(547 sats,sh(de64339689cffd9954e82650bdc7489899c1c77c)), TransactionOutput(547 sats,pkh(2c3034477226c953c7bfdf37a57b5ef72d845773)), TransactionOutput(547 sats,pkh(1b980ccb350e958513cac7031c2f8d037bd3d33d)), TransactionOutput(547 sats,pkh(ca470e9456e7fcfd3282b8e5547db71067584c23)), TransactionOutput(547 sats,sh(7493cecc87c3e1512aa502791cadc858527cfd60)), TransactionOutput(547 sats,pkh(8b9d038965ef40cdf6b2179d24a737f8f0fc64d4)), TransactionOutput(547 sats,sh(0904f1a65a1671e9718224c90bcdd4d981ed13e6)), TransactionOutput(547 sats,sh(a0d0cb1362e3367331f413d4e95dda33bf59ffe2)), TransactionOutput(547 sats,sh(b541f609756fb144f5d87b87a515563c5185ed4c)), TransactionOutput(547 sats,wpkh(76de53781da21c28b854714030f60655c01936da)), TransactionOutput(547 sats,pkh(553360efb4f1337a304d833c006f65625580e9d6)), TransactionOutput(547 sats,wpkh(24eb2b58976164272055c5d8e33e134b63ff3af4)), TransactionOutput(547 sats,pkh(7796681441c9f2eb826398a10afce0240a499cdd)), TransactionOutput(547 sats,sh(ed1a54faf310f0fa3fe041219006ededc3e2b090)), TransactionOutput(547 sats,wpkh(c4976d206da3995694b1743d621db3aff3a3f491)), TransactionOutput(547 sats,sh(3da99fcef5e7da440530ee7bc0a29428d60d08dd)), TransactionOutput(547 sats,sh(6b2b5a9544bbc70f5255653167c83d589dd6983b)), TransactionOutput(547 sats,sh(b57dad25d82428ddf3d702f8866fa268955a508a)), TransactionOutput(547 sats,pkh(bba81549f149741e79ef1719150b0d52a0335383)), TransactionOutput(547 sats,sh(b7e6eeddb7a17c62137f758859854124eccb2d2e)), TransactionOutput(547 sats,sh(d4913822e89c430ce31449c024bddb5b6ba72106)), TransactionOutput(547 sats,pkh(d26bb7c6fd5d39ab76c32abb956f65333659662a)), TransactionOutput(547 sats,pkh(033ebd5d7114934ec871224ee4a9f3c034057721)), TransactionOutput(547 sats,sh(74c7b5d931b78c817d32e63f4f660f455a186c52)), TransactionOutput(547 sats,wpkh(1ccbee5d78e1ceadd1747fa1f9e2076af14cf3e7)), TransactionOutput(547 sats,pkh(79cdb818be5c72840a57c43db7a68f897ed2d5ec)), TransactionOutput(547 sats,wpkh(9807d8d45c60fd36c5a5f89da84be86061fd8037)), TransactionOutput(547 sats,sh(8d4e2d8bb92aaff70aa6755163515e5ccc6882b9)), TransactionOutput(547 sats,sh(dda395967c5998540994f26536caf5ff778924f4)), TransactionOutput(547 sats,pkh(8fc1ff6e256e7560e3a8f59f92b90d8cbb33031f)), TransactionOutput(547 sats,sh(b9b8a32c2d9a660efec10adee18a447422a93f78)), TransactionOutput(547 sats,pkh(90f7fec9b9d1f8e00a03536a9efe8e7327cf48e2)), TransactionOutput(547 sats,sh(1cab5f8200e1a801a70121fc4bec08a7faaed2b9)), TransactionOutput(547 sats,sh(198d0d8e324460dbde2eee90279708ddee1871f5)), TransactionOutput(547 sats,wpkh(a98c87a6a076b86a289e504873d6edb005e73163)), TransactionOutput(547 sats,sh(3ab083e70d63ab931417b7257995c336847a5ef7)), TransactionOutput(547 sats,wpkh(28a5f68c4e39b007619fd0b7b45fff5608c3f136)), TransactionOutput(547 sats,pkh(e4200fab7e35453f5d98fb65467e9121fb1490d8)), TransactionOutput(547 sats,sh(84ed2020d76a13e7a030073060ae412f9807a932)), TransactionOutput(547 sats,wpkh(02cd78d3ec050ed4f06e73aa392ae5cf38f26b95)), TransactionOutput(547 sats,sh(eabfcd9efe02602e151bc2b991b9eaf8f8590088)), TransactionOutput(547 sats,sh(8b6065dab8302532a12aafa0b830ab2bdb42a714)), TransactionOutput(547 sats,sh(32b7183734429b0aa45ab965d96959d128d8f59e)), TransactionOutput(547 sats,wpkh(a0e9c227e3ca350209011eb658196a678cfdbab1)), TransactionOutput(108944145 sats,wpkh(718eb14c8b2a915f38eb48827d36dc19efd68c65))),UInt32Impl(685682),IndexedSeq(P2WPKHWitnessV0(List(022ee8e970385fc312ae22d41e89a34e567cfffd3c5ff072853616cea7b122712a, 304402204a0633b56f90119ed2b3bc3284eb5ea45ae018659fc8e8b0ea3e2a369692575c02204b48d99955ecc928823c0c4f32ad3ab8b5a90b07e4bc7a9a2efef99e593a46b201)))),UInt32Impl(105),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(14643378057465566172),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(0e0554dd38d747f80c36b45cce605e420267314c1d75918f4ae2557f2951d808:2),EmptyScriptSignature,UInt32Impl(4294967294))),Vector(TransactionOutput(36435 sats,wpkh(b70b54c77a527367690435f0539728b06b548e0a)), TransactionOutput(63565 sats,wpkh(f0c60aa568b9891c1e35b6c4f0a93467ee6879d1))),UInt32Impl(0),IndexedSeq(P2WSHWitnessV0(List(5221027dd53ed71a0b2aaab63b43ab431518612ee78759863c8c497ce892aad2c519c72102988c5671f42149973f3cfde0dfd4693123d9daa7dc187acc07669a72c7fddfdf52ae, 304402205d9351c8e980081e9b330a082d73106edc63b7661c8d09a55010eeb4cdd760b50220045b95ee2a3e380dc07b8bf2c2fc57c77328346617ea781eff80d13b81aab38701, 3045022100b2246d051596c73d1fbb17c8388e56cddcdf77debcc83b2b0bcf358ee5533d550220305a7e6163bc15ecbc1058000d2a38d2d872c94702338646cf97f8394bd0ae0901, )))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(1519065859901246733),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(4837a5703d363c6c91b735fc968d401a362cd0f1fe4e827bf21124cf3e159bbe:1),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(0e0554dd38d747f80c36b45cce605e420267314c1d75918f4ae2557f2951d808:0),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(3035 sats,wpkh(032f4c093ad59c5a2ebb7ce447835205f5ecb5b5)), TransactionOutput(109021 sats,wpkh(84d781502709f5cd296f05f961970a75d5cc033f)), TransactionOutput(100170 sats,wsh(7b6a4bc0229307b69bc980c3759087b45e87f8a23b376a4bc3358376d66d4233))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(024e32511e6deb8b3c1d603fd32657a18a5432e320ca460ca6510a2f15f891f504, 304402201602fe767e6ff0ad2e08287f6bb5455d1d4423863b09a3b9a24bed05370a2d3c022008a09c9bd71e0a64813229c0f048e39f6b2eb6d4677fe102574a6e64998c1f4201)), P2WPKHWitnessV0(List(03bb58041bc35c823ca2bb95f39191c1238a2d766a44187e5bcbfb1d2b2de8110f, 304402201703d4ae617170e9cc5edb57a071b664ab8c174d1b222ad584276fe7bb1f86c802200d72db38ae4bf277e321287dfbd3db58d8c8cbd40d4b7cb22f05c980f31e468901)))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(10266876976437113133),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(a31dfc6f20335600f22374acdc8a9ffcddb6798a89281d277f2b2d2710a22ec0:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(bef88d690bcd8e0ac36e3cba26b2007698b9a367545d5e7645d8d106d6c0f27f:1),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(bc160e2092f93c5b3e977b453619fb8e92f6b16fb59ee7558f5884e87842afda:2),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(45119ac13f6b7f468f9814075922c200e194b186dd20ab5fe1ddc95259337702:2),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(501859 sats,wpkh(79a73b0cc447fb8871234f2dcea4a0d5e14cb24f)), TransactionOutput(100170 sats,wsh(ebe2327de660ea626643166b7115b46fd4837abd29aa35f26ccad978a21c5a83)), TransactionOutput(10667 sats,wpkh(e7e2dab5dbc6fa35e60881802ef5e23fc4a92f51))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(0318d993063b1e3ff2f6b1383ee84cefb9f3b2200bc7e1b21dfd347397e5ba81de, 304402203187cad08f8e82d1c79fb6f377133955d4ee8034f4ef34e96f1a70ce90854b4702200ad2d209d4ba48fe2574e1b475d6414a3419cad8c3d2a119f9afa7936962a18a01)), P2WPKHWitnessV0(List(03c6b078bcae1001267c41fb90d63b276f81b8383b6fad453de595807219c557bb, 30440220052c2a7720f9012b2442ee4a24f70bd285909563d7aed64a89725b4d221c4bbe02207cc4bf4d61b99b79aeabc759f7cff9da5d1b9b69c2ac65e9806f4a18a9cc8cae01)), P2WPKHWitnessV0(List(03c77e544b1a37b1bc1ff32718af6ab51d77b5fe84f208726497c7cb7bbe1542f8, 3044022035fc2f9905e265f42e5758596c474478be4931cbb719eed517160ca3fef1e5bb0220388a10045e0648d17c45e35784c3a7e7d642b29e45a63e01c60c8ff6dc63e2b701)), P2WPKHWitnessV0(List(03948ee3a77567e69315406972df6772de23951f9c36842dad063de2b03fa11083, 304402206a1494acd00d88524428e7cfbee088b1af1f173e50504b08eb0a200ab83abdf8022064bd678d8b5b4b038f697d31428154dd9261949d7df46ef4b0a0900c2cf2568901)))),UInt32Impl(2),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(3489947806068236891),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(180fc0bfaff3e2f37f123445a7ae74e97fef50113a27c91d9ed0e0b4b2797633:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(7b6eed6b2f4e9bc2ff2694ed8c0927ac409b6d33ecdc3c63dc5dd3bec69617f2:0),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(5953 sats,wpkh(f86785b71f4f44530c009a2f14e8109927733890)), TransactionOutput(48523 sats,wpkh(c184e92bb428b8d4bbf4f68c82658af2ffe4c2e7)), TransactionOutput(101190 sats,wsh(5264e3d65636e96af8278bbc3e964df04537174dfa47ddef15181e4f1ede435d))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(03d2db9a7d22de629c9ef42a4462beba442498ad12055e04cda81b95e85bc0c81e, 30440220212adcbc93e17dbd89be31a6bb8b7a079cbee3dee2d231eb3705f6ded5c2f27e0220070cd559e65af8c398058b91054c434d0ddb51db95b0cef35398dc4f582f0eb301)), P2WPKHWitnessV0(List(024d3e8c14423c04ef79c0be7ca8f1ad0088aec25c41a82c116189081e54c992a2, 304402204c3b6fe56eb1de8d8ea51fc174910fdeb499fe103a07df333972aa4fe54c5f7f022068fa57e54ec8eec939f7f0544a047a3d2e1d3d73de573a238c29cf2001470da401)))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(13487705597432644691),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(96155d9164a6b8e4d75769b72c21761e2f235b892ef13e3d315aefae3bf18a36:1),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(0d5fb7a4c9c8bc02869289745b8a07a43d0588613353bc0a5d36e23af44eecfa:0),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(2831 sats,wpkh(107eb2463ad25843ed01fd33656c83bdd11db355)), TransactionOutput(100170 sats,wsh(02265c41f299b3c7f0dda5b9d7bc4135d25c2d8aed286837aa9e0954d70894d6)), TransactionOutput(1873414 sats,wpkh(82a7ecd4624e6856d1b09c27e9f3a82323f49c2d))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(03cd2d0a4eace5993ebb0a75da85d9070627e64f1a5783cf5217e9bd82d20d1c47, 304402200911162e99e23e4a26e0219a4bdaaf7a5f790be63a8376516640dcc0860ca4d602203a078371904842e2e6adfbebebcac138db23514b3396851569f5f2bf82c3197a01)), P2WPKHWitnessV0(List(03d3864eb755690e2b4ff139047419373e36a05630429da76fef5de25eeffb4ffc, 304402200fa8515323410ca2b14b08bf22c618b6ced77b9289cb1dfa7ac10548e2e1b2e002206a407bcafdfb64009182fb5838db9671968abdd902e1194f6883cd0e5413ad3601)))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(14128290805772080321),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(47a1a93d0524b867c8e35f16aad900f80ee65a69962d94480c5facc256492f98:1),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(647f5432b2a785bd9151e68c41a91d319b9c8337787e4975047822ef8ed38cb3:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(e2b17e228252065f5ad79fad346de2582d05f3d7d95e1f3d5395f44cdeef6668:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(ccc20d8d8c5d1969216810af466ce915ecf26a91d89eaa95346fac4306a91402:0),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(12358 sats,wpkh(48ba92affa20e46dc7c2fcec746080889ac78492)), TransactionOutput(100850 sats,wsh(d40ec2fa1e8c00f97d4d96bc5a60a6d397f62fd23eb326fd2461f3d5848865cd)), TransactionOutput(447890 sats,wpkh(2a464d0d10fca3e53b49bcaf307eaefdfd59d716))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(02dad6c5f135b9a9a5ee9f0d5a828760373696c686ce3d6047ed37e2bd6c7c6020, 304402206e83824012ce95e09469173de716dc3881fcae5fb9711aa05c5df7fdb5054f60022072c4a46ad50b5ebd611778805577419601cbcf90cf42a65a6f36e51d2a93777101)), P2WPKHWitnessV0(List(03911309104575a84aad2a36d35033e172c6bfd3a195649074c96ff24864377dcd, 304402206dc3a95bf2ebf3051e177bd37fa30df8293ad4e3d74d1b9c0c864c58adeb422c02200f60a8bd667f34f4467b0532361816ae398cc4f48d5bebe76cc8df00cc9eb9fa01)), P2WPKHWitnessV0(List(0348d08290108093b047047a6f18f1562fe6bfa3b2104f4a77a0dee27b22dbf450, 304402205b0119225eaf2b127203bb6fc2072695a6f19bcefb91172c4e486320c72c590c02202af0b2d8b1b82f5241cd906fcf9f7575eb2f9a3d13368d38540b1974e5d5de3b01)), P2WPKHWitnessV0(List(02946459bf02d94a6014499a9c357fe2bcb1e02367b3b323f1207315dd9b3e956c, 30440220783688959deb6aac94ebe639b294237955742cc6c4c95fa4b65a441851c32b890220672c0819b35101c0e331b6770468f38f85d4620befb869bacbaf12fb909018b901)))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(7949566791666683479),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(d72ef6f76c6594eab343103952a71bc21bd8469ef9be581f2952bf533fcbcc86:0),EmptyScriptSignature,UInt32Impl(0)), TransactionInputImpl(TransactionOutPoint(33e076556557d8101e4c497039d06ba8d1e6a08c89c9e65b2161389bf11f48bd:0),EmptyScriptSignature,UInt32Impl(0))),Vector(TransactionOutput(14195 sats,wpkh(e60ce491b7f7a548ed6d6b8ca88d47ad398bdfed)), TransactionOutput(75000 sats,wpkh(5ee7fa05b91109e8098906ee34ecfebd2dfb24b5))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(0304e5ecdd25c310458d4b8f313b37593f6a6524dd26ae571a13c6ba3f2939c6ee, 3044022067095f1e06b2d860d34cccfdcb7dde62d963f2c3ad004785e329b66ee782cc3102202c1b4a9705ed043ded2f413407d1000eefd8cd6222a43d59387bda8c1ca0450801)), P2WPKHWitnessV0(List(02856d51b4715d6e271a0099b16e7db0f8fec3229c00633564a0cdc5569fd708b8, 304402207bc0328ac59719ac05b8a170eda77746dadf55af84302b03073c608af42f40ee0220212f9e71fe42eb364aa21d2c86a0e87235f3d40d505dae7d2b3f819ea8688df401)))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None)),wpkh(1e9b40ba13d526b9a194d9a72092e2b31dfff439),UInt64Impl(2213912330987628648),UInt64Impl(4340683412601391854),5 sats/vbyte,BlockHeight(0),BlockTime(UInt32Impl(1638230400)))) WARNING arguments left: 1
2021-11-22T17:17:02UTC INFO [DataMessageHandler] Received headers message with 1 headers
2021-11-22T17:17:02UTC INFO [DataMessageHandler] Starting to fetch filter headers in data message handler
2021-11-22T17:17:03UTC INFO [DataMessageHandler] Got 1 compact filter header hashes
2021-11-22T17:17:03UTC INFO [DataMessageHandler] Done syncing filter headers, beginning to sync filters in datamessagehandler
2021-11-22T17:17:03UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=710862, stopBlockHash=000000000000000000032db4eb79f1540c19a64c70c0519c67b250872dbea79d)
2021-11-22T17:17:04UTC INFO [DataMessageHandler] We are synced
2021-11-22T17:17:04UTC INFO [DataMessageHandler] Processing 1 filters

_Originally posted by @Christewart in https://github.com/bitcoin-s/bitcoin-s/issues/3839#issuecomment-975748706_

### PR DESCRIPTION
**Pull request by Christewart**
This PR begins exposing database actions in our `CRUD` trait. There is now a super trait called `CRUDAction`, and has two methods on it `createAllAction`/`createAction`/`deleteAction`/`deleteAllAction`. I'm not going to implement `upsert`/`upsertAll` on this PR.

For more information on how `DBIOAction` please see this slick documentation: https://scala-slick.org/doc/3.3.3/dbio.html

This PR begins to fix #3844 / #3846 / #3119

### CODE REVIEW

File: dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala [hunk 1]
```diff
@@ -429,11 +428,21 @@ abstract class DLCWallet
...
+        dlcAnnouncementDbs)
+      inputsAction = dlcInputsDAO.createAllAction(dlcInputs)
+      offerAction = dlcOfferDAO.createAction(dlcOfferDb)
+      actions = Vector(globalAction,
+                       contractAction,
+                       announcementAction,
+                       inputsAction,
+                       offerAction)
+      allActions = DBIO.sequence(actions)
+      _ <- safeDatabase.run(allActions)
```
Comment (benthecarman) [inline dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala]: Maybe should make a `DLCDbActionManager` (or a better name) trait that contains all the long strings of actions

Comment (Christewart) [reply dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala]: I'm not sure if I understand, I can see a helper method to reduce clutter but i think this action is contextual to `createDLCOffer()`? Is this used else where too?

Comment (benthecarman) [reply dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala]: Yeah mostly to reduce clutter
