### PR TITLE
Wallet integration for nested segwit v0 spending

### LINKED ISSUE #1266: Implement nested segwit
```bashrc
./bitcoin-s-cli getnewaddress
Request failed: Nested segwit is not implemented yet!
```

You should be able to replicate this by changing 

```
  bitcoin-s.wallet.defaultAccountType = nested-segwit # legacy, segwit, nested-segwit
```

in your `bitcoin-s.conf`

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #1266

### CODE REVIEW

File: wallet/src/main/scala/org/bitcoins/wallet/models/SpendingInfoTable.scala [hunk 1]
```diff
@@ -80,7 +89,39 @@ case class LegacySpendingInfo(
...
+  */
+case class NestedSegwitV0SpendingInfo(
+    outPoint: TransactionOutPoint,
+    output: TransactionOutput,
+    privKeyPath: NestedSegWitHDPath,
+    redeemScript: ScriptPubKey,
+    scriptWitness: ScriptWitness,
+    txid: DoubleSha256DigestBE,
+    state: TxoState,
+    id: Option[Long] = None,
```
Comment (nkohen) [inline wallet/src/main/scala/org/bitcoins/wallet/models/SpendingInfoTable.scala]: nit: If you move `id` down one then you won't have to mention it when using `None`

**Review by nkohen — COMMENTED** [review]
Just one small nit, lgtm otherwise
