### PR TITLE
Fix bug where postgres tests weren't running on `dlcWalletTest/test`

### LINKED ISSUE #4800: Postgres database not being used with `dlcWalletTest/test` when `PG_ENABLED=1`
Here is an example on 2a0cb57cf187245c954f9cb952cf603d1cf06cc1 when running 

```
dlcWalletTest/testOnly *DLCDataManagement* -- -z "retrieve a acceptdb state from getDLCFundingData"
```

When you look carefully at these logs, you see that sqlite migrations are getting run rather than postgres migrations. 

```
2022-09-24 14:42:47,345 INFO [KeyManagerAppConfig] No seed file found at=/var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-17674824775041648432/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:47,346 INFO [KeyManagerAppConfig] Initializing new mnemonic seed at path=/var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-17674824775041648432/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:47,352 INFO [BIP39KeyManager$] Initializing wallet with seedPath=/var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-17674824775041648432/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:47,353 INFO [BIP39KeyManager$] Seed path parent directory does not exist, creating /var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-17674824775041648432/seeds
2022-09-24 14:42:47,365 INFO [BIP39KeyManager$] Created mnemonic from entropy
2022-09-24 14:42:47,374 INFO [WalletStorage$] Writing seed to /var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-17674824775041648432/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:47,377 INFO [BIP39KeyManager$] Saved wallet mnemonic to /var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-17674824775041648432/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:47,411 INFO [BIP39KeyManager$] Successfully initialized wallet
2022-09-24 14:42:47,416 INFO [KeyManagerAppConfig] Successfully initialize seed at path with root xpub=vpub5SLqN2bLY4WeZiUid8XcPdToHhpB4zzAeRNcKXtXkBCYTxDY9BfUqLPrqN2thFCECLtMSbKSeibhMhddarjcZR4Q5UEkzBQLC5dsq3JjZTx
2022-09-24 14:42:47,598 INFO [VersionPrinter] Flyway Community Edition 9.2.1 by Redgate
2022-09-24 14:42:47,599 INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.2.1
2022-09-24 14:42:47,599 INFO [VersionPrinter] 
2022-09-24 14:42:47,608 INFO [BaseDatabaseType] Database: jdbc:sqlite:/var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-17674824775041648432/regtest/walletdb.sqlite (SQLite 3.39)
2022-09-24 14:42:47,626 INFO [DbValidate] Successfully validated 16 migrations (execution time 00:00.010s)
2022-09-24 14:42:47,628 INFO [JdbcTableSchemaHistory] Creating Schema History table "main"."flyway_schema_history" ...
2022-09-24 14:42:47,636 INFO [DbMigrate] Current version of schema "main": << Empty Schema >>
2022-09-24 14:42:47,640 INFO [DbMigrate] Migrating schema "main" to version "1 - wallet db baseline"
2022-09-24 14:42:47,645 INFO [DbMigrate] Migrating schema "main" to version "2 - wallet db spent to txo state"
2022-09-24 14:42:47,648 INFO [DbMigrate] Migrating schema "main" to version "3 - txo spending info drop confirmations"
2022-09-24 14:42:47,651 INFO [DbMigrate] Migrating schema "main" to version "4 - wallet db add transaction table"
2022-09-24 14:42:47,654 INFO [DbMigrate] Migrating schema "main" to version "5 - add address tags"
2022-09-24 14:42:47,655 INFO [DbMigrate] Migrating schema "main" to version "6 - unique spendinginfodb outpoint"
2022-09-24 14:42:47,658 INFO [DbMigrate] Migrating schema "main" to version "7 - add address tag pk"
2022-09-24 14:42:47,661 INFO [DbMigrate] Migrating schema "main" to version "8 - add script pub keys"
2022-09-24 14:42:47,664 INFO [DbMigrate] Migrating schema "main" to version "9 - state descriptor table"
2022-09-24 14:42:47,666 INFO [DbMigrate] Migrating schema "main" to version "10 - blockhash to transaction table"
2022-09-24 14:42:47,668 INFO [DbMigrate] Migrating schema "main" to version "11 - master xpub"
2022-09-24 14:42:47,669 INFO [DbMigrate] Migrating schema "main" to version "12 - add oracle name"
2022-09-24 14:42:47,671 INFO [DbMigrate] Migrating schema "main" to version "13 - add scriptpubkey hash"
2022-09-24 14:42:47,673 INFO [DbMigrate] Migrating schema "main" to version "14 - compute spk hashes"
2022-09-24 14:42:47,676 INFO [DbMigrate] Migrating schema "main" to version "15 - add tag name constraint"
2022-09-24 14:42:47,677 INFO [DbMigrate] Migrating schema "main" to version "16 - unique spendinginfodb outpoint"
2022-09-24 14:42:47,678 INFO [DbMigrate] Successfully applied 16 migrations to schema "main", now at version v16 (execution time 00:00.043s)
2022-09-24 14:42:47,767 INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
2022-09-24 14:42:47,772 INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
2022-09-24 14:42:47,832 INFO [BaseDatabaseType] Database: jdbc:sqlite:/var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-17674824775041648432/regtest/dlcdb.sqlite (SQLite 3.39)
2022-09-24 14:42:47,838 INFO [DbValidate] Successfully validated 8 migrations (execution time 00:00.000s)
2022-09-24 14:42:47,838 INFO [JdbcTableSchemaHistory] Creating Schema History table "main"."flyway_schema_history" ...
2022-09-24 14:42:47,839 INFO [DbMigrate] Current version of schema "main": << Empty Schema >>
2022-09-24 14:42:47,841 INFO [DbMigrate] Migrating schema "main" to version "1 - dlc db baseline"
2022-09-24 14:42:47,843 INFO [DbMigrate] Migrating schema "main" to version "2 - add funding input sequence"
2022-09-24 14:42:47,844 INFO [DbMigrate] Migrating schema "main" to version "3 - last updated col"
2022-09-24 14:42:47,845 INFO [DbMigrate] Migrating schema "main" to version "4 - index col funding input"
2022-09-24 14:42:47,846 INFO [DbMigrate] Migrating schema "main" to version "5 - serialization version global dlc data"
2022-09-24 14:42:47,847 INFO [DbMigrate] Migrating schema "main" to version "6 - create incoming offers"
2022-09-24 14:42:47,848 INFO [DbMigrate] Migrating schema "main" to version "7 - create contacts"
2022-09-24 14:42:47,849 INFO [DbMigrate] Migrating schema "main" to version "8 - contact global dlc data"
2022-09-24 14:42:47,850 INFO [DbMigrate] Successfully applied 8 migrations to schema "main", now at version v8 (execution time 00:00.011s)
2022-09-24 14:42:47,851 INFO [DLCAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@77caaa2c to the dlc project
2022-09-24 14:42:48,010 INFO [Wallet$] Created account=AccountDb(tpubDCnYTsdEk9YKWR5m81GdPVayvkm4pknhkysauyKJyfhXiawbDC3xyQxE5Zcx7Urn6ZZBa84exSuoPQLitoadXEy62ThjHs64JRyps4dCqqJ,m/44'/1'/0') to DB
2022-09-24 14:42:48,011 INFO [Wallet$] Created account=AccountDb(vpub5ZnajhewAdr6XBWqKdKJ2NphGN1ewXFkeqod6CvvmEcYqqcHNKQf6F5D1RuiFTmeAvhWmvkybExYPERUMtCdLHwsHF1VNrBwf5WPfj5csko,m/84'/1'/0') to DB
2022-09-24 14:42:48,011 INFO [Wallet$] Created account=AccountDb(upub5EPd47sgzK7TR568tbC4T18orrdg85E8brK92gHXiJrzBUPQsF33NqeGuwubtVDUD3LTCTKnSgqtAFayGHx7cCL3QuJZ8FCBajzbmy2rrCv,m/49'/1'/0') to DB
2022-09-24 14:42:48,020 INFO [DLCWallet$DLCWalletImpl] Creating new account at index 1 for purpose m/84'
2022-09-24 14:42:48,124 INFO [DLCWallet$DLCWalletImpl] Generated new address=bcrt1q8mm3alaf3a8dvmjnxvu3cat72sun8xnqhyes3v path=m/84'/1'/0'/0/0 isChange=false
2022-09-24 14:42:48,142 INFO [DLCWallet$DLCWalletImpl] Generated new address=bcrt1qcgjwuxg3uysjz00hghx0j53umwvm5kgnwfyfyl path=m/84'/1'/0'/0/1 isChange=false
2022-09-24 14:42:48,168 INFO [DLCWallet$DLCWalletImpl] Generated new address=bcrt1q8zgagvh6w6rjhdt327l3vcscm3fcecdtwd0pyh path=m/84'/1'/0'/0/2 isChange=false
2022-09-24 14:42:48,247 INFO [HikariDataSource] bitcoin-s.dlc.db - Starting...
2022-09-24 14:42:48,247 INFO [HikariDataSource] bitcoin-s.dlc.db - Start completed.
2022-09-24 14:42:48,321 INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO e8d91cb28beebcd3f91faefef7a874a2f882c5d68cf71feb056aa3d89eb0ff4e:0 amt=100000000 sats into DB
2022-09-24 14:42:48,332 INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, balance=100000000 sats it took=93ms
2022-09-24 14:42:48,342 INFO [DLCWallet$DLCWalletImpl] Finished processing of transaction=e8d91cb28beebcd3f91faefef7a874a2f882c5d68cf71feb056aa3d89eb0ff4e. Relevant incomingTXOs=1, outgoingTXOs=0
2022-09-24 14:42:48,394 INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 395089537794582bf0eea33d2e9bda900e55e832758976e09564020038b5d8a8:0 amt=200000000 sats into DB
2022-09-24 14:42:48,396 INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, balance=200000000 sats it took=39ms
2022-09-24 14:42:48,399 INFO [DLCWallet$DLCWalletImpl] Finished processing of transaction=395089537794582bf0eea33d2e9bda900e55e832758976e09564020038b5d8a8. Relevant incomingTXOs=1, outgoingTXOs=0
2022-09-24 14:42:48,431 INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 8aa661fd1dac77378b85ee4a316f044473362440c846e7359502598504667cc9:0 amt=300000000 sats into DB
2022-09-24 14:42:48,433 INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, balance=300000000 sats it took=27ms
2022-09-24 14:42:48,435 INFO [DLCWallet$DLCWalletImpl] Finished processing of transaction=8aa661fd1dac77378b85ee4a316f044473362440c846e7359502598504667cc9. Relevant incomingTXOs=1, outgoingTXOs=0
2022-09-24 14:42:48,466 INFO [DLCWallet$DLCWalletImpl] Generated new address=bcrt1qmwh6d7f8zukr4fvgvdnv83dlwztuk3u8hl9s7v path=m/84'/1'/1'/0/0 isChange=false
2022-09-24 14:42:48,497 INFO [DLCWallet$DLCWalletImpl] Generated new address=bcrt1qd0rsxfqedjkvszkraujkh8yqxf6mvt6kjjexnd path=m/84'/1'/1'/0/1 isChange=false
2022-09-24 14:42:48,511 INFO [DLCWallet$DLCWalletImpl] Generated new address=bcrt1qgeeluh2xhrzvufzk403aqjl5akjaxsxxxff9xn path=m/84'/1'/1'/0/2 isChange=false
2022-09-24 14:42:48,579 INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 4bddf09380de0c9a6181588551ff591e1a4d77f5e7fe87bc830da1f4a2ee4d1b:0 amt=20000000 sats into DB
2022-09-24 14:42:48,582 INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, balance=20000000 sats it took=54ms
2022-09-24 14:42:48,586 INFO [DLCWallet$DLCWalletImpl] Finished processing of transaction=4bddf09380de0c9a6181588551ff591e1a4d77f5e7fe87bc830da1f4a2ee4d1b. Relevant incomingTXOs=1, outgoingTXOs=0
2022-09-24 14:42:48,633 INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 841d4706c115ba2949ca801fc68a98eaa6e968089f06dcf319b8d0ac9eb2e4ca:0 amt=30000000 sats into DB
2022-09-24 14:42:48,635 INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, balance=30000000 sats it took=40ms
2022-09-24 14:42:48,641 INFO [DLCWallet$DLCWalletImpl] Finished processing of transaction=841d4706c115ba2949ca801fc68a98eaa6e968089f06dcf319b8d0ac9eb2e4ca. Relevant incomingTXOs=1, outgoingTXOs=0
2022-09-24 14:42:48,691 INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 9f091c34fe17510518145bf6892b357af2390ac60cf1b19088f2b778907738c5:0 amt=50000000 sats into DB
2022-09-24 14:42:48,694 INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, balance=50000000 sats it took=45ms
2022-09-24 14:42:48,699 INFO [DLCWallet$DLCWalletImpl] Finished processing of transaction=9f091c34fe17510518145bf6892b357af2390ac60cf1b19088f2b778907738c5. Relevant incomingTXOs=1, outgoingTXOs=0
2022-09-24 14:42:48,769 INFO [KeyManagerAppConfig] No seed file found at=/var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-12901904128733402851/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:48,770 INFO [KeyManagerAppConfig] Initializing new mnemonic seed at path=/var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-12901904128733402851/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:48,770 INFO [BIP39KeyManager$] Initializing wallet with seedPath=/var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-12901904128733402851/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:48,770 INFO [BIP39KeyManager$] Seed path parent directory does not exist, creating /var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-12901904128733402851/seeds
2022-09-24 14:42:48,771 INFO [BIP39KeyManager$] Created mnemonic from entropy
2022-09-24 14:42:48,771 INFO [WalletStorage$] Writing seed to /var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-12901904128733402851/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:48,772 INFO [BIP39KeyManager$] Saved wallet mnemonic to /var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-12901904128733402851/seeds/encrypted-bitcoin-s-seed.json
2022-09-24 14:42:48,781 INFO [BIP39KeyManager$] Successfully initialized wallet
2022-09-24 14:42:48,782 INFO [KeyManagerAppConfig] Successfully initialize seed at path with root xpub=vpub5SLqN2bLY4WeZKCSvm2mx1CbgcGg3rHYiLcYsB7gTFGxu7dtGWAogey8DtVRhMJ1PVu6XZAogWbFcr3K5PTQBpZY2optfiM6sHvEVC1j8ui
2022-09-24 14:42:48,798 INFO [BaseDatabaseType] Database: jdbc:sqlite:/var/folders/fg/scntn26d4h55x96zc456l0r40000gn/T/bitcoin-s-12901904128733402851/regtest/walletdb.sqlite (SQLite 3.39)
2022-09-24 14:42:48,800 INFO [DbValidate] Successfully validated 16 migrations (execution time 00:00.001s)
2022-09-24 14:42:48,801 INFO [JdbcTableSchemaHistory] Creating Schema History table "main"."flyway_schema_history" ...
2022-09-24 14:42:48,802 INFO [DbMigrate] Current version of schema "main": << Empty Schema >>
2022-09-24 14:42:48,803 INFO [DbMigrate] Migrating schema "main" to version "1 - wallet db baseline"
2022-09-24 14:42:48,805 INFO [DbMigrate] Migrating schema "main" to version "2 - wallet db spent to txo state"
2022-09-24 14:42:48,809 INFO [DbMigrate] Migrating schema "main" to version "3 - txo spending info drop confirmations"
2022-09-24 14:42:48,812 INFO [DbMigrate] Migrating schema "main" to version "4 - wallet db add transaction table"
2022-09-24 14:42:48,814 INFO [DbMigrate] Migrating schema "main" to version "5 - add address tags"
2022-09-24 14:42:48,816 INFO [DbMigrate] Migrating schema "main" to version "6 - unique spendinginfodb outpoint"
2022-09-24 14:42:48,817 INFO [DbMigrate] Migrating schema "main" to version "7 - add address tag pk"
2022-09-24 14:42:48,820 INFO [DbMigrate] Migrating schema "main" to version "8 - add script pub keys"
```

### PR DESCRIPTION
**Pull request by Christewart**
fixes #4800

### CODE REVIEW

File: testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSDualWalletTest.scala [hunk 1]
```diff
@@ -26,7 +26,11 @@ trait BitcoinSDualWalletTest extends BitcoinSWalletTest {
   /** Wallet config with data directory set to user temp directory */
   override protected def getFreshConfig: BitcoinSAppConfig = {
     val segwitConfig = BaseWalletTest.segwitWalletConf
-    BitcoinSTestAppConfig.getNeutrinoTestConfig(segwitConfig)
+    val randomHex = ECPrivateKey.freshPrivateKey.bytes.toHex.take(8)
```
Comment (benthecarman) [inline testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSDualWalletTest.scala]: Instead of this it would be simpler to call CryptoUtil.randomBytes

File: dlc-wallet/src/main/resources/postgresql/dlc/migration/V1__dlc_db_baseline.sql [hunk 2]
```diff
@@ -137,7 +137,7 @@ CREATE TABLE "watch_only_tx_table"
     "unsignedTxIdBE" TEXT    NOT NULL,
     "unsignedTx"     TEXT    NOT NULL,
     "wTxIdBE"        TEXT,
-    "totalOutput"    INTEGER NOT NULL,
+    "totalOutput"    bigint NOT NULL,
```
Comment (benthecarman) [inline dlc-wallet/src/main/resources/postgresql/dlc/migration/V1__dlc_db_baseline.sql]: Can this be done in the v10 Migration
