### PR TITLE
Fix monitorInvoice unit test

### LINKED ISSUE #693: EclairRpcClientTest monitorInvoice unit test failing randomly on CI
https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/571510842#L1132

### PR DESCRIPTION
**Pull request by rorp**
Fixes https://github.com/bitcoin-s/bitcoin-s/issues/693

### CODE REVIEW

File: eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcClientTest.scala [hunk 1]
```diff
@@ -146,6 +136,8 @@ class EclairRpcClientTest extends BitcoinSAsyncTest {
     val hasRoute = () => {
       (for {
         c1 <- firstClientF
+        b <- bitcoindRpcClientF
+        _ <- b.getBlockCount
```
Comment (Christewart) [inline eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcClientTest.scala]: Can we get rid of these now?

File: eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcClientTest.scala [hunk 2]
```diff
@@ -774,15 +769,19 @@ class EclairRpcClientTest extends BitcoinSAsyncTest {
...
-        _ <- paidF
-        invoice <- invoiceF
+      val res = for {
+        bitcoind <- bitcoindRpcClientF
+        _ <- EclairRpcTestUtil.awaitEclairInSync(otherClient, bitcoind)
+        _ <- EclairRpcTestUtil.awaitEclairInSync(client, bitcoind)
+        invoice: LnInvoice <- otherClient.createInvoice("monitor an invoice",
+                                                        amt)
+        _ <- client.payInvoice(invoice)
         //CI is super slow... wait 2 minutes
```
Comment (Christewart) [inline eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcClientTest.scala]: I think this comment is out of date... it at least isn't 2 minutes anymore, right?

File: testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala [hunk 3]
```diff
@@ -635,6 +634,21 @@ trait EclairRpcTestUtil extends BitcoinSLogger {
     bitcoindRpc
   }
 
+  def clientInSync(client: EclairRpcClient, bitcoind: BitcoindRpcClient)(
```
Comment (Christewart) [inline testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala]: scaladoc please

Comment (Christewart) [reply testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala]: Can this method be private? IT seems to me that we want people using `awaitEclairInSync()`?

File: testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala [hunk 4]
```diff
@@ -635,6 +634,21 @@ trait EclairRpcTestUtil extends BitcoinSLogger {
...
+      implicit ec: ExecutionContext): Future[Boolean] =
+    for {
+      blockCount <- bitcoind.getBlockCount
+      info <- client.getInfo
+    } yield info.blockHeight == blockCount
+
+  def awaitEclairInSync(eclair: EclairRpcClient, bitcoind: BitcoindRpcClient)(
```
Comment (Christewart) [inline testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala:641]: scaladoc saying that 
```scala
/**
Returns a `Future` that is completed when both eclair and bitcoind have the same block height 
Fails the future if they are not sychronized within the given timeout. 
*/
```
