### PR TITLE
Send GetHeadersMessage using all of our cached headers to prevent reorgs from stalling node

### LINKED ISSUE #1739: No common ancestor found in the chain
**Describe the bug**
I received these error messages last night when trying to sync my compact block filters. It seems to have stopped all syncing operations. I'm guessing these are new block headers coming in on the testnet network?

It seems that we don't have headers to connect to for this headers message?

>HeadersMessage(CompactSizeUInt(4),000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3..00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)

Finally we fail with this exception

>org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: block_headers.hash)

Here is the full log:
```
2020-08-02T04:02:51 DEBUG [P2P] Parsed 1 message(s) from bytes: NetworkMessage(NetworkHeader(TestNet3,headers,UInt32Impl(325),ByteVector(4 bytes, 0xef003c20)), HeadersMessage(CompactSizeUInt(4),000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3..00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 DEBUG [P2P] Unaligned bytes after this: 0
2020-08-02T04:02:51 DEBUG [P2P] Received message=headers from peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333) state=Normal 
2020-08-02T04:02:51 INFO [P2P] Received headers message with 4 headers
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 ERROR [P2P] Error when processing headers message
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: block_headers.hash)
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.throwex(DB.java:987)
	at org.sqlite.core.DB.executeBatch(DB.java:812)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:72)
	at slick.jdbc.LoggingStatement.$anonfun$executeBatch$1(LoggingStatement.scala:114)
	at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:87)
	at slick.jdbc.LoggingStatement.executeBatch(LoggingStatement.scala:114)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-08-02T04:02:51 ERROR [P2P] Cannot send a message to our peer when we are not connected! payload=GetCompactFiltersMessage(Basic,UInt32Impl(1742875),DoubleSha256Digest(027340bf7219e5825273b4b59fb7bed001d86aef36ab5eadda19000000000000)) peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333)

```

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #1739 

There was a problem where if a node is stopped with it's chain tip being a one that is later reorged out it will not be able to continue syncing headers.

This happens because we request headers using a get headers message with hashes=`<current chain tip>` and stopHash=`<00000..0000>`. Since, our chain tip is reorged out we will receive the first 2000 block headers of the network.

Solution: Send more than just our tip in the `GetHeadersMessage` so other nodes can find our best tip in their best chain to send us headers.

Context: https://bitcoin.stackexchange.com/questions/98376/what-is-the-proper-way-to-handle-reorgs-when-fetching-headers

### CODE REVIEW

File: node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala [hunk 1]
```diff
@@ -59,7 +59,10 @@ case class NeutrinoNode(
       filterCount <- chainApi.getFilterCount
       peerMsgSender <- peerMsgSenderF
     } yield {
-      peerMsgSender.sendGetHeadersMessage(header.hashBE.flip)
+      // Get all of our cached headers in case of a reorg
+      val cachedHeaders =
```
Comment (Christewart) [inline node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala:63]: I don't think we want to send them all do we? Perhaps we want to sample at some exponentially increasing interval? i.e. 

current tip
2^0 
2^1 
2^2 
2^3 ....

until we run out of headers?

**Review by Christewart — CHANGES_REQUESTED** [review]
Ok here is what I get when running this: 
```
2020-08-05T12:44:42 INFO [P2P] Received headers message with 2000 headers
2020-08-05T12:44:42 DEBUG [chain-verification] Attempting to connect 2000 headers to 1 blockchains
2020-08-05T12:44:42 DEBUG [chain-verification] Attempting to add new tip=000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e with prevhash=000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3 to chain
2020-08-05T12:44:42 DEBUG [chain-verification] Attempting to add new tip=000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e with prevhash=000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3 to chain of 2027 headers
[ERROR] [08/05/2020 07:44:42.103] [bitcoin-s-akka.actor.internal-dispatcher-17] [akka://bitcoin-s/user/P2PClient$-1596631428444] requirement failed
java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:327)
        at org.bitcoins.chain.blockchain.BaseBlockChain.$init$(BaseBlockChain.scala:42)
        at org.bitcoins.chain.blockchain.Blockchain.<init>(Blockchain.scala:6)
        at org.bitcoins.chain.blockchain.Blockchain$.fromHeaders(Blockchain.scala:18)
        at org.bitcoins.chain.blockchain.Blockchain.compObjectfromHeaders(Blockchain.scala:10)
        at org.bitcoins.chain.blockchain.BaseBlockChain.$anonfun$fromHeader$1(BaseBlockChain.scala:61)
        at org.bitcoins.chain.blockchain.BaseBlockChain.$anonfun$fromHeader$1$adapted(BaseBlockChain.scala:60)
        at scala.Option.map(Option.scala:242)
        at org.bitcoins.chain.blockchain.BaseBlockChain.fromHeader(BaseBlockChain.scala:60)
        at org.bitcoins.chain.blockchain.BaseBlockChain.fromHeader$(BaseBlockChain.scala:58)
        at org.bitcoins.chain.blockchain.Blockchain.fromHeader(Blockchain.scala:6)
        at org.bitcoins.chain.blockchain.BaseBlockChain.fromValidHeader(BaseBlockChain.scala:69)
        at org.bitcoins.chain.blockchain.BaseBlockChain.fromValidHeader$(BaseBlockChain.scala:68)
        at org.bitcoins.chain.blockchain.Blockchain.fromValidHeader(Blockchain.scala:6)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.connectTip(BaseBlockChain.scala:122)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.connectTip$(BaseBlockChain.scala:103)
        at org.bitcoins.chain.blockchain.Blockchain$.connectTip(Blockchain.scala:14)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.$anonfun$connectHeadersToChains$3(BaseBlockChain.scala:175)
        at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
        at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
        at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.$anonfun$connectHeadersToChains$2(BaseBlockChain.scala:173)
        at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:638)
        at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:634)
        at scala.collection.AbstractIterable.foldLeft(Iterable.scala:920)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.connectHeadersToChains(BaseBlockChain.scala:171)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.connectHeadersToChains$(BaseBlockChain.scala:160)
        at org.bitcoins.chain.blockchain.Blockchain$.connectHeadersToChains(Blockchain.scala:14)
        at org.bitcoins.chain.blockchain.ChainHandler.processHeaders(ChainHandler.scala:103)
        at org.bitcoins.node.networking.peer.DataMessageHandler.handleDataPayload(DataMessageHandler.scala:181)
        at org.bitcoins.node.networking.peer.PeerMessageReceiver.handleDataPayload(PeerMessageReceiver.scala:140)
        at org.bitcoins.node.networking.peer.PeerMessageReceiver.handleNetworkMessageReceived(PeerMessageReceiver.scala:122)
        at org.bitcoins.node.networking.P2PClientActor.$anonfun$handleEvent$1(P2PClient.scala:216)
        at org.bitcoins.core.util.FutureUtil$.$anonfun$foldLeftAsync$2(FutureUtil.scala:40)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[INFO] [akkaDeadLetter][08/05/2020 07:45:12.165] [bitcoin-s-akka.actor.default-dispatcher-14] [akka://bitcoin-s/user/P2PClient$-1596631428444] Message [akka.io.Tcp$Received] from Actor[akka://bitcoin-s/system/IO-TCP/selectors/$a/0#826358329] to Actor[akka://bitcoin-s/user/P2PClient$-1596631428444#-1442015776] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [akkaDeadLetter][08/05/2020 07:45:48.806] [bitcoin-s-akka.actor.default-dispatcher-16] [akka://bitcoin-s/user/P2PClient$-1596631428444] Message [akka.io.Tcp$Received] from Actor[akka://bitcoin-s/system/IO-TCP/selectors/$a/0#826358329] to Actor[akka://bitcoin-s/user/P2PClient$-1596631428444#-1442015776] was unhandled. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

```

File: node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala (hunk 1 above)
Comment (benthecarman) [reply node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala:63]: We could do this but it'd complicate the logic a whole bunch, we'd have to change the `DataMessageHandler` to know what headers we have cached, as well as if we received the incorrect headers and need to send another `getheaders` message. I think this should be fine, as a `getheaders` message with all 101 hashes is only `3269` bytes

**Comment by benthecarman** [comment]
> Ok here is what I get when running this:
> 
> ...

So this seemed to be an issue with us not correctly creating the starting `blockchains` for our`ChainHandler`, I changed it to use our new `getBlockchainsBetweenHeights` function to fix this :tm:

**Comment by benthecarman** [comment]
~~So it seems this uncovers another problem :(~~

~~After syncing headers we will get stuck trying to request a block header from the since reorged chain~~

Nvm, had accidentally entered the wrong chainwork for the reorged header, this is not an issue.

**Comment by benthecarman** [comment]
Does not solve deep reorg problems, see #1759

**Review by Christewart — APPROVED** [review]
