### PR TITLE
Fix normalized string comparison

### LINKED ISSUE #2691: DLC Oracle test for enum signing sometimes fails
https://github.com/bitcoin-s/bitcoin-s/pull/2656/checks?check_run_id=1929863942#step:5:789

After doing some testing it seems that it is just the `outcome == tlvOutcomes.head` check that is failing. Likely we are missing somewhere to normalize a string or something

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #2691

### CODE REVIEW

File: core/src/main/scala/org/bitcoins/core/protocol/tlv/TLV.scala [hunk 1]
```diff
@@ -325,6 +325,8 @@ case class NormalizedString(private val str: String) extends NetworkElement {
     other match {
       case otherStr: String =>
         normStr == otherStr
+      case otherNorm: NormalizedString =>
```
Comment (Christewart) [inline core/src/main/scala/org/bitcoins/core/protocol/tlv/TLV.scala:328]: test case to make sure we don't regress in the future?

**Review by Christewart — APPROVED** [review]
