### PR TITLE
Make sure both filter ehaders and filters are empty before sending fi…

### LINKED ISSUE #1933: Syncing fitler headers fails primary key fail
I'm running on 453e02b58b01cd703f39f167c3e0b40a29e55f03

>2020-08-29T14:35:40 INFO [P2P] Requesting compact filter headers from=98000 to=DoubleSha256BDigestBE(000000004956cc2edd1a8caa05eacfa3c69f4c490bfc9ace820257834115ab35)
2020-08-29T14:35:40 INFO [P2P] Got 2000 compact filter header hashes
2020-08-29T14:35:40 ERROR [P2P] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=0000000000000000000000000000000000000000000000000000000000000000, stopHash=00000000a6299059b2bff3479bc569019792e75f3c0f39b10a0bc85eac1b1615 filterHeaders=c03705b2d6fb76a59664f1d63fe8fdbb2dc076d18175fdc51d11c43afaf78a4c...7f4f429ac93cc021dd1e713be69e538ea0c2903b6507e22afddee61499d1c88e)
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.throwex(DB.java:987)
	at org.sqlite.core.DB.executeBatch(DB.java:812)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:72)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.LoggingStatement.$anonfun$executeBatch$1(LoggingStatement.scala:114)
	at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:87)
	at slick.jdbc.LoggingStatement.executeBatch(LoggingStatement.scala:114)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-29T14:35:40 ERROR [P2P] Cannot send a message to our peer when we are not connected! payload=GetCompactFilterHeadersMessage(Basic,UInt32Impl(98000),DoubleSha256Digest(35ab154183570282ce9afc0b494c9fc6a3cfea05aa8c1add2ecc564900000000)) peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333)
2020-08-29T14:36:37 INFO [P2P] Stopping node
2020-08-29T14:36:37 WARN [P2P] Cannot disconnect client that is not connected to socket=neutrino.testnet3.suredbits.com/34.210.154.40:18333!
2020-08-29T14:36:37 INFO [P2P] Awaiting disconnect

### PR DESCRIPTION
**Pull request by Christewart**
…rst filterheader sync message

This seems to fix #1933 

Now we only start syncing compact filter headers when both filters headers and filters are empty inside of `DataMessageHandler`. I'm not exactly sure why this fixes the problem though.

Also it caches `BlockHeader.hashBE` as a minor optimization.

### CODE REVIEW

File: core/src/main/scala/org/bitcoins/core/protocol/blockchain/BlockHeader.scala [hunk 1]
```diff
@@ -125,7 +125,7 @@ sealed trait BlockHeader extends NetworkElement {
     * [[https://bitcoin.stackexchange.com/questions/2063/why-does-the-bitcoin-protocol-use-the-little-endian-notation]]
     * @return
     */
-  def hashBE: DoubleSha256DigestBE = hash.flip
+  lazy val hashBE: DoubleSha256DigestBE = hash.flip
```
Comment (benthecarman) [inline core/src/main/scala/org/bitcoins/core/protocol/blockchain/BlockHeader.scala:128]: I don't think this is an actual optimization because `DoubleSha256Digest.flip` is already a `lazy val`, but good to do this anyways

File: node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala [hunk 2]
```diff
@@ -214,7 +214,9 @@ case class DataMessageHandler(
                 // so we also check if our cached filter heights have been set as well, if they haven't then
                 // we probably need to sync filters
                 if (
-                  appConfig.nodeType == NodeType.NeutrinoNode && (!syncing || filterHeaderHeightOpt.isEmpty || filterHeightOpt.isEmpty)
+                  appConfig.nodeType == NodeType.NeutrinoNode && (!syncing ||
+                  filterHeaderHeightOpt.isEmpty &&
+                  filterHeightOpt.isEmpty)
```
Comment (benthecarman) [inline node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala]: nit: can you put `()` around the 
```
filterHeaderHeightOpt.isEmpty && filterHeightOpt.isEmpty
```
so it's easier to understand

**Review by benthecarman — CHANGES_REQUESTED** [review]
lgtm otherwise

File: core/src/main/scala/org/bitcoins/core/protocol/blockchain/BlockHeader.scala (hunk 1 above)
Comment (Christewart) [reply core/src/main/scala/org/bitcoins/core/protocol/blockchain/BlockHeader.scala:128]: It is, it showing up on visualvm as ~1% of cpu usage when syncing filters

**Review by benthecarman — APPROVED** [review]
