### PR TITLE
Fix unconfirmed -> confirmed state change

### LINKED ISSUE #4815: Payments not transitioning from unconfirmed -> confirmed
The user reported this on 42ef5d15b6569208f4aa6502a262188d11e1df45 (1.9.3)

Screenshot from 2022-10-04 10-38-24

### PR DESCRIPTION
**Pull request by rorp**
Fixes https://github.com/bitcoin-s/bitcoin-s/issues/4815

### CODE REVIEW

File: wallet-test/src/test/scala/org/bitcoins/wallet/UTXOLifeCycleTest.scala [hunk 1]
```diff
@@ -96,6 +96,172 @@ class UTXOLifeCycleTest
...
+      _ = assert(oldUtxos.size + 3 == utxos.size)
+
+      utxo1 = utxos.find(_.txid == txid1).get
+      _ = assert(utxo1.state == PendingConfirmationsReceived)
+      utxo2 = utxos.find(_.txid == txid2).get
+      _ = assert(utxo2.state == PendingConfirmationsReceived)
+      utxo3 = utxos.find(_.txid == txid3).get
+      _ = assert(utxo3.state == PendingConfirmationsReceived)
+
+      // mine the second block
```
Comment (benthecarman) [inline wallet-test/src/test/scala/org/bitcoins/wallet/UTXOLifeCycleTest.scala:174]: blocks 2-5 are all the same, could just make a function and call it 4 times

**Review by benthecarman — COMMENTED** [review]
Test fails on master 👍 , LGTM besides some cleanup

**Review by Christewart — APPROVED** [review]
