### PR TITLE
Fix DLCPayoutCurve Tests

### LINKED ISSUE #2389: Re-enable DLCPayoutCurveTest
We disabled them in #2388 until #2369 is resolved. The reason this is done is so we don't have flaky CI until the dlc spec is changed to avoid these off by one satoshi errors.

### PR DESCRIPTION
**Pull request by nkohen**
Fixes #2389 

`OutcomePayoutPoint` now has the correct types and defers rounding due to `extra_precision` in serialized points which was just added to the specification: [`c4fb12d` (#110)](https://github.com/discreetlogcontracts/dlcspecs/pull/110/commits/c4fb12d95a4255eabb873611437d05b740bbeccc)

I tested locally using the following in my coreTest build (.sbt) file
```
commands += Command.command("testUntilFail") { state =>
  "testOnly org.bitcoins.core.protocol.dlc.DLCPayoutCurveTest" :: "testUntilFail" :: state
}
```
left that running for a really long time and no failures now! I also attempted the above on current master after getting rid of the `ignore` statements and it did generate a failure in less than a minute.

### CODE REVIEW

File: core/src/main/scala/org/bitcoins/core/protocol/dlc/DLCPayoutCurve.scala [hunk 1]
```diff
@@ -68,13 +68,22 @@ case class DLCPayoutCurve(points: Vector[OutcomePayoutPoint]) {
   * isEndpoint: True if this point defines a boundary between pieces in the curve
   */
 sealed trait OutcomePayoutPoint {
-  def outcome: BigDecimal
-  def payout: Satoshis
+  def outcome: Long
+  def payout: BigDecimal
   def isEndpoint: Boolean
 
+  def roundedPayout: Satoshis = {
```
Comment (benthecarman) [inline core/src/main/scala/org/bitcoins/core/protocol/dlc/DLCPayoutCurve.scala:75]: nit: `lazy val`

File: core/src/main/scala/org/bitcoins/core/protocol/dlc/DLCPayoutCurve.scala [hunk 2]
```diff
@@ -68,13 +68,22 @@ case class DLCPayoutCurve(points: Vector[OutcomePayoutPoint]) {
...
+    Satoshis(payout.setScale(0, RoundingMode.FLOOR).toLongExact)
+  }
+
+  def extraPrecision: Int = {
```
Comment (benthecarman) [inline core/src/main/scala/org/bitcoins/core/protocol/dlc/DLCPayoutCurve.scala:79]: nit: `lazy val`

File: core/src/main/scala/org/bitcoins/core/protocol/tlv/TLV.scala [hunk 3]
```diff
@@ -862,7 +866,8 @@ case class TLVPoint(outcome: Long, value: Satoshis, isEndpoint: Boolean)
   override def bytes: ByteVector = {
```
Comment (benthecarman) [inline core/src/main/scala/org/bitcoins/core/protocol/tlv/TLV.scala:866]: nit: `val`

**Review by benthecarman — APPROVED** [review]
