### PR TITLE
2021 04 19 Cleanup after ourselves in postgres tests

### LINKED ISSUE #2920: Postgres wallet threads not being shutdown after test cases
When used `PG_ENABLED=1` and running `walletTest/test` locally all tests pass, but they threads allocated do not get shutdown. I suspect this is why postgres is always failing on CI. 

Here is what i see in visualvm after running `walletTest/test`

Screenshot from 2021-04-19 06-23-55

### PR DESCRIPTION
**Pull request by Christewart**
This fixes #2920 

This makes sure we are shutting down database connection pools when `WalletAppConfig.stop()` is called.

This PR also fixes test cases `BitcoindBackendTest` & `BitcoindBlockPollingTest` which don't use our test fixtures in a conventional way, which means we need to stop the wallet manually inside the test case itself.

### CODE REVIEW

File: async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala [hunk 1]
```diff
@@ -153,7 +154,19 @@ abstract class AsyncUtil extends AsyncUtilApi {
...
 object AsyncUtil extends AsyncUtil {
 
-  private[bitcoins] val scheduler = Executors.newScheduledThreadPool(2)
+  private[this] val threadFactory = new ThreadFactory {
+    private val atomicInteger = new AtomicInteger(0)
+
+    override def newThread(r: Runnable): Thread = {
+      val t = new Thread(
+        r,
+        s"bitcoin-s-async-util-${atomicInteger.getAndIncrement()}")
```
Comment (Christewart) [inline async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala]: added to make threads show up with a name on them with visualvm

**Review by benthecarman — APPROVED** [review]
