### PR TITLE
Fix bug where we didn't set spendingTxId when transitioning from `Reserved` -> `PendingConfirmationsSpent`

### LINKED ISSUE #3888: Single UTXO wallet spending error / DLC accounting error
**Describe the bug**
I started with a wallet with a single reserved UTXO. I try to create a new DLC Offer, but cannot until the UTXO gets its first confirm at 38:08. Then I make a 7 digit numeric offer at 39:15 and a enum offer at 49:15 before another block clears. At 51:19 a block is received and there is an error processing it with "requirement failed: If we have spent a spendinginfodb, the spendingTxId must be defined.". Then I try to sign an 18 digit Accept message made earlier and get an "Error fetching accounting" at 55:47.

One thing to note is that the 7 digit numeric DLC stayed stuck in Broadcasted state even after 6 confirmations. I had previously seen DLCs stuck in Broadcasted state on initiator and non-initiator wallets.

Doing a `rescan --force` updated the Broadcasted DLC to Confirmed state, but oddly did not change the Last Updated date on the contract or on the 18 digit DLC in Signed state. All other contracts had their Last Updated date overwritten with current time even though they did not ultimately have their state changed by the rescan.

This was all done on a Neutrino connected wallet. The bitcoin-s implementation running was commit d393848cc204b92edc3c200faab05c1f72bf3e75

**Logs**
Attached
[1 utxo wallet, make 7 digit numeric, then make enum, then receive block.txt](https://github.com/bitcoin-s/bitcoin-s/files/7679005/1.utxo.wallet.make.7.digit.numeric.then.make.enum.then.receive.block.txt)

**Platform (please complete the following information):**
 - Ubuntu Linux x64

### PR DESCRIPTION
**Pull request by Christewart**
This PR fixes a bug when we try to transition a `Reserved` utxo to `Spent` inside of `TransactionProcessing.processExistingReceivedTxo()`.

The bug was transition a utxo to spent when we are receiving the utxo. A received utxo doesn't have a `spendingTxId`, thus we will violate the invariant that says every utxo that in a spent state must have a `spendingTxId`

### CODE REVIEW

**Review by benthecarman — APPROVED** [review]

**Comment by benthecarman** [comment]
Probably worth adding a test

File: wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala [hunk 1]
```diff
@@ -480,7 +482,6 @@ private[bitcoins] trait TransactionProcessing extends WalletLogger {
           val unreservedTxo = foundTxo.state match {
             case TxoState.Reserved =>
               foundTxo
-                .copyWithSpendingTxId(transaction.txIdBE)
```
Comment (benthecarman) [inline wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala]: why revert this?

**Comment by Christewart** [comment]
> Probably worth adding a test

So i tried to add a test in c2869f8 and can't get it to fail

https://github.com/bitcoin-s/bitcoin-s/blob/c2869f8b626ab1d7aa150d396ad3cea65f6682a1/wallet-test/src/test/scala/org/bitcoins/wallet/UTXOLifeCycleTest.scala#L521

I pushed the code for now as i need to work on something else. I"m not sure why that test case wont fail, i reverted the change to try and verify that the bug fix actually fixes it.

I can't trigger the initial bug in #3888 at all :man_shrugging:

File: wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala [hunk 2]
```diff
@@ -461,6 +461,8 @@ private[bitcoins] trait TransactionProcessing extends WalletLogger {
       transaction: Transaction,
       blockHashOpt: Option[DoubleSha256DigestBE],
       foundTxo: SpendingInfoDb): Future[SpendingInfoDb] = {
+    logger.info(
+      s"processExistingReceivedTxo txId=${transaction.txIdBE.hex} foundingTxo.outPoint=${foundTxo.outPoint}")
```
Comment (Christewart) [inline wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala]: These txids end up being the same, this seems wrong to me?

```
10:53:25.467 INFO Wallet$WalletImpl - processExistingReceivedTxo txId=6d6e8213a449d5797cc3b629f41ce075b30f626a44478e1f071f10a7c9f3199e foundingTxo.outPoint=TransactionOutPoint(6d6e8213a449d5797cc3b629f41ce075b30f626a44478e1f071f10a7c9f3199e:0)
10:53:25.468 INFO Wallet$WalletImpl - processExistingReceivedTxo txId=6d6e8213a449d5797cc3b629f41ce075b30f626a44478e1f071f10a7c9f3199e foundingTxo.outPoint=TransactionOutPoint(6d6e8213a449d5797cc3b629f41ce075b30f626a44478e1f071f10a7c9f3199e:2)
10:53:25.470 INFO Wallet$WalletImpl - processExistingReceivedTxo txId=6d6e8213a449d5797cc3b629f41ce075b30f626a44478e1f071f10a7c9f3199e foundingTxo.outPoint=TransactionOutPoint(6d6e8213a449d5797cc3b629f41ce075b30f626a44478e1f071f10a7c9f3199e:3)
```

You should be able to reproduce with turning the log level = `INFO` and then running

```
 walletTest/testOnly *UTXOLifeCycle* -- -z "mark a utxo as reserved that is still receiving confirmations and not unreserve the utxo"
```

Comment (benthecarman) [reply wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala]: That's right, the tx is the transaction we received in. The outpoint pointing to which output we received with in the transaction. It doesn't have anything to do with spending here

Comment (Christewart) [reply wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala:465]: This isn't right, how can the `spendingTxId` be the same as the `outpoint` txid? You can't have a self referential transaction like that. If we are _receiving_ funds, how can we have a _spending_ txid?
