### PR TITLE
Use database to calculate number of confirmations

### LINKED ISSUE #1780: getconfirmedbalance not working
This is the address on the testnet blockchain: https://blockstream.info/testnet/address/tb1qufh4hy0nse2mn46tsvzs0yp2thew9736fvat06

```
./bitcoin-s-cli getutxos
2ada5ad20661496580dfde529d0f7228db03728479f2fc8ef2306a4ca89ab80001000000 1815403 sats
0644f13e2623cd3020ca38ed97e10fbe54f5dbfa0022da90262b83bfe0b4f7c700000000 30000000 sats
b8a89c1c4bb9b744baf640199fa1bf25e1bedb9d6fc8d1102220801b805604d101000000 20000000 sats
c171dee042da941d568b1c516047d84a6e0aadb8d6d34fe2bf8f1b11ca2eee4d00000000 10000000 sats

➜  bin git:(master) ✗ ./bitcoin-s-cli getconfirmedbalance
0E-8 BTC
➜  bin git:(master) ✗ ./bitcoin-s-cli getbalance
0.60000000 BTC
```

I would expect after that many confirms that `getconfirmedbalance` and `getbalance would return the same thing.

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #1780 

Context: https://github.com/bitcoin-s/bitcoin-s/issues/1780#issuecomment-670966280

This should not be an performance hit to anything too meaningful as `getNumberOfConfirmations` is only used for a few wallet functions

### CODE REVIEW

File: chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala [hunk 1]
```diff
@@ -442,11 +442,9 @@ case class ChainHandler(
...
       case None => FutureUtil.none
       case Some(blockHeight) =>
-        for {
-          tipHash <- getBestBlockHash()
-          tipHeightOpt <- getBlockHeight(tipHash)
-        } yield {
-          tipHeightOpt.map(tipHeight => tipHeight - blockHeight + 1)
+        blockHeaderDAO.chainTips.map { tips =>
+          val bestHeader = tips.maxBy(_.chainWork)
+          Some(bestHeader.height - blockHeight + 1)
```
Comment (Christewart) [inline chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala]: This doesn't seem right. We don't know if the block is apart of these various chains do we? The block we are talking about could be a part of Chain A, but not Chain B?

Comment (benthecarman) [reply chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala]: I'm not sure how we'd solve that without linking headers all the way back

**Review by Christewart — CHANGES_REQUESTED** [review]
This doesn't seem to work for me: 

>➜  bin git:(7aef728b3a) ✗ ./bitcoin-s-cli getblockcount
1806673
➜  bin git:(7aef728b3a) ✗ ./bitcoin-s-cli getconfirmedbalance
0E-8 BTC
➜  bin git:(7aef728b3a) ✗ ./bitcoin-s-cli getblockcount
1806674
➜  bin git:(7aef728b3a) ✗ ./bitcoin-s-cli getconfirmedbalance
0E-8 BTC

**Comment by Christewart** [comment]
Still nothing

>➜  bin git:(33e1166a9a) ✗ ./bitcoin-s-cli getblockcount
1806675
➜  bin git:(33e1166a9a) ✗ ./bitcoin-s-cli getconfirmedbalance
0E-8 BTC
➜  bin git:(33e1166a9a) ✗ ./bitcoin-s-cli getblockcount
1806681
➜  bin git:(33e1166a9a) ✗ ./bitcoin-s-cli getconfirmedbalance
0E-8 BTC

**Comment by benthecarman** [comment]
I did a bunch of txs on this branch today while testing for the release and they are all marked as confirmed in my db. Unsure what the cause could be for @Christewart

File: chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala [hunk 2]
```diff
@@ -442,10 +442,21 @@ case class ChainHandler(
...
         } yield {
-          tipHeightOpt.map(tipHeight => tipHeight - blockHeight + 1)
+          val confs = ancestorChains.flatMap { chain =>
+            if (chain.last.hashBE == blockHash) {
+              Some(chain.head.height - blockHeight + 1)
+            } else None
+          }
+
+          if (confs.nonEmpty) {
+            Some(confs.max)
```
Comment (Christewart) [inline chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala:458]: Is this right? Don't we want to use the "heaviest" confirmation rather than the highest number?

Comment (benthecarman) [reply chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala:458]: We are using `blockHeaderDAO.chainTips` which means all the tips will have equal work. More than likely everything in `confs` will be equal, but we have to pick one, so for some reason if a block is in a chain equal work chain but longer, then I think that's the better chain to pick.

**Review by Christewart — APPROVED** [review]
