### PR TITLE
Stop requesting merkle block messages while in neutrino mode

### LINKED ISSUE #1526: Receiving merkleblock messages while in neutrino mode
**Describe the bug**
In my bitcoin-s.conf file I have `bitcoin-s.node.mode=neutrino` but i'm still reciving merkle block messages which shouldn't be used in the neutrino node

**To Reproduce**
I was running 5b882e9d on mainnet when this happened. It appears that a mainnet block was mined and we requested th merkleblock. I think to see these messages you need to make sure that `bitcoin-s.logging.level=DEBUG`

**Expected behavior**

We should just fetch the full block when in neutrino mode and parse it looking for our outpoints/outputs in that block

**Logs**

> 212 2020-06-06T14:51:49 DEBUG [P2P] Parsed 21 message(s) from bytes: NetworkMessage(NetworkHeader(MainNet,merkleblock,UInt32Impl(67171),ByteVector(4 bytes, 0xd58ccf9b)), Merkle     BlockMessage(MerkleBlockImpl(BlockHeaderImpl(Int32Impl(536928256),DoubleSha256Digest(0     ce369510c722d1291873b85c6e7ad6173b2d05b669b10000000000000000000),DoubleSha256Digest(7f     3bd26ac0dab1a074e7f2e766965997c2143e0962c94046eea950f89c39e781),UInt32Impl(1591455074),UInt32Impl(387219253),UInt32Impl(1186869550)),UInt32Impl(2080),Part

...

>46:8333
2020-06-06T14:53:44 DEBUG [P2P] Received 55 TCP bytes
2020-06-06T14:53:44 DEBUG [P2P] Parsed 1 message(s) from bytes: NetworkMessage(NetworkHeader(MainNet,addr,UInt32Impl(31),ByteVector(4 bytes, 0xc3e5f4c0)), AddrMessageImpl(CompactSizeUInt(1),List(NetworkIpAddressImpl(UInt32Impl(1591454694),ServiceIdentifier(network=true, compactFilters=false, getUtxo=false, bloom=false, witness=true, xthin=false, networkLimited=true),/183.82.184.66,8333))))
2020-06-06T14:53:44 DEBUG [P2P] Unaligned bytes after this: 0
2020-06-06T14:53:44 DEBUG [P2P] Received message=addr from peer=Peer(neutrino.suredbits.com/35.163.36.246:8333) state=Normal
2020-06-06T14:54:24 DEBUG [P2P] Received 32 TCP bytes
2020-06-06T14:54:24 DEBUG [P2P] Parsed 1 message(s) from bytes: NetworkMessage(NetworkHeader(MainNet,ping,UInt32Impl(8),ByteVector(4 bytes, 0xc5fd73d6)), PingMessageImpl(UInt64Impl(15953033562031329305)))
2020-06-06T14:54:24 DEBUG [P2P] Unaligned bytes after this: 0
2020-06-06T14:54:24 DEBUG [P2P] Received message=ping from peer=Peer(neutrino.suredbits.com/35.163.36.246:8333) state=Normal
2020-06-06T14:54:24 DEBUG [P2P] Sending msg=pong to peer=neutrino.suredbits.com/35.163.36.246:8333
Exception in thread "chain.db-3" java.lang.OutOfMemoryError: Java heap space
        at java.base/jdk.internal.reflect.ByteVectorImpl.resize(ByteVectorImpl.java:84)
        at java.base/jdk.internal.reflect.ByteVectorImpl.add(ByteVectorImpl.java:63)
        at java.base/jdk.internal.reflect.ClassFileAssembler.emitByte(ClassFileAssembler.java:74)
        at java.base/jdk.internal.reflect.ClassFileAssembler.emitConstantPoolUTF8(ClassFileAssembler.java:107)
        at java.base/jdk.internal.reflect.AccessorGenerator.emitBoxingContantPoolEntries(AccessorGenerator.java:292)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:353)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:55)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.security.Provider.newInstanceUtil(Provider.java:153)
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1824)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at java.base/java.security.Security.getImpl(Security.java:700)
        at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:178)
        at org.bitcoins.crypto.CryptoUtil.sha256(CryptoUtil.scala:31)
        at org.bitcoins.crypto.CryptoUtil.sha256$(CryptoUtil.scala:30)
        at org.bitcoins.crypto.CryptoUtil$.sha256(CryptoUtil.scala:128)
 213 2020-06-06T14:51:49 DEBUG [P2P] Unaligned bytes after this: 58
 214 2020-06-06T14:51:49 DEBUG [P2P] Received message=merkleblock from peer=Peer(neutrino.s     uredbits.com/35.163.36.246:8333) state=Normal
 215 2020-06-06T14:51:49 DEBUG [P2P] Received merkle block, expecting 2080 TX(s)
 216 2020-06-06T14:51:49 DEBUG [P2P] Received message=tx from peer=Peer(neutrino.suredbits.     com/35.163.36.246:8333) state=Normal
 217 2020-06-06T14:51:49 DEBUG [P2P] Transaction=DoubleSha256BDigestBE(15cf49cc10410e32d4bc     7250086473ea919f8fc250afb3d4b633a447f345870a) matched merkleBlock=DoubleSha256BDigestB     E(0000000000000000000f73b30d9310a79378b8681a8ba19a7648c83a01126888)

**Additional context**

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #1526 

Closed #1727 but then figured out a way to do it.

### CODE REVIEW

File: node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala [hunk 1]
```diff
@@ -312,7 +312,10 @@ case class DataMessageHandler(
     logger.info(s"Received inv=${invMsg}")
     val getData = GetDataMessage(invMsg.inventories.map {
       case Inventory(TypeIdentifier.MsgBlock, hash) =>
-        Inventory(TypeIdentifier.MsgFilteredBlock, hash)
+        // only request the merkle block if we are spv enabled
+        if (appConfig.isSPVEnabled) {
+          Inventory(TypeIdentifier.MsgFilteredBlock, hash)
+        } else Inventory(TypeIdentifier.MsgBlock, hash)
```
Comment (Christewart) [inline node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala:318]: Hmm.... so is this going to cause us to fetch a full block twice when we are running in neutrino mode?

Comment (benthecarman) [reply node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala:318]: No, the inventory will just send us a list of blocks, not the full blocks, so after receiving it this way, we can then request the full one.

https://developer.bitcoin.org/reference/p2p_networking.html#inv

**Review by Christewart — APPROVED** [review]

File: node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala (hunk 1 above)
Comment (Christewart) [reply node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala:318]: My main concern here is that things are working _without_ sending this `TypeIdentifier.MsgBlock` back to the peer in neutrino mode. So do we really need to send it again? If we are talking about #1093 this `TypeIdentifier.MsgBlock` doesn't seem necessary since neutrino works as expected :tm: but we are just receiving unecessary spv messages

Comment (benthecarman) [reply node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala:318]: According to [this](https://developer.bitcoin.org/reference/p2p_networking.html#inv), inventory messages will be sent for "announcements of new transactions or blocks, or it can be sent in reply to a “getblocks” message or “mempool” message."

In the case we are in neutrino mode we could be sending `getblocks` for filter matches and in those cases we would want to process the block, not the filtered block. It may be we have just gotten lucky we haven't run into the issue yet.
