### PR TITLE
Reduce number of rows selected by best filter header/best filter query

### LINKED ISSUE #2616: bundle/run throws strange exception
I was running `bundle/run` on 865f1a6d with testnet sqlite3 database. If you look at the _very_ bottom of the longs I get a very weird exception. I'm wondering if it has something to do with server startup time (again) which took `13553ms`

>[info] 2021-02-02T22:21:30UTC INFO [BitcoinSServerMain] version=0.4.0+303-865f1a6d-SNAPSHOT
[info] 2021-02-02T22:21:30UTC INFO [BitcoinSServerMain] networkDatadir=/home/chris/.bitcoin-s/testnet3
[info] 2021-02-02T22:21:30UTC INFO [ActorSystemImpl] Akka logger started
[info] 2021-02-02T22:21:31UTC INFO [VersionPrinter] Flyway Community Edition 6.4.2 by Redgate
[info] 2021-02-02T22:21:31UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/chaindb.sqlite (SQLite 3.34)
[info] 2021-02-02T22:21:31UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/nodedb.sqlite (SQLite 3.34)
[info] 2021-02-02T22:21:31UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/old-wallet/walletdb.sqlite (SQLite 3.34)
...
[info] 2021-02-02T22:21:46UTC INFO [NeutrinoNode] Our node has been full started. It took=13553ms
[info] 2021-02-02T22:21:46UTC INFO [NeutrinoNode] Started node, best block hash 000000000000002738246e8a322cd5f4ad4f0b006cada7e061d4a441f59e2c05 at height 1931771, with 1931769 filter headers and 1931769 filters
[info] 2021-02-02T22:21:46UTC INFO [DbValidate] Successfully validated 9 migrations (execution time 00:00.009s)
[info] 2021-02-02T22:21:46UTC INFO [DbMigrate] Current version of schema "main": 9
[info] 2021-02-02T22:21:46UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2021-02-02T22:21:48UTC INFO [BitcoinSServerMain] Starting neutrino node sync
[info] 2021-02-02T22:21:48UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
[info] 2021-02-02T22:21:49UTC INFO [ActorSystemImpl] http-rpc-server: Response for
[info]   Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.9, Host: localhost:9999, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,83 bytes total),HttpProtocol(HTTP/1.1))
[info]   Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,39 bytes total),HttpProtocol(HTTP/1.1)))
[info] 2021-02-02T22:21:59UTC INFO [ActorSystemImpl] Request timeout encountered for request [POST / Strict(64 bytes)]
[error] Exception in Application start method

### PR DESCRIPTION
**Pull request by Christewart**
fixes #2616 and is related to past work in #2568 

Basically this reduces the number of rows selected in the filter header/filter queries to be the last difficulty Interval (2016 filters/filter headers)

With this change, it seems these queries run really fast now. 

>[info] 2021-02-03T12:39:48UTC ERROR [CompactFilterDAO] Took 18ms to execute getBestFilterHeight

>[info] 2021-02-03T12:39:44UTC ERROR [CompactFilterDAO] Took 15ms to execute getBestFilterHeight

>[info] 2021-02-03T12:39:41UTC ERROR [CompactFilterHeaderDAO] Took 9ms to execute getBestFilterHeaderHeight

when measuring this off of 865f1a6d460108325cc8a0a94621b205c13a5d8c (current master) these two queries would take roughly ~6 seconds and ~12 seconds on sqlite. 

>2021-02-02T22:59:11UTC ERROR [CompactFilterDAO] Took 6160ms to execute getBestFilterHeight
2021-02-02T22:59:17UTC ERROR [CompactFilterHeaderDAO] Took 12297ms to execute getBestFilterHeaderHeight

### CODE REVIEW

File: chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala [hunk 1]
```diff
@@ -124,7 +124,11 @@ case class CompactFilterHeaderDAO()(implicit
   private val bestFilterHeaderQuery = {
     val join = table
       .join(blockHeaderTable)
-      .on(_.blockHash === _.hash)
+      //sort by height as an optimization
+      .sortBy(_._1.height.desc)
+      //just take the last 2016 headers, if we have a reorg larger than
+      //this we will not be able to retrieve that header
+      .take(appConfig.chain.difficultyChangeInterval)
```
Comment (benthecarman) [inline chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala:131]: This should make it slower, it should be faster if we do what we are doing for filters:

```
.map(_.headOption.map(_.height))
 ```

Comment (benthecarman) [reply chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala:131]: However, these seem like they should resolve to the same sql query

Comment (Christewart) [reply chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala:131]: That will not reduce the set size, the point of the `.take()` is to make sure that the subsequent `max`/[`filter`](https://github.com/christewart/bitcoin-s-core/blob/5ce5b71250ec184c8348517a8fe36ca3ba351e51/chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala#L136) call is not done over the _entire_ table. Only 2016 headers. 


Breaking down the calls 

1. `.sortBy()` is O(n) (we need to look through the entire table to establish an ordering of heights
2.  [`.max`](https://github.com/christewart/bitcoin-s-core/blob/5ce5b71250ec184c8348517a8fe36ca3ba351e51/chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala#L133) is O(n).
3. [filter](https://github.com/christewart/bitcoin-s-core/blob/5ce5b71250ec184c8348517a8fe36ca3ba351e51/chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala#L136) is also O(n)

If we reduce set size from ~2 million testnet headers, to just 2016 testnet headers, we should see significant performance improvements even if the algorithm is still `O(n^3)` 

This same methodology is applied to the filter table as well

**Comment by Christewart** [comment]
I'm running into issues because it appears that the max chain work portion of the query is not working

https://github.com/bitcoin-s/bitcoin-s/pull/2617/files#diff-d11e2e384dce366db5cedeb097cc2a569e18a375b91537ab7087e7bb43ca2300R133

It seems to return everything on postgres, rather then just the block header with the max chainwork

File: chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala (hunk 1 above)
Comment (benthecarman) [reply chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala:131]: Because of our indexes it shouldn't be O(n) it should be O(log n)

Comment (benthecarman) [reply chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala:131]: Also this removes the safety of checking by chain work

**Review by benthecarman — APPROVED** [review]
