### PR TITLE
2020 03 15 chainhandler getnancestor

### LINKED ISSUE #806: Filter header batch size does not match block header batch size 1959 != 1960
When starting my node and receiving filters i get this error:

https://pastebin.com/FLMxB50J

### PR DESCRIPTION
**Pull request by Christewart**
This PR addresses #806 

Previously when fetching headers from the database, we would just select headers between a height range and then return the headers in this range from `BlockHeaderDAO.getNChildren()`. 

This doesn't work because we can have multiple block headers at the same height. This PR does two things: 

1. Renames `getNChildren()` -> `getNAncestors()` as that is what we are actually doing
2. Calls `Blockchain.connectWalkBackwards()` on the headers returned from `BlockHeaderDAO.getNAncestors()` to validate that we can actually form a blockchain with what is returned from the database.

closes #806

### CODE REVIEW

File: core/src/main/scala/org/bitcoins/core/script/constant/BytesToPushOntoStack.scala [hunk 1]
```diff
@@ -25,7 +25,7 @@ object BytesToPushOntoStack
     override val opCode = num
   }
 
-  override def operations: Seq[BytesToPushOntoStack] =
+  override val operations: Seq[BytesToPushOntoStack] =
```
Comment (Christewart) [inline core/src/main/scala/org/bitcoins/core/script/constant/BytesToPushOntoStack.scala:28]: this is a quick optimization so we don't re-create `BytesToPushOntoStack` everytime we parse a script.

Comment (benthecarman) [reply core/src/main/scala/org/bitcoins/core/script/constant/BytesToPushOntoStack.scala:28]: Should this be `lazy`?

Comment (Christewart) [reply core/src/main/scala/org/bitcoins/core/script/constant/BytesToPushOntoStack.scala:28]: nah, it doesn't really matter `lazy` or `val`, the problem is it being a `def` so it has to be recreated _everytime_

File: chain/src/main/scala/org/bitcoins/chain/pow/Pow.scala [hunk 2]
```diff
@@ -42,10 +42,16 @@ sealed abstract class Pow {
...
-                throw new RuntimeException(
-                  s"Could not find non mindiffulty block in chain! hash=${tip.hashBE.hex} height=${currentHeight}")
+              case None =>
+                config.chain match {
+                  case RegTestNetChainParams =>
+                    RegTestNetChainParams.compressedPowLimit
+                  case TestNetChainParams | MainNetChainParams =>
+                    //if we can't find a non min diffulty block, let's just fail
+                    throw new RuntimeException(
+                      s"Could not find non mindiffulty block in chain of size=${blockchain.length}! hash=${tip.hashBE.hex} height=${currentHeight}")
```
Comment (rorp) [inline chain/src/main/scala/org/bitcoins/chain/pow/Pow.scala]: A typo in "mindiffulty" ?

File: chain/src/main/scala/org/bitcoins/chain/models/BlockHeaderDAO.scala [hunk 3]
```diff
@@ -141,20 +141,31 @@ case class BlockHeaderDAO()(
...
       }
     } yield {
-      res
+      if (headerOpt.isDefined) {
+        val connectedHeaders =
+          Blockchain.connectWalkBackwards(headerOpt.get, headers)
+        connectedHeaders.reverse
+      } else {
+        Vector.empty
+      }
```
Comment (rorp) [inline chain/src/main/scala/org/bitcoins/chain/models/BlockHeaderDAO.scala]: `headerOpt.get` looks a bit brutal. Maybe`headerOpt.map(...).getOrElse(Vector.empty)`?
