### PR TITLE
Give gui command line arguments

### LINKED ISSUE #1930: ./bitcoin-s-bundle --datadir not working
It looks like the server is not getting spun up correct? I am using a non standard `--rpcport` 

>java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
        at com.softwaremill.sttp.HttpURLConnectionBackend.writeBody(HttpURLConnectionBackend.scala:89)
        at com.softwaremill.sttp.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:44)
        at com.softwaremill.sttp.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:19)
        at com.softwaremill.sttp.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:17)
        at com.softwaremill.sttp.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:12)
        at com.softwaremill.sttp.RequestT.send(RequestT.scala:246)
        at org.bitcoins.cli.ConsoleCli$.$anonfun$exec$1(ConsoleCli.scala:941)
        at scala.util.Try$.apply(Try.scala:210)
        at org.bitcoins.cli.ConsoleCli$.exec(ConsoleCli.scala:925)
        at org.bitcoins.gui.WalletGUIModel.updateBalance(WalletGUIModel.scala:68)
        at org.bitcoins.gui.WalletGUIModel.<init>(WalletGUIModel.scala:23)
        at org.bitcoins.gui.WalletGUI$.delayedEndpoint$org$bitcoins$gui$WalletGUI$1(WalletGUI.scala:58)
        at org.bitcoins.gui.WalletGUI$delayedInit$body.apply(WalletGUI.scala:16)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scalafx.application.JFXApp.$anonfun$init$1(JFXApp.scala:302)
        at scalafx.application.JFXApp.$anonfun$init$1$adapted(JFXApp.scala:302)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
        at scalafx.application.JFXApp.init(JFXApp.scala:302)
        at scalafx.application.JFXApp.init$(JFXApp.scala:302)
        at org.bitcoins.gui.WalletGUI$.init(WalletGUI.scala:16)
        at scalafx.application.AppHelper.start(AppHelper.scala:33)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:834)

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #1930

### CODE REVIEW

File: app/gui/src/main/scala/org/bitcoins/gui/WalletGUI.scala [hunk 1]
```diff
@@ -32,6 +32,23 @@ object WalletGUI extends JFXApp {
       }
     )
 
+  private val argsWithIndex = parameters.raw.zipWithIndex
+
+  val rpcPortOpt: Option[Int] = {
```
Comment (Christewart) [inline app/gui/src/main/scala/org/bitcoins/gui/WalletGUI.scala:37]: Any way we can factor code like this into a shared trait between everything that `extends App` so we don't have to remember to update different places every time we add an option?

**Review by Christewart — APPROVED** [review]
