### PR TITLE
Fixed `getAddressInfo` RPC for bitcoind versions 18 and 19

### LINKED ISSUE #1628: NPE exception thrown for bitcoind getaddressinfo
Reported by a user on gitter, from a quick glance it looks like we have `getaddressinfo` tests for V17 of the rpc client, but not any later versions. Perhaps they changed the API? 

https://gitter.im/bitcoin-s-core/Lobby

>Hi! Anybody here? I have a problem with bitcoin-s
rpcCli
.getAddressInfo(BitcoinAddress("3EHFYhtgSvWAyDusrQHBEQnqDkhayCXLiz").get)
.onComplete(
addresInfo => println(addresInfo.get)
)
this code throws an error
[bitcoind-rpc-client-created-by-bitcoin-s-akka.actor.default-dispatcher-2] ERROR o.b.r.c.c.BitcoindRpcClient - Error when parsing result of 'getaddressinfo': {"obj":[{"msg":["error.expected.jsobject"],"args":[]}]}!JSON: null
java.lang.IllegalArgumentException: Could not parse JsResult: null! Error: Error when parsing result of 'getaddressinfo': {"obj":[{"msg":["error.expected.jsobject"],"args":[]}]}!
at org.bitcoins.rpc.client.common.Client.parseResult(Client.scala:348)
at org.bitcoins.rpc.client.common.Client.$anonfun$bitcoindCall$2(Client.scala:264)
at scala.util.Success.$anonfun$map$1(Try.scala:255)
at scala.util.Success.map(Try.scala:213)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:64)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

### PR DESCRIPTION
**Pull request by nkohen**
Should fix #1628 (I think)

### CODE REVIEW

File: app-commons/src/main/scala/org/bitcoins/commons/jsonmodels/bitcoind/WalletResult.scala [hunk 1]
```diff
@@ -204,7 +204,30 @@ case class UnspentOutput(
...
+sealed trait AddressInfoResult extends WalletResult {
+  def address: BitcoinAddress
+  def scriptPubKey: ScriptPubKey
+  def ismine: Boolean
+  def iswatchonly: Boolean
+  def isscript: Boolean
+  def iswitness: Boolean
+  def iscompressed: Option[Boolean]
+  def witness_version: Option[WitnessVersion]
+  def witness_program: Option[String] // todo what's the correct type here?
```
Comment (benthecarman) [inline app-commons/src/main/scala/org/bitcoins/commons/jsonmodels/bitcoind/WalletResult.scala:216]: Looks like it is a hash of the key or script

https://github.com/bitcoin/bitcoin/blob/master/src/rpc/util.cpp#L244

**Review by benthecarman — APPROVED** [review]

**Review by Christewart — COMMENTED** [review]
Can we add a unit test to verify this?
