### PR TITLE
Fix WalletAppConfig.hasWallet for Postgres

### LINKED ISSUE #1554: WalletAppConfig.hasWallet() does not work for postgres
The current implementation: 

https://github.com/bitcoin-s/bitcoin-s/blob/master/app/server/src/main/scala/org/bitcoins/server/Main.scala#L156

We just detect if there are files on disk. This will not work for postgres, we need a different way to detect if postgres is setup with a wallet correctly.

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #1554

### CODE REVIEW

File: wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala [hunk 1]
```diff
@@ -136,14 +136,20 @@ case class WalletAppConfig(
...
-    val hdCoin = defaultAccount.coin
-    if (Files.exists(walletDB) && seedExists()) {
-      AccountDAO()(ec, this).read((hdCoin, 0)).map(_.isDefined)
+  private def hasWallet()(
+      implicit walletConf: WalletAppConfig,
+      ec: ExecutionContext): Future[Boolean] = {
+    if (walletConf.seedExists()) {
+      val hdCoin = walletConf.defaultAccount.coin
+      val walletDB = walletConf.dbPath resolve walletConf.dbName
+      if (walletConf.driverName == "postgresql" || Files.exists(walletDB)) {
```
Comment (Christewart) [inline wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala:148]: @rorp is this enough to deteremine that postgres is enabled and the wallet is configured correctly?

Comment (rorp) [reply wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala:148]: Yes, I think so.
